code/game/src/character/DungeonCharacter.java, code/game/src/character/monster/Imp.java, code/game/src/character/monster/Monster.java, code/game/src/character/player/Hero.java, code/game/src/collision/Collidable.java, code/game/src/collision/CollidableLevel.java, code/game/src/collision/CollisionMap.java, code/game/src/collision/Hitbox.java, code/game/src/collision/RectCollidable.java, code/game/src/collision/TileCollidable.java, code/game/src/mydungeon/Starter.java
fixes #17 
Ich habe jetzt mal die `Hitbox` erweitert. Was jetzt aktuell vielleicht noch zu einem Problem führen kann, ist nicht quadratische Hitboxen, da ich aus Gründen der Einfachheit beim `Hitbox#collide`, mit statischen Werten angelegt habe anstelle von den Winkelgrenzen jedes Mal neu zu berechnen.
Der Aktuelle Stand hier die roten linien sind hilfreich vielleicht lohnt es sich dies einmal richtig einzubauen und nicht nur als hack.
=> [GAME] Hitbox System verbessern

game/src/character/objects/Item.java, game/src/character/objects/TreasureChest.java, game/src/mydungeon/Starter.java
fixes #55 
- Schatztruhe als Dungeonelement implementiert
- Collisionsystem zum Einsammeln verwendet
- Dummy Item-Interface angelegt
=> [GAME] Added treasure chest

dsl/src/interpreter/DSLInterpreter.java, dsl/src/runtime/GameEnvironment.java, dsl/src/runtime/IEvironment.java, dsl/src/runtime/nativeFunctions/NativePrint.java, dsl/src/semanticAnalysis/IScope.java, dsl/src/semanticAnalysis/ScopedSymbol.java, dsl/src/semanticAnalysis/SymbolTableParser.java, dsl/test/helpers/Helpers.java
Enables dynamically loading of data types and functions definitions in an environment. This can be used to increase testability of component based definitions and to create environments for different use-cases (e.g. testing the structure of an AST via a DSL-function)
=> Add environments to store types and function definitions

game/src/ecs/systems/DrawSystem.java, game/src/ecs/systems/ECS_System.java, game/src/ecs/systems/SystemController.java, game/src/mydungeon/ECS.java, game/test/ecs/systems/ECS_SystemTest.java
fixes #76 
- Jedes `ECS_System` hat ein `boolean run` einen entsprechenden getter und eine toggle-funktion.
- der `SystemController` updated nur Systeme deren `run=true` ist 
- Default Implementierung im `ECS_System` 
- Systeme die nicht pausiert werden dürfe (z.B `DrawSystem`) überschreiben die `toggleRun` Methode
- Statische `togglePause` Methode im `ECS` angelegt, welche für jedes System die toggle Funktion aufruft. 
- incl Unit Tests
=> [GAME] Pause 

game/src/ecs/components/AnimationComponent.java, game/src/ecs/components/AnimationList.java, game/src/ecs/entitys/Hero.java, game/src/ecs/systems/AnimationSystem.java, game/src/mydungeon/ECS.java, game/test/ecs/components/AnimationComponentTest.java, game/test/ecs/systems/DrawSystemTest.java
Idee für #94 
Die Idee:
In  der neuen Klassen `AnimationList` werden alle Animationen einer Entität gespeichert. Dabei gibt es für jeden "Anwendungsfall" ein konkretes Attribut. Eine Entität muss nicht alle Animationen haben (eine Kiste bewegt sich z.B nicht). 
Anstelle einer Java-Liste mit Animationen wird dem `AnimationComponent` jetzt die `AnimationList` der Entität übergeben (Benennung ist evtl. etwas doof, da doppeldeutig).
Das `AnimationSystem` iteriert über jede Entität mit einem `AnimationComponent` und prüft anhand der Werte der anderen Components, welche Animation jetzt die `currentAnimation` sein muss. 
Dafür haben die Components eine (selbst ausgedachte) Priorität. Schlaganimation > Bewegungsanimation etc. Das konnte ich jetzt noch nicht implementieren, weil wir nur Bewegung …
=> [GAME] Animation System

dsl/src/antlr/DungeonDSL.g4, dsl/src/interpreter/DSLInterpreter.java, dsl/src/runtime/GameEnvironment.java, dsl/src/runtime/IEvironment.java, dsl/src/semanticAnalysis/types/AdaptedType.java, dsl/src/semanticAnalysis/types/AggregateTypeAdapter.java, dsl/src/semanticAnalysis/types/DSLTypeAdapter.java, dsl/src/semanticAnalysis/types/IType.java, dsl/src/semanticAnalysis/types/TypeBuilder.java, dsl/src/semanticAnalysis/types/TypeInstantiator.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/interpreter/mockECS/ExternalType.java, dsl/test/interpreter/mockECS/ExternalTypeBuilder.java, dsl/test/interpreter/mockECS/TestComponentWithExternalType.java, dsl/test/semanticAnalysis/TestTypeBinder.java, dsl/test/semanticAnalysis/types/RecordBuilder.java, dsl/test/semanticAnalysis/types/TestRecordComponent.java, dsl/test/semanticAnalysis/types/TestRecordUser.java, dsl/test/semanticAnalysis/types/TestTypeBuilder.java, dsl/test/semanticAnalysis/types/TestTypeInstantiator.java, game/src/dslToGame/AnimationBuilder.java, game/src/ecs/components/AnimationComponent.java, game/src/ecs/components/PositionComponent.java, game/src/mydungeon/ECS.java
Fixes #133 
Aktuell besteht das Problem, dass die Komponenten, die per DSL-Eingabe erstellt werden, "in der Luft hängen", also weder in die `Entity` eingehangen werden, noch in einer globalen Liste landen. Das wird momentan noch manuell nach der DSL-Eingabe (in `Entity::setupDSLInput()`) gemacht.
@AMatutat füg gerne noch weitere Issues hinzu, die von deiner Seite hier gefixt werden, da hast du den besseren Überblick
=> [DSL->GAME] DSL monster definition prototype

game/src/ecs/components/ai/AITools.java
Fixes #185 
Das Problem liegt darin, dass, selbst wenn der Pfad bereits abgeschlossen wurde, wird immer noch versucht, das nächste Element im Pfad anzulaufen.
Außerdem ist ein kleiner Schutz gegen das Verlassen des Pfades eingebaut. Falls das neue Tile nicht Teil des gemerkten Pfads wäre.
=> [GAME] fix falschen Path abfrage in AITools

game/src/ecs/components/ai/AIComponent.java, game/src/ecs/components/ai/fight/CollideAI.java
Fixes #88 
Erste Idee war, sobald die rushrange erreicht ist direkt auf den Player zuzulaufen, dies habe ich aber weggeworfen, da es sonst zu viele Edge Cases gibt, welche Probleme erstellen würden.
z.b. Diagonales movement und laufen gegen eine Wand wegen einer Kante 
- New IFightAI CollideAI
Verhalten 
- Nah dran berechne Pfad jedes Mal neu, damit es sich aktiver anfühlt
- weiter entfernt berechne Pfad nur alle X Frames neu identisch zu MeleeAI
=> [GAME] add logic for CollideAI

game/test/ecs/EntityTest.java, game/test/ecs/components/AIComponentTest.java, game/test/ecs/components/AnimationComponentTest.java, game/test/ecs/components/PlayableComponentTest.java, game/test/ecs/components/PositionComponentTest.java, game/test/ecs/components/SkillComponentTest.java, game/test/ecs/components/SkillTest.java, game/test/ecs/components/VelocityComponentTest.java, game/test/ecs/systems/AISystemTest.java, game/test/ecs/systems/DrawSystemTest.java, game/test/ecs/systems/ECS_SystemTest.java, game/test/ecs/systems/VelocitySystemTest.java
Die ECS Testfälle waren zwar (meist) alle Sinnvoll, aber nicht einheitlich. 
Ich hab etwas aufgeräumt
- Präfix "test" entfernt
- Einheitliche Bennung von `setup`
- Tests für Missing-Components hinzugefügt
- Weitere (kleinere) Tests hinzugefügt
- Mockito verwendet wo sinnvoll
- Kleinere Code Anpassungen
=> [GAME] Cleanup Tests

game/src/ecs/components/AnimationComponent.java, game/src/ecs/components/HitboxComponent.java, game/src/ecs/components/PositionComponent.java, game/src/ecs/components/VelocityComponent.java, game/src/ecs/components/ai/AIComponent.java
fixes #186 
- Alle Components haben jetzt eine `name in der `DSLType` Annotation
- Alle Attribute haben jetzt ein `name` in der `DSLTypeMemeber`Annotation
- Teilweise noch auskommentiert (siehe #207)
=> [GAME] add names to DSLType(Members)

dsl/src/interpreter/DSLInterpreter.java, dsl/src/runtime/Value.java, dsl/src/semanticAnalysis/types/TypeInstantiator.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/semanticAnalysis/types/ComponentWithExternalTypeMember.java, dsl/test/semanticAnalysis/types/ComponentWithInterfaceMember.java, dsl/test/semanticAnalysis/types/ITestInterface.java, dsl/test/semanticAnalysis/types/TestTypeBuilder.java
Fixes #207 
Der Interpreter wirft keine Exception mehr, wenn der an `createDefaultValue` übergeben `type` null ist (was der Fall ist, falls es keine DSL Repräsentation für einen Java-Typen gibt). Die mit `@DSLTypeMember` markierten Member der erzeugten Java-Instanzen sind anschließend `null`.
Tests wurden um einen entsprechenden Testcase ergänzt.
=> [DSL] Dont crash on unsupported data types

doc/dsl/interpretation-laufzeit.md, doc/dsl/sprachkonzepte.md, doc/dsl/typebuilding.md, doc/dsl/typsystem.md, doc/dsl/ueberblick.md
Da wir uns in #161 darauf geeinigt haben, die technische Doku im `doc/` Ordner zu führen:
Das hier ist der aktuelle Stand der DSL-Doku aus dem Wiki. Die Links habe ich für die lokalen Dateien angepasst.
Da in der Doku noch sehr viel WIP ist, würde ich das gerne nach und nach in mehreren PRs fertigstellen und diesen PR nur auf das Rüberziehen aus dem Wiki beschränken.
=> [DSL] Move DSL documentation to doc/dsl/ 

dsl/src/antlr/DungeonDSL.g4, dsl/src/interpreter/DSLInterpreter.java, dsl/src/parser/AST/AggregateValueDefinitionNode.java, dsl/src/parser/AST/AstVisitor.java, dsl/src/parser/AST/Node.java, dsl/src/parser/DungeonASTConverter.java, dsl/src/semanticAnalysis/SymbolTableParser.java, dsl/src/semanticAnalysis/types/TypeBinder.java, dsl/test/interpreter/mockECS/ExternalTypeBuilderMultiParam.java, dsl/test/parser/TestDungeonASTConverter.java
Fixes #248
`ComponentDefinitionNode` wurde zu `AggregateValueDefinitionNode` umbenannt, da dieser AST-Knoten nicht mehr nur zur Komponenten-Definition in `GameObjectDefinitionNodes` verwendet wird.
=> [DSL] Support inline definition of aggregate value in grammar

doc/dsl/typebuilding.md, dsl/src/semanticAnalysis/types/AggregateTypeAdapter.java, dsl/src/semanticAnalysis/types/DSLTypeMember.java, dsl/src/semanticAnalysis/types/TypeBuilder.java, dsl/test/interpreter/mockECS/ExternalTypeBuilderMultiParam.java, dsl/test/semanticAnalysis/types/TestTypeBuilder.java
Fixes #267 
- Erzeuge ein `AggregateTypeAdapter` mittels `TypeBuilder` in `registerTypeAdapter`
- Füge Unit Tests für `TypeBuilder` hinzu 
- Dokumentation um Type-Builder-Methoden mit mehreren Parametern ergänzen
=> [DSL] Create `AggregateTypeAdapter` for multi parameter builder methods

game/src/ecs/components/AnimationComponent.java, game/src/ecs/components/Component.java, game/src/ecs/components/HitboxComponent.java, game/src/ecs/components/PlayableComponent.java, game/src/ecs/components/PositionComponent.java, game/src/ecs/components/VelocityComponent.java, game/src/ecs/components/ai/AIComponent.java, game/src/ecs/components/ai/AITools.java, game/src/ecs/components/skill/SkillComponent.java, game/src/ecs/entities/Entity.java, game/src/ecs/systems/AISystem.java, game/src/ecs/systems/CollisionSystem.java, game/src/ecs/systems/DrawSystem.java, game/src/ecs/systems/KeyboardSystem.java, game/src/ecs/systems/VelocitySystem.java, game/src/mydungeon/ECS.java, game/test/ecs/EntityTest.java, game/test/ecs/systems/AISystemTest.java, game/test/ecs/systems/DrawSystemTest.java, game/test/ecs/systems/VelocitySystemTest.java
fixes #247  und #243 
- Remove static name in Components
- Benutze `.class` um Components zu identifizieren
- Tests angepasst
=> [GAME] use .class for Component identification

game/src/hud/PauseMenu.java, game/src/mydungeon/ECS.java
fixes #114 
Ich hatte nochmal kontrolliert, ob es möglich wäre, das UI ins ECS zu übernehmen. Da es sicher schöner wäre.
Es gibt so ein paar Punkte, wo sich das UI grundsätzlich unterscheidet.
- Das UI nutzt nicht das Weltkoordinatensystem
- Das UI nutzt nicht das Point als aktuelle Position, da die darunter liegenden UI Elemente von libgdx stammen.
- Und manche Komponenten könnten verwirrend sein, warum beim UI sie nichts machen etc.
In diesem PR soll eine visuelle Unterstützung gegeben werden, ob das Spiel aktuell läuft oder eben nicht.
=> [GAME] Pause-Menü

dsl/src/antlr/DungeonDSL.g4, dsl/src/parser/DungeonASTConverter.java, dsl/test/parser/TestDungeonASTConverter.java
Fixes #343
Erweitert die Grammatik um Funktionsdefinitionen mit optionalen Parametern, optionalem Rückgabewert und Funktionsrumpf.
Note:
Die Deklaration des Rückgabetyps ist optional. Um allerdings ein einheitliches Bild der Funktionsdefinitionen zu schaffen, wird der Rückgabetyp hinter dem `fn` Keyword, dem Funktionsnamen und den Klammern (also dem, was es immer gibt) deklariert.
Also:
```
fn test_func() {
...
}
fn test_func_ret() -> int {
...
}
```
statt 
```
fn test_func() {
...
}
fn int test_func_ret() {
...
}
```
=> [DSL] Grammatik für Funktionsdefinitionen erweitern

dsl/src/parser/AST/AstVisitor.java, dsl/src/parser/AST/FuncDefNode.java, dsl/src/parser/AST/Node.java, dsl/src/parser/AST/ParamDefNode.java, dsl/src/parser/DungeonASTConverter.java, dsl/test/parser/TestDungeonASTConverter.java
Fixes #344 
Fügt Klassen für nötige AST-Knoten (`ParamDefNode` und `FuncDefNode`) hinzu.
Implementiert Zusammenfassung von Knoten in DungeonASTConverter.
Fügt zwei Testfälle für AST-Konvertierung von Funktionsdefinitionen hinzu.
=> [DSL] AST für Funktionsdefinition erstellen

game/src/ecs/components/HealthComponent.java, game/src/ecs/components/IOnDeathFunction.java, game/src/ecs/damage/Damage.java, game/src/ecs/damage/DamageType.java, game/src/ecs/systems/HealthSystem.java, game/src/mydungeon/ECS.java, game/test/ecs/components/HealthComponentTest.java, game/test/ecs/systems/HealthSystemTest.java
fixes #227  and #228 
- `Damage` und `enum DamageType` hinzugefügt, um später die Implementierungen von komplexeren Schadensberechnungen zu vereinfachen.
- `HealthComponent` hinzugefügt 
- `IOnDeathFunction` hinzugefügt, wieder mit dem Strategy-Pattern den Methode definieren die beim sterben ausgeführt weden soll (z.B Loot verteilen)
- `HealthSystem` hinzugefügt, verrechnet den Schaden und kümmert sich um den Entitäts-Tot
- Programmiermethoden/PM-Dungeon#246
=> [GAME] add HealthComponent and HealthSystem

game/src/level/elements/ILevel.java, game/src/level/elements/ITileable.java, game/test/level/TileLevelTest.java
#312 
getRandomTile war möglich eine Endlosschleife zu sein.
Gründe für die Schleife:
- ElementTyp nicht vorhanden 
- Random gibt nur Felder zurück, welche nicht vom Typ sind.
Zum Lösen wurde die Suche nach einem Tile mit einem bestimmten Elementtyp von ITileable nach ILevel bewegt.
Dann wurde die speziellen Listen benutzt, um das Tile zu suchen. Außerdem wurde eine Kontrolle eingeführt, ob es überhaupt ein Tile des Types gibt.
=> [GAME] fix getRandomTile mögliche Endlosschleife

game/src/ecs/components/skill/Skill.java, game/test/ecs/components/SkillTest.java
fixes #221 
- Cool Down in Skill implementiert
- Cool Down wird im ctor in Sekunden angegeben und nach Frames umgerechnet
- ´coolDownInFrames´ ist die Anzahl der Frames, die der Cool Down hat
- ´currentCoolDownInFrames´ ist die verbleibende Anzahl an Frames 
- [wie von @cagix angemerkt](https://github.com/Programmiermethoden/Dungeon/issues/221#issuecomment-1437329283): jeder Skill gehört zu einer Entität und daher wird der Cool Down im Skill gespeichert
- Tests angepasst
- YAGNI unnötige Methoden weggeworfen (wie im Meeting besprochen)
Fehlend:
=> [GAME] add Skill Cool Down

game/src/level/LevelAPI.java, game/src/starter/Game.java, game/test/level/TileLevelAPITest.java
fixes #492 
- `LevelAPI` um Parametisierte `loadLevel` Methoden erweitert
- `Game` lädt in der default Konfiguration nun immer kleine Level (ist besser zum testen)
=> [GAME] add better level size generation options

.github/CODEOWNERS
fixes #480 
- Hinzufügen von Code-Owners
- Cagix ist global owner
- malte ist owner der `dsl`
- andre und @Programmiermethoden/codrs sind owner des `game`
- ander und malte sind owner des `dsl-connector`
- Anmerkung: Als global owner ist cagix **nicht** owner von `game`, `dsl` und `dsl-connector`
- enable: Require review from Code Owners
- disable: Require approvals
=> [REPO] add Codeowners

game/src/ecs/entities/Hero.java
fixes #531 
- SkillComponent war in der Hero-Klasse, wurde aber noch nicht genutzt. Um es den Studis leichter zu machen, wurde es entfernt.
=> [GAME] SkillComponent aus Hero-Klasse entfernt

game/src/ecs/tools/interaction/InteractionTool.java, game/test/ecs/tools/interaction/InteractionToolTest.java
fixes #532
- Hero war noch in InteractionTool eingebunden, die Klasse `Hero` soll im Quickstart jedoch gelöscht werden
- `Hero.class` durch `Entity.class` an den entsprechenden Stellen ersetzt
- Tests für InteractionTool angepasst
=> [GAME] Hero aus InteractionTool entfernt

game/src/level/elements/ILevel.java, game/src/level/elements/ITileable.java, game/src/level/elements/TileLevel.java, game/src/level/elements/astar/TileConnection.java, game/src/level/elements/tile/TileFactory.java, game/test/level/TileLevelTest.java, game/test/level/elements/tile/TileFactoryTest.java
fixes #485
fixes #462
fixes #461
Verhalten des TileLevels ist beim entfernen bzw. hinzufügen von Tiles jetzt korrigiert somit werden die Verbindungen aufgeräumt beim Entfernen sowie beim Einfügen werden neue Verbindungen hergestellt. Der Index des Tiles wird nun auch richtig entfernt bzw hinzugefügt. 
restlichen Tests kommen noch
=> [Game] Tilelevel verhalten aufräumen

game/src/ecs/components/PositionComponent.java, game/src/ecs/entities/Hero.java, game/src/level/elements/ILevel.java, game/src/level/elements/tile/Tile.java, game/src/starter/Game.java
Bessere Konstruktionen für das `PositionComponent`
- add `new PositionComponent(Entity entity, float x, float y)`
- Dann braucht man keinen `Pont`erzeugen
- ` new PositionComponent(Entity entity)` prüft jetzt vorher, ob das Level existiert (ohne level hat es früher gecrasht) und setzt die Position entweder auf ein random Floor-Tile (wenn das level existiert) oder auf (0,0)
- `Hero` verwendet jetzt den einfachen ctor. 
@cagix ich trag dich mal für das Review ein, da du das Feature requested hast.
=> [GAME] Add Ctor with default position (PositonComponent)

game/src/ecs/components/HealthComponent.java, game/src/ecs/systems/HealthSystem.java, game/src/ecs/systems/VelocitySystem.java, game/src/graphic/Animation.java, game/test/ecs/components/HealthComponentTest.java, game/test/ecs/systems/HealthSystemTest.java
fixes #246 
Fixt das sofortige löschen des gestorbenen Entities, bevor die Death-Animation abgespielt werden konnte.
=> [GAME] Fix: wait for DeathAnimation onDeath

game/src/api/utils/DelayedSet.java, game/src/starter/Game.java, game/test/api/utils/DelayedSetTest.java, game/test/ecs/EntityTest.java, game/test/ecs/components/DropLootTest.java, game/test/ecs/entities/ChestTest.java, game/test/ecs/items/ItemDataTest.java, game/test/ecs/systems/AISystemTest.java, game/test/ecs/systems/CollisionSystemTest.java, game/test/ecs/systems/DrawSystemTest.java, game/test/ecs/systems/HealthSystemTest.java, game/test/ecs/systems/SkillSystemTest.java, game/test/ecs/systems/VelocitySystemTest.java, game/test/ecs/systems/XPSystemTest.java, game/test/ecs/tools/interaction/InteractionToolTest.java, game/test/graphic/DungeonCameraTest.java, game/test/starter/GameTest.java
fixes #635 
- hinzufügen von `DelayedSet` als Hilfsklasse, um die verschiedenen Sets `current`, `toAdd` und `toRemove` zu gruppieren und das handeln dieser zu vereinheitlichen. 
- Einbauen von `DelayedSet` in `Game` um die Entitäten des ECS zu verwalten
- Anpassen der Test-Fälle 
---
Ich habe zuerst mit dem Gedanken gespielt, `DelayedSet` von `Set` abzuleiten (wäre den Namen auch gerechter).
Ich habe mich dagegen entschieden, da wir sonst die ganzen `Set` Funktionalitäten selbst implementieren müssten.
Hier mal der Ausschnitt: 
In der Regel würden wir die Funktionen nur auf `current` anwenden und nicht auf die "Hilfe-Sets". 
Das müssten wir dann aber wieder Umfangreich dokumentieren und testen und und und...
Ich sehe dabei auch keinen Gewinn für unsere Sache und würde (für den seltenen …
=> [GAME] add DelayedSet

game/test/level/TileLevelTest.java
fixes #571 
Das Problem war, dass der Test aus einer Zeit mit nur einem `ExitTile` kommt und nicht an das neue System angepasst wurde.
Dadurch konnte die Situation entstehen, dass mehrere Ausgänge existieren und der berechneten Pfad nicht zu den erwarteten Ausgang geführt hat. Bin tatsächlich etwas irritiert, dass der Test nicht häufiger fehlgeschlagen ist. 
Ich habe die Erstellung des Test-Level entsprechend angepasst und der Test sollte nun zuverlässig laufen.
=> [GAME] fix bug in TileLevelTest.test_findPath_moreThanOnePathPossible

build.gradle
Fixes #430
spotbugs ist die aktuellste Version 5.0.14
spotless vorher 6.5.+ wurde auf 6.5.2 festgelegt, da neuere Versionen neue regeln festlegen 6.18.0(aktuellste Version) wird viele Dateien anpassen, da sich z.b. Import regeln geändert haben.
junit war 4.+ aktuellste Version 4.13.2 ist kompatibel und eingestellt
powermock ist stale und letzte stabile Version ist 2.0.9 dies ist mit unserem Code kompatibel
Getestet wurde es wie folgt auf einem Windows 10 System.
Check ausgeführt
Check ausgeführt nach Löschen des Caches
Check ausgeführt nach Löschen des Caches und Neustart
=> [Game] Gradle Plugins und libs stärker beschränken

game/src/contrib/entities/EntityFactory.java, game/src/core/components/PlayerComponent.java, game/src/core/systems/PlayerSystem.java, game/test/core/components/PlayerComponentTest.java
fixes #658 
- PlayerComponent speichert nun die Tastaturbelegung und die Funktionalität nach Druck der Taste in einer Hashmap
- zum Hinzufügen einer neuen Funktionalität (z.B. neuer Skill), existiert die Methode `registerFunction`, zum Entfernen `removeFunction`
- Hero bekommt in "EntityFactory` durch nutzen der neuen Methoden seine Bewegungsfähigkeit und seine Skills.
- Tests angepasst
=> [GAME] Refactor PlayerComponent

doc/dsl/interpretation_laufzeit.md, doc/dsl/typebuilding.md, dsl/src/interpreter/DSLInterpreter.java, dsl/src/runtime/AggregateValue.java, dsl/src/runtime/GameEnvironment.java, dsl/src/runtime/Value.java, dsl/src/semanticanalysis/SemanticAnalyzer.java, dsl/src/semanticanalysis/types/AdaptedType.java, dsl/src/semanticanalysis/types/AggregateTypeAdapter.java, dsl/src/semanticanalysis/types/DSLTypeAdapter.java, dsl/src/semanticanalysis/types/TypeBuilder.java, dsl/src/semanticanalysis/types/TypeInstantiator.java, dsl/test/interpreter/CustomQuestConfig.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/interpreter/TestEnvironment.java, dsl/test/interpreter/mockecs/ExternalTypeBuilder.java, dsl/test/interpreter/mockecs/ExternalTypeBuilderMultiParam.java, dsl/test/interpreter/mockecs/OtherExternalType.java, dsl/test/interpreter/mockecs/OtherExternalTypeBuilderMultiParam.java, dsl/test/runtime/TestGameEnvironment.java, dsl/test/semanticanalysis/types/RecordBuilder.java, dsl/test/semanticanalysis/types/TestTypeBuilder.java
=> [DSL] Instanziierung für AggregateTypeAdapter

.github/CODEOWNERS
In #657 haben wir das Projekt "dsl-connector" in "dungeon" umbenannt.
Diese Namensänderung wurde nicht in die Codeowner Konfiguration aufgenommen.
Dieser PR macht das.
=> [Org]  rename project "dsl-connector" to "dungeon" in Codeowner configuration

dsl/src/runtime/GameEnvironment.java, dsl/src/runtime/IEvironment.java, dsl/src/semanticanalysis/types/TypeBinder.java, dsl/test/helpers/Helpers.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/interpreter/TestEnvironment.java, dsl/test/semanticanalysis/TestSymbolTableParser.java, dsl/test/semanticanalysis/TestTypeBinder.java
Aktuell muss für das Laden von Datentypen oder Funktionsdefinitionen in ein `IEnvironment` immer folgende umständliche Konstruktion verwendet werden:
```java
var types = new IType[] {type1, type2};
env.loadTypes(List.of(types));
```
Das händische Laden von Datentypen ist insbesondere für Tests (z.B. in `TestDSLInterpreter`, `TestTypeBinder`) wichtig. Um den Code etwas lesbarer und handlicher zu gestalten, fügt dieser PR die Möglichkeit hinzu, `varargs` für die `loadTypes` und `loadFunctions`-Methoden von `IEnvironment` zu verwenden:
```java
env.loadTypes(type1, type2);
```
=> [DSL] Varargs in `load`-Methoden von `IEnvironment` ermöglichen

doc/related_work/conferences.md, doc/related_work/readme.md
fixes #431
Dieser PR fügt eine Übersichtstabelle der in #431 genannten Konferenzen hinzu.
Unter dem "Bereich"-Abschnitt habe ich versucht, eine grobe Übersicht über die Themen zu geben, die auf der Konferenz behandelt werden. Diese können von Jahr zu Jahr variieren und sollten daher als grobe Kategorisierung verstanden werden.
Um den Zyklus zu bestimmen, habe ich mich auf die Informationen auf der Webseite verlassen und kurz recherchiert, ob es in den vergangenen Jahren ebenfalls Konferenzen gab, um den Zyklus festzulegen.
=> [Doc/Publication] add overview table of conferences  

game/src/core/Game.java
fix #680 
sollte eigentlich in #688 behoben worden sein, scheint aber beim rebasen verloren gegangen zu sein.
=> [GAME] fix bug where LevelManger was initialized two times

game/src/core/System.java, game/test/core/SystemTest.java
bzgl #727
- fügt in `System` die `protected Consumer <Entity>`
- `onEntityRemove` -> letzter Aufruf in `System#removeEntity`
- `onEntityAdd` -> letzter Aufruf in `System#addEntity`
- `onEntityShow` -> letzter Aufruf in `System#showEntity` (`onAddEntity`/ `onRemoveEntity` wird daher (wenn das Event passiert, vor `onEntityShow` aufgerufen) 
- passe Tests an
@cagix Ich habe mich aus dem Bauchgefühl heraus für `protected` Consumer entscheiden und keine getter/setter verwendet. 
Für mich sind die Consumer etwas, was in den abgeleiteten Systemen im Konstruktor gesetzt wird, nach außen sind die irrelevant. 
Getter/Setter haben für mich immer einen leichten API-Geschmack, also Konfiguration von/nach "außen". 
Hast du eine andere Präferenz?
@AHeinisch kannst du damit #727 umsetzten?
=> [GAME] add `onEntityShow`, `onEntityAdd` and `onEntityRemove` Consumer in `System`

game/src/core/Game.java, game/src/core/utils/components/MissingComponentException.java
fixes #556
- die Methode `Game.onLevelLoad` wirft durch Aufruf von `Game.placeOnLevelStart` eine MissingComponentException wenn der Held keine PositionComponent hat
- Try-Catch-Block innerhalb von `Game.onLevelLoad`, der `Game.placeOnLevelStart` aufruft und bei Auftreten einer MissingComponentException dies loggt
- gleiches Verhalten bei `Game.onFrame`, welches durch den Aufruf von `Game.loadNextLevelIfEntityIsOnEndTile` bei fehlendem PositionComponent des Helden zu einer MissingComponentException führt
=> [Game] Hero ohne PositionComponent führt nicht mehr zu MissingComponentException

game/src/core/Entity.java
In #652 aufgekommen
- Wenn eine Entität einen expliziten Namen hat, wird in `toString` noch "_${id}" angehangen. 
- Wenn die Entität keinen expliziten  Name hat, dann wird nur `"_${id}`angehangen
Warum wird der explizite Name nicht im Konstruktor um die id ergänzt?
Also `this.name=name+"_"+id`. 
Ich könnte mir vorstellen, dass die `toString` Methoden genutzt wird, um in irgendwelchen Texten den Namen auszugeben.
z.B
`"Hallo "+hero+" meine Name ist "+cagix";`
=> [GAME] Entity#toString will return $name_$id if the entity has a name

dsl/test/helpers/Helpers.java, dsl/test/interpreter/TestDSLInterpreter.java
Das folgende Codesnippet taucht häufig in den Tests für den `DSLInterpreter` auf:
``` java 
// Laden von Datentypen
TypeBuilder tb = new TypeBuilder();
var testCompType = tb.createTypeFromClass(new Scope(), TestComponent.class);
var otherCompType = tb.createTypeFromClass(new Scope(), OtherComponent.class);
var env = new GameEnvironment();
env.loadTypes(testCompType, otherCompType);
// Durchführen von Parsing und  semantischer Analyse 
SemanticAnalyzer symbolTableParser = new SemanticAnalyzer();
symbolTableParser.setup(env);
var ast = Helpers.getASTFromString(program);
symbolTableParser.walk(ast);
// Erzeugung der QuestConfig
DSLInterpreter interpreter = new DSLInterpreter();
interpreter.initializeRuntime(env);
var questConfig = interpreter.generateQuestConfig(ast);
```
Ein vergleichbares …
=> [DSL] Refactoring von DSLInterpreter tests

game/src/contrib/systems/CollisionSystem.java, game/src/core/Entity.java, game/test/core/EntityTest.java
fixes #754 
- Einfache implementation des Comparable interfaces
- Drei Tests für Kontrolle der Funktionalität
- EntityTest nebeneffekt entfernt (setup räumt auf, aber nicht richtig, dass Delayedset wurde nicht geupdated)
- CollisionSystem isIDsmaller umgebaut, nutzt nun compareTo
=> [Game] Entity Comparable<Entity> implemented

game/src/core/components/DrawComponent.java
In diesem Pull-Request wurde das `DrawComponent` refactored.
- DrawComponent wird aus Entität entfernt, wenn beim laden der Animationen eine FileNotFound-Exception auftritt
- try-catch im Konstruktor verbessert
=> [GAME] remove DrawComponent from the entity if animations can't be loaded and refactor the DrawComponent (JavaDoc, Clean Code)

game/src/core/Entity.java
fixes #778
- Fügt `Entity#componentValueStream` hinzu, um einen Stream aller Komponenteninstanzen abzurufen, die in der Entität gespeichert sind.
- Fügt `Entity#componentKeyStream` hinzu, um einen Stream von `Class<? extends Component>` abzurufen, wobei jede Klasse Teil des Streams ist, wenn eine Instanz in der Entität gespeichert ist.
=> [GAME] add  component stream getter to `Entity`

game/src/contrib/utils/components/skill/DamageProjectile.java, game/src/contrib/utils/components/skill/FireballSkill.java
fixes #716 
In `DamageProjectile#accept(Entity entity)` wird nun der `cause` gesetzt. 
Dazu wurde das Attribut `DamageProjectile#projectileDamage` mit den Attributen `int damageAmount` und `DamageType damageType` ersetzt und die Zeile `  ((HealthComponent) hc).receiveHit(projectileDamage);` zu `  ((HealthComponent) hc).receiveHit(new Damage(damageAmount,danageType,entity);` geändert.
Außerdem:
- Parameter zu Konstanten in `FireballSkill` umgewandelt
=> [GAME] Cause-Entity für Damage-Skills hinzugefügt

.github/CODEOWNERS
Dieser PR macht das @Programmiermethoden/dungeon -Team Codeowner der `buiild.gradle` und `settings.gradle` im root.
=> [GitHub] make Dungeon-Team owner of `build.gradle` and `settings.gradle`

game/src/contrib/components/XPComponent.java, game/src/contrib/systems/XPSystem.java, game/test/contrib/components/XPComponentTest.java, game/test/contrib/systems/XPSystemTest.java
In diesem Pull-Request wurde das `XPComponent` refactored.
Außerdem:
Es gab einen konzeptionellen Fehler im Callback für ein Level-Up. Früher war es ein `LongConsumer`, was einfach ein `Consumer<Long>` ist. Beim Aufruf wurde dann das aktuelle Character-Level übergeben.
Die Callback-Funktion wusste dann zwar, welches Level die Entität erreicht hatte, kannte aber nicht die Entität selbst. Das Problem wurde behoben, indem jetzt (analog zu allen anderen Callbacks) ein `Consumer<Entity>` verwendet wird.
Dann kann die Callback-Methode über die Entität die gewünschten Komponenten (z. B. das XPComponent) und gewünschte Werte (z. B. das aktuelle …
=> [GAME] refactor XPComponent use Consumer<Entity> for level-up callback ( and JavaDoc, Clean Code)

game/src/contrib/components/StatsComponent.java, game/src/contrib/systems/HealthSystem.java, game/test/contrib/systems/HealthSystemTest.java
In diesem Pull-Request wurde das `StatsComponent` refactored.
Außerdem:
Vereinfachen des Zugriffs auf das `DamageModifier` Objekt. 
Anstelle erst das Objekt aus dem Component abzufragen und dann die Funktionen von `DamageModifier` aufzurufen, kann man diese nun direkt im Component aufrufen. Das vereinfach den Zugriff. 
Die Tests wurden entsprechend angepasst.
=> [GAME] refactor StatsComponent better api ( and JavaDoc, Clean Code)

game/src/contrib/utils/components/ai/AITools.java, game/src/contrib/utils/components/ai/fight/RangeAI.java, game/src/contrib/utils/components/ai/idle/StaticRadiusWalk.java, game/src/core/Game.java, game/src/core/level/elements/IPathable.java, game/src/core/utils/Point.java, game/test/core/level/TileLevelTest.java
fixes #786 
`IPathable#findPath` überprüft nun, ob die Start- und End- Tile für eine Entity accessible sind. Falls nicht, wird eine IllegalArgumentException geworfen.
Außerdem:
- Testfälle geschrieben für:
- startTile ist nicht accessible
- endTile ist nicht accessible
- startTile und endTile sind nicht accessible
- JavaDoc für `AITools` ergänzt
=> [GAME] add throw of `IllegalArgumentException` to `IPathable#findPath` if `start` or `end` are non-accessible

game/src/core/systems/LevelSystem.java
fixes #857
Das `HudSystem` hat beim Aufrufen (Beispielweise bei der Pause-Funktion) alle anderen Systeme gestoppt. Dadurch wurde das `LevelSystem` auch gestoppt und wurde bei offenen "Menüs" nicht mehr gezeichnet. Dies wurde durch das Überschreiben der Funktion `LevelSystem#stop`, welche das pausieren des `LevelSystem`s nun verhindert, gelöst.
=> [GAME] HUD pausiert `LevelSystem` nicht mehr

dsl/src/semanticanalysis/types/TypeBuilder.java, dsl/src/semanticanalysis/types/TypeInstantiator.java, dsl/src/semanticanalysis/types/callbackadapter/CallbackAdapter.java, dsl/src/semanticanalysis/types/callbackadapter/CallbackAdapterBuilder.java, dsl/src/semanticanalysis/types/callbackadapter/ConsumerFunctionTypeBuilder.java, dsl/src/semanticanalysis/types/callbackadapter/FunctionFunctionTypeBuilder.java, dsl/src/semanticanalysis/types/callbackadapter/IFunctionTypeBuilder.java
Behebt den Benennungsfehler des `CallbackAdapter`-packages.
=> [DSL] Rename package CallbackAdapter to callbackadapter

dsl/src/antlr/DungeonDSL.g4, dsl/src/interpreter/DSLInterpreter.java, dsl/src/parser/DungeonASTConverter.java, dsl/src/parser/ast/AssignmentNode.java, dsl/src/parser/ast/AstVisitor.java, dsl/src/parser/ast/ComparisonNode.java, dsl/src/parser/ast/EqualityNode.java, dsl/src/parser/ast/FactorNode.java, dsl/src/parser/ast/LogicAndNode.java, dsl/src/parser/ast/LogicOrNode.java, dsl/src/parser/ast/MemberAccessNode.java, dsl/src/parser/ast/Node.java, dsl/src/parser/ast/TermNode.java, dsl/src/parser/ast/UnaryNode.java, dsl/src/semanticanalysis/FunctionCallResolver.java, dsl/src/semanticanalysis/SemanticAnalyzer.java, dsl/src/semanticanalysis/VariableBinder.java, dsl/src/semanticanalysis/types/TypeBinder.java, dsl/test/parser/TestDungeonASTConverter.java
Fixes #780 
Modifiziert die Grammatik zur Behandlung von Ausdrücken.
Fügt Regeln für arithmetische Ausdrücke, logische Ausdrücke, Vergleichsoperationen, Zuweisungen und Member-Zugriffe hinzu.
Implementiert die Konvertierung in AST-Knoten für die neuen Regeln.
Ändert das `ASTVisitor`-Interface so, dass eine `UnsupportedOperationException` geworfen wird, falls eine Implementierung des Interfaces eine bestimmte Methode nicht implementiert. Dass dies in der Vergangenheit nicht nötig war, hat schon einige Male zu langen Fehlersuchen geführt.
=> [DSL] Expression-Grammatik

dungeon/test/manual/dslFileReader/DslFileReaderTest.java, dungeon/test/manual/quizquestion/QuizQuestionUITest.java, dungeon/test/manual/quizquestion/WizardQuizTest.java, game/src/core/Game.java, game/src/core/utils/logging/LoggerConfig.java, game/src/starter/Main.java
Damit die Konsole nicht mehr mit Log-Nachrichten geflutet wird, habe ich den Console-Handler aus dem Logger entfernt.
Zeitgleich wurde das Initialisieren des Base-Loggers Teil der Pre-Run-Konfiguration (muss daher in der `main` aufgerufen werden).
Damit die Konfiguration direkt zu Beginn gesetzt wird, sollte dies der erste Aufruf sein.
Log-Nachrichten, die vor `initBaseLogger()` erstellt werden, werden nämlich weiterhin auf der Konsole ausgegeben (der Console-Handler wurde ja schließlich nicht entfernt).
Um bei der aktuellen Pre-Run-API zu bleiben, wurde eine Hilfsmethode zum Initialisieren in `Game` angelegt.
=> [GAME] Remove console log-handler, make init-logger part of the pre-run configuration.

game/src/core/System.java, game/test/contrib/entities/ChestTest.java, game/test/contrib/entities/MonsterTest.java, game/test/contrib/systems/AISystemTest.java, game/test/contrib/systems/CollisionSystemTest.java, game/test/contrib/systems/HealthSystemTest.java, game/test/contrib/systems/XPSystemTest.java, game/test/contrib/utils/components/interaction/ControlPointReachableTest.java, game/test/core/level/TileLevelAPITest.java, game/test/core/systems/CameraSystemTest.java, game/test/core/systems/VelocitySystemTest.java
fixes  #886
- entfernt das impliziere Registrieren der Systeme bei `Game` 
- Hinweis auf das registrieren in die javadoc aufgenommen
- Tests entsprechend angepasst
- Immer wen ein System erzeugt wurde, habe ich ein `Game.addSystem` hinzugefügt
- Cleanup Methode hinzugefügt, wenn diese Gefehlt hat.
=> [GAME] remove impliziertes registrieren von `System`s beim `Game` 

dungeon/test/manual/quizquestion/WizardQuizTest.java, game/src/contrib/components/InteractionComponent.java, game/src/contrib/entities/EntityFactory.java, game/src/contrib/entities/WorldItemBuilder.java, game/src/contrib/utils/components/interaction/DropItemsInteraction.java, game/src/contrib/utils/components/interaction/InteractionTool.java, game/src/contrib/utils/components/item/ItemData.java, game/src/core/components/PlayerComponent.java, game/src/core/utils/Constants.java, game/src/core/utils/components/draw/Animation.java, game/test/contrib/components/InteractionComponentTest.java, game/test/contrib/utils/components/interaction/ControlPointReachableTest.java, game/test/contrib/utils/components/interaction/InteractionToolTest.java
(fix #646)
Replaces the `CollisionComponent `on item entities with `InteractionComponent`. Also, it makes sure that only one item is picked up per interaction.
=> [Game] Replace collision for item pickup with interaction

game/src/core/level/generator/perlinNoise/PerlinNoiseGenerator.java, game/src/core/level/generator/randomwalk/RandomWalkGenerator.java
Erstellen eines Levels generiert beim Fehlen eines Ausgangs einen dafür. Dadurch benötigen die Generatoren keinen extra Exit erstellen. Außerdem kann es an anderer Stelle hilfreich sein, wenn nicht der Generator selbst den Ausgang bestimmt anhand eines zufälligen Tiles.
fixes #901
=> [Game] level generater will no longer place exit

game/src/contrib/components/InventoryComponent.java, game/test/contrib/components/InventoryComponentTest.java
Logik für #491
Erlaubt das transferieren von Items aus einem inventar in das andere.
Damit das Issue resolved ist, müsste die Funktionalität in #234 noch hinzugefügt werden.
=> [GAME] add transfer function to inventory component

game/src/contrib/systems/HealthbarSystem.java
fixes #899 
irgendwie ist die letzte konvertierung verloren gegangen um die einzelnen schritte vielleicht besser zu verstehen comments hinzugefügt
=> [Game] fix:  Healthbars misalign on window rescale due to missing window to stage coordinate conversion

dsl/src/interpreter/DSLEntryPointFinder.java, dsl/src/parser/DungeonASTConverter.java, dsl/test/interpreter/TetsDSLEntryPointFinder.java, dsl/test_resources/config1.dng, dsl/test_resources/config2.dng, dungeon/src/dslToGame/DSLEntryPoint.java, dungeon/src/dslToGame/ParsedFile.java, dungeon/src/dslToGame/QuestConfig.java
Fixes #869 
Implementiert die Suche nach Einstiegspunkten (QuestConfigs) in `DSLEntryPointFinder` (als `ASTVisitor`-Implementierung).
Sammelt die nötigen Informationen (Dateipfad, Anzeige-Name, AST-Knoten) einer QuestConfig in der `DSLEntryPoint` Recordklasse.
Die Logik wird dabei bewusst vom `DSLInterpreter` abgekapselt, da für die Suche nach QuestConfig-Definitionen möglichst wenig Overhead entstehen soll, daher reicht es aus, hier nur auf der AST-Ebene zu bleiben. Der für die Datei erstellte AST wird in einer `ParsedFile`-Instanz zusammen mit dem Dateipfad gespeichert. 
Beispiel:
```
quest_config my_config {
name: "Tolle QuestConfig",
...
}
```
Im obigen Beispiel ist der Config-Name "my_config" (also der Name der QuestConfig Objektdefinition). Der Anzeigename ist "Tolle QuestConfig" …
=> [DSL] Implementieren von `getConfigs`

game/src/contrib/utils/components/ai/transition/ProtectOnAttack.java
closes #751
In diesem PR wird die Nutzung eines peek durch einen übersichtlicheren Filterablauf ersetzt
=> [GAME] ProtectOnAttack `peek` vs `filter` überarbeitet

game/src/contrib/entities/EntityFactory.java, game/src/contrib/utils/components/skill/FireballSkill.java, game/src/core/level/Tile.java, game/src/core/systems/VelocitySystem.java, game/src/core/utils/Constants.java, game/test/core/systems/VelocitySystemTest.java
(closes #935)
- Hinzufügen von Reibungswiderstand
- Berücksichtigen der Delta-Time für Bewegung (→ Bewegung wird bei Einbruch der Framerate mit gleicher Geschwindigkeit im nächsten Frame fortgesetzt)
=> [Game] Verbesserung der Bewegung im Dungeon

doc/jar_converter/readme.md, jarConverter.sh
fixes #881
- Fügt Skript hinzu
- Fügt Anleitung zur Verwendung hinzu
- Anders als in #881 beschrieben, verarbeitet das Skript nicht automatisch alle Dateien im Verzeichnis. Stattdessen werden Befehlszeilenargumente (CLA) erwartet. Dies mag die Verwendung etwas umständlicher machen, aber ich habe Bedenken, dass sonst jemand das Skript auf dem Desktop ausführt und das gesamte System in eine JAR-Datei kopiert.
Falls sich wer fragt, warum der `scripts` Ordner am Ende nicht gelöscht wird:
1. Dann kann man relativ einfach gucken ob wirklich alles enthalten ist was man wollte
2. Falls es schon ein `scripts` Ordner gibt bevor das Skript startet, will ich nichts vom User löschen. Lieber lasse ich den User selber aufräumen als ausversehen irgendwelche Daten zu löschen
=> [DUNGEON] add `jarConverter.sh` to create Jar Files 

game/src/core/Game.java, game/src/core/components/PositionComponent.java, game/src/core/systems/PositionSystem.java, game/src/core/utils/Point.java, game/test/core/systems/PositionSystemTest.java
fixes #959
- Fügt ein konstante `PositionComponent#ILLEGAL_POSITION` ein, welche gesetzt wird, wenn kein level geladen ist
- Fügt das `PositionSystem` ein, welches auf Entitäten mit den `PositionComponent` agiert und deren Illegal-Position auf eine zufällige accessible-position ändert (wenn das level geladen ist).
- Fügt eine gescheite `Point#equals(Point other)` ein
- Tests
=> [GAME] add `PositionSystem`

dungeon/test/manual/dslFileReader/DslFileReaderTest.java, dungeon/test/manual/quizquestion/CallbackTest.java, dungeon/test/manual/taskgeneration/TaskGenerationTest.java, game/src/core/Game.java, game/src/core/utils/EntitySystemMapper.java, game/src/starter/Main.java
fixes #900 
- Fügt in der Klasse `Game` die `Map<ILevel, Set<EntityStorageMapper>>` hinzu. 
- Die Map stellt die Verbindung zwischen den Leveln und den Entitäten her.
- Der aktive Storage ist das `Set<EntityStorageMapper>` des aktiven Levels.
- Im `Game#onLevelLoad` werden jetzt alle Systeme aus dem "alten" `Set<EntityStorageMapper>` entfernt. Dadurch werden alle `System#onEntityRemove`-Methoden ausgelöst, ohne die Entitäten tatsächlich zu löschen (denn diese werden beim Neuladen des Levels noch benötigt).
- Für das neue Level werden die Systeme anschließend wieder hinzugefügt, was jeweils jedes `System#onEntityAdd` auslöst.
- `userOnLevelLoad` ist nun ein `Consumer<Boolean>`. Der Boolean gibt an, ob das Level schon einmal geladen wurde. Dadurch können Monster und Schatzkisten nur beim …
=> [GAME] use map `Set<EntiteSystemMapper>` with `ILevel` to create a link between the level and the entities

game/src/core/components/DrawComponent.java, game/src/core/utils/components/draw/Animation.java
Fixes #932
Dieser PR fügt dem `DrawComponent` eine Fallunterscheidung hinzu, die prüft, ob das Programm in der IDE oder in einer JAR-Datei ausgeführt wird. Abhängig davon werden unterschiedliche Logiken zum Einlesen der Animationsdateien angewendet.
Für die Ausführung in der IDE hat sich nicht viel geändert. Wir lesen nach wie vor alle Verzeichnisse im übergebenen Pfad ein und ordnen sie der Funktion `Animation#of` zu.
Wenn das Programm in einer JAR-Datei ausgeführt wird, sind andere Schritte erforderlich. Zunächst lesen wir alle Dateien und Verzeichnisse in der gesamten JAR-Datei ein (Verwendung von `Enumeration<JarEntry> entries = jar.entries();`). Da wir innerhalb einer JAR-Datei nicht mit dem Datentyp `File` arbeiten können, erfolgt die Verarbeitung auf der Ebene Strings. Zunächst …
=> [GAME] add unterscheidung von Dateiverarbeitung in IDE und JAR im `DrawComponent` 

game/src/core/components/DrawComponent.java, game/test/core/components/DrawComponentTest.java
Unter Windows können die assets nicht geladen werden (seit der Änderung #953)
Dieser PR behebt dieses verhalten, scheinbar muss intern vollständig mit `/` als Fileseprator gearbeitet werden.
Danke @Lena241 für die schnelle Unterstützung. Bitte nochmal testen
Frage: Wie konnte das in den master gelangen? Vermutlich spielen da mehrere PRs eine Rolle, welche alleine zwar Lauffähig waren aber kombiniert nicht. Vielleicht müssen wir in GitHub einen rebase Forcen. 
Edit: Vermutlich ist es durch gekommen, weil die Tests nicht verändert wurden und somit nur Junit auf Linux lief
=> [GAME] fix DrawComponent for Windows

game/src/contrib/crafting/Crafting.java
fixes #967 
Unter Windows war der kram eh schon in einer jar lauffähig (scheinbar war der in #967 befürchtete Fehler nicht aufgetreten)
Under Mac (und ich denke auch Unix) war das Crafting nicht in der Jar lauffähig, da dass Pfad-Replacement per Regex nur den windows typischen Pfad ersetzt hat.
Ich habe das nun angepasst
=> [GAME] fix Crafting in jar vor mac/unix

dsl/src/antlr/DungeonDSL.g4, dsl/src/interpreter/DSLInterpreter.java, dsl/src/parser/DungeonASTConverter.java, dsl/src/parser/ast/AstVisitor.java, dsl/src/parser/ast/Node.java, dsl/src/parser/ast/VarDeclNode.java, dsl/src/runtime/EncapsulatedObject.java, dsl/src/runtime/FunctionValue.java, dsl/src/runtime/IMemorySpace.java, dsl/src/runtime/MemorySpace.java, dsl/src/semanticanalysis/SemanticAnalyzer.java, dsl/src/semanticanalysis/VariableBinder.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/semanticanalysis/TestSemanticAnalyzer.java
Implementiert Variablen-Definition.
Erweitert Grammatik für Variablendeklaration.
Implementiert AST-Konvertierung für Variablendeklaration.
Implementiert semantische Analyse für Variablendeklaration (wobei allerdings aktuell nur die `identifier : datentyp` Variante unterstützt wird, die `identifier = expression` Variante erfordert Typechecking).
Fügt Sonderfall-Behandlung für if-else-Statement mit nur einem Statement im Rumpf hinzu, um evtl. darin erfolgte Variablendeklarationen nicht in den umliegenden Scope zu lassen (TODO: das in der Interpretation berücksichtigen oder festlegen, dass im Rumpf von if-else-Statements immer ein Block verwendet werden muss).
Fügt Tests hinzu.
TODO:
=> [DSL] Variablendeklaration implementieren

game/src/contrib/components/AIComponent.java, game/src/contrib/entities/AIFactory.java, game/src/contrib/utils/components/ai/idle/PatrolWalk.java
fixes #983
Patrouille ist kein englisches Wort. PatrouilleWalk wurde dementsprechend in PatrolWalk umbenannt.
=> [GAME] renamed PatrouilleWalk to PatrolWalk

game/src/core/level/utils/Coordinate.java, game/src/core/level/utils/LevelUtils.java, game/src/core/utils/Point.java, game/test/core/level/utils/LevelUtilsTest.java
fixes #572 
Umbau von schleife, wo nur direkt auf die untere linke ecke als Kachel Erkennung genutzt wird, so das alle ecken benutzt werden und falls der Radius gerade so in der Kachel endet, ohne eine Ecke zu berühren. (Bild folgt für Darstellung mit allen Fällen)
=> [Game] core.level.utils.LevelUtils#tilesInRange findet Kacheln mehrfach

game/src/core/level/generator/graphBased/RoombasedLevelGenerator.java
fixes #982 
- Die Raumgröße wird jetzt beim generieren davon abhängig gemacht, wie viele Entitäten initial darin enthalten sein sollen (dabei zählen nur Entitäten mit einen PositionComponent und DrawComponent (also quasi nur Sachen die man auch sieht) 
- Konstanten sind nach etwas hin und her testen festgelegt worden. Für meinen Geschmack war das ganz gut.
=> [GAME] make room size base on entities in room

dungeon/src/Starter.java, dungeon/src/task/Task.java, game/src/contrib/configuration/KeyboardConfig.java
fixes #616 
- fügt dem Dungeon-Starter einen Knopf zum Anzeigen des Questlogs hinzu (Default `M`)
- Beim aufrufen werden die Task-Beschreibungen aller aktiven Tasks angezeigt
- Dafür wird in `Task` eine zentrale statische Liste geführt bei dem jedes `Task` Objekt beim erzeugen hinzugefügt wird (vielleicht wandert das später noch wo anders hin (Petri Netz?)
- Hübsch ist das noch nicht, aber das Problem ist in #907 hinterlegt
=> [DUNGEON] add Questlog

dsl/src/interpreter/DSLInterpreter.java, dsl/src/runtime/AggregateValue.java, dsl/src/runtime/EncapsulatedObject.java, dsl/src/runtime/GameEnvironment.java, dsl/src/runtime/ListValue.java, dsl/src/runtime/SetValue.java, dsl/src/runtime/Value.java, dsl/src/runtime/nativefunctions/ExtensionMethod.java, dsl/src/runtime/nativefunctions/NativeMethod.java, dsl/src/semanticanalysis/IInstanceCallable.java, dsl/src/semanticanalysis/SemanticAnalyzer.java, dsl/src/semanticanalysis/types/DSLExtensionMethod.java, dsl/src/semanticanalysis/types/FunctionType.java, dsl/src/semanticanalysis/types/IDSLExtensionMethod.java, dsl/src/semanticanalysis/types/ListType.java, dsl/src/semanticanalysis/types/SetType.java, dsl/src/semanticanalysis/types/TypeBuilder.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/interpreter/mockecs/TestComponent2.java, dsl/test/semanticanalysis/types/TestTypeBuilder.java
Fixes #781 
Implementiert zwei Methoden-Arten (native Methoden und externe Methoden). Beide Methoden-Arten nutzen das Pattern, was bereits für #955 genutzt wurde. Sie werden also als innere statische Klasse mit einer statischen Instanz und `private`-Konstruktor erzeugt. Die statische Instanz wird zur Erzeugung der entsprechenden Symbole verwendet, welche die Methode in der Symboltabelle repräsentieren.
Native Methoden sind Methoden, die direkt mit den nativen Datentypen der DSL verbunden sind (bspw. die `add`-Methode eines Listen-Typen). Native Methoden implementieren `IInstanceCallable` und werden als `NativeMethod`-Symbol abgebildet und im entsprechenden Datentyp, in dem sie verfügbar sind, gebunden.
Externe Methoden sind Methoden, die Datentypen, welche per `@DSLType` Annotation …
=> [DSL] Methoden implementieren

.github/dependabot.yml
Dieser PR fügt eine minimale Dependabot-Konfiguration hinzu, die die verwendeten GitHub-Actions überwacht und bei neuen Versionen automatisch einen Update-PR vorschlägt. Die Konfiguration könnte in Zukunft erweitert werden, um auch Gradle-Abhängigkeiten automatisiert zu aktualisieren.
@AMatutat Bitte einmal freigeben.
=> Tool: add dependabot

dsl/src/interpreter/DSLInterpreter.java, dsl/src/parser/ast/AggregateValueDefinitionNode.java, dsl/src/parser/ast/BinaryNode.java, dsl/src/parser/ast/ConditionalStmtNodeIf.java, dsl/src/parser/ast/ConditionalStmtNodeIfElse.java, dsl/src/parser/ast/DotDefNode.java, dsl/src/parser/ast/EdgeRhsNode.java, dsl/src/parser/ast/EdgeStmtNode.java, dsl/src/parser/ast/FuncCallNode.java, dsl/src/parser/ast/FuncDefNode.java, dsl/src/parser/ast/ListDefinitionNode.java, dsl/src/parser/ast/ListTypeIdentifierNode.java, dsl/src/parser/ast/Node.java, dsl/src/parser/ast/ObjectDefNode.java, dsl/src/parser/ast/ParamDefNode.java, dsl/src/parser/ast/PropertyDefNode.java, dsl/src/parser/ast/PrototypeDefinitionNode.java, dsl/src/parser/ast/ReturnStmtNode.java, dsl/src/parser/ast/SetDefinitionNode.java, dsl/src/parser/ast/SetTypeIdentifierNode.java, dsl/src/parser/ast/StmtBlockNode.java, dsl/src/parser/ast/UnaryNode.java, dsl/src/runtime/nativefunctions/ExtensionMethod.java, dsl/src/runtime/nativefunctions/NativeMethod.java, dsl/src/semanticanalysis/SemanticAnalyzer.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/interpreter/mockecs/TestComponent2.java, dsl/test/semanticanalysis/TestSemanticAnalyzer.java
Fixes #1005 
Umbau der ursprünglich rekursiven Behandlung von `MemberAccess`-Knoten in iterative Version (in `SemanticAnalyzer` und `DSLInterpreter`).
Im `DSLInterpreter` wird ein neuer Instanz-`IMemorySpace`-Stack hinzugefügt, auf den der `MemorySpace` des `Values` gelegt wird, welcher als Instanz für den Methoden-Aufruf verwendet werden soll. In der `call`-Implementierung von `ExtensionMethod` und `NativeMethod` wird über diesen Stack der `$THIS$`-Value aufgelöst, der auf die entsprechende Instanz zeigt. Die Instanz kann nicht auf den regulären `memoryStack` des `DSLInterpreter`s gelegt werden, da die Parameter des Methodenaufrufs in dem umliegenden Scope des Methodenaufrufs aufgelöst werden müssen und nicht in dem Scope der Instanz, welche für den Methodenaufruf verwendet werden soll. …
=> [DSL] Bugfix: Auflösung von Parametern in Methodenaufrufen

game/src/contrib/utils/components/Debugger.java
fixes #1028 
Hotkey Fenster schließen (Escape) entfernt zusätzlich von Herunternehmen des Elements vom UI auch die Komponente. Daher hatte das Pausemenu nicht mitbekommen, dass dort eine Änderung war. Ich war mir sicher, alle Fälle durchprobiert zu haben. Öffnen und schließen über UI sowie über Hotkey
=> [Game] fix pause no longer opens after closing with hotkey

doc/related_work/analysis_framework.md
Fügt die Zusammenfassung für das Paper 'Ein Analyserahmen für die Gestaltung von deklarativen Wissens-Trainingspielen im Roguelite-Genre' hinzu.
Das Paper beschäftigt sich relativ lange mit ihrem 'Fallbeispiel', aber für uns ist eigentlich die Grundprämisse interessanter: 'Welche Fragen muss ich mir stellen, wenn ich ein Rogue-Like als Lernspiel verwenden möchte?' Daher habe ich die Zusammenfassung genau auf diesen Punkt fokussiert.
Die Zusammenfassung ist auch nicht als Ersatz für das Paper gedacht, sondern eher als Anreiz zum Vertiefen: 'Schau mal, was sie gemacht haben. Lohnt es sich, noch genauer hineinzusehen?'
=> [DOC] add Zusammensfassung: An Analysis Framework for Designing Declarative Knowledge Training Games Using Roguelite Genre (Related Work)

dungeon/src/task/Task.java, game/src/starter/Main.java
fixes #1045 
- iteriert über alle entitäten die zu einem Task gehören und sucht sich die Entität aus, die das `TaskContentComponent` implementiert, welches mit den übergebenen `TaskContent` gelinkt ist.
=> [Dungeon] add `Task#find` to find the entity to a `TaskContent`

dungeon/src/graphconverter/TaskGraphConverter.java
1. Eigentlich nur eine Kleinigkeit, aber in #1030 wurde der Aufruf der TaskBuilder im Generierungsprozess für die Levelgraphen "versteckt". Das macht zwar Sinn, weil ich die hier spätestens aufrufen muss, aber das ist ziemlich undurchsichtig. Daher habe ich eine explizite Methode dafür hinzugefügt.
2. Außerdem habe ich eine Methode hinzugefügt, die gleich den kompletten Convert-Flow ausführt (TaskBuilder, Level, PetriNetze). Das macht uns das Leben einfacher.
=> [DUNGEON] make TaskBuilder-call more explicit 

dsl/src/interpreter/DSLInterpreter.java, dsl/test/interpreter/TetsDSLEntryPointFinder.java, dsl/test_resources/config1.dng, dsl/test_resources/config2.dng
Implementiert die Interpretation eines `DSLEntryPoint` durch den `DSLInterpreter`.
Aktuell wird für jeden `DSLEntryPoint` das komplette Environment des DSLInterpreters neu aufgebaut. Aktuell unterstützt der DSLInterpreter auch nur DSL-Definitionen, die sich auf eine Datei beschränken, daher führt das zu keinen Problemen. Sobald an der Interpretation einer DSL-Definition mehrere Dateien beteiligt sind (bspw. wenn #171 umgesetzt ist) oder Funktionsdefinitionen potenziell länger als eine DungeonConfig leben (z.B. Taskbuilder, siehe #1041 ), sollte das geändert werden.
=> [DSL] Interpretation von `DSLEntryPoint`

game/src/contrib/entities/AIFactory.java, game/src/contrib/utils/components/ai/fight/MeleeAI.java
fixes #812
Der `path` in `MeleeAI#accept` war immer null, was zum Absturz geführt hat. Das lag daran, dass der `path` erst nach dem Hochzählen von `delay` gesetzt wurde.
Außerdem:
- `AIFactory` teilt den Monstern nun auch zufälig die MeleeAI zu
- Variablen in `AIFactory`, die noch Patrouille im Namen hatten, wurden umbenannt
=> [GAME] `path` ist nicht mehr null in `MeleeAI`

game/test/core/level/TileLevelAPITest.java
fixes #1022
Es bestand eine Abhängigkeit von `contrib.EntityFactory` in `TileLevelAPITest`. Diese wurde aufgelöst.
=> [GAME] remove `contrib.EntityFactory` from `TileLevelAPITest`

game/src/core/systems/LevelSystem.java, game/src/core/utils/components/draw/PainterConfig.java
fixes #925
Die Level Tiles werden um eine halbe Texture offset und dadurch befinden sich Helden und Monster in der Mitte des Tiles anstelle von dem oberen rechten Rand.
=> [GAME] Entities offset fix

game/src/contrib/hud/inventory/InventoryGUI.java
fixes #951 
Items können nun aus dem Inventar in die Welt geworfen werden, indem man sie außerhalb des Inventars zieht.
=> [GAME] made items droppable from inventory

game/src/core/components/PositionComponent.java, game/test/contrib/entities/MonsterTest.java, game/test/core/systems/CameraSystemTest.java
fixes #1065
Das Problem war, dass einige Entitäten nicht (wie es korrekt gewesen wäre) mit einer Illegalen-Position initialisiert wurden, sondern sich ein zufälliges Floor-Tile aus den Wizard-Quest-Selector level gesucht hatten. 
Ich habe den Ctor im PositionComponent so verändert, das Entitäten immer mit einer Illegalen Position initialisiert werden (der rest wird eh vom `PositonSystem` erledigt).
=> [GAME] fix bug where entities spawn in the wall (or outside the level)

game/src/contrib/entities/WorldItemBuilder.java
Der `WorldItemBuilder` platziert ein runtergefallenes Item nun per default auf die Illegale Position, das `PositionSystem` schiebt die dann auf eine gültige Position.
=> [GAME] Items now get dropped at the Illegal Position

dungeon/src/starter/Starter.java, game/src/contrib/components/SpikyComponent.java, game/src/contrib/entities/EntityFactory.java, game/src/contrib/systems/SpikeSystem.java, game/src/starter/Main.java
Kleine Änderungen für ein besseres Spielgefühl.
Es kann nun Schaden bei Kollision verursacht werden.
- Fügt das `SpikyComponent` hinzu (dieses speichert den Schaden-Wert, Typ und den Cool Down (Zeit zwischen zwei Schadensberechnungen bei Kollision).
- Fügt das `SpikeSystem` hinzu, welches pro Frame den Cool Down reduziert.
- Implementiert das Component in den Monstern.
- Implementiert das Schadensverhalten im Callback des `CollideComponent` im Helden.
Eigentlich recht einfach: Während einer Kollision überprüfe ich, ob `other` (also der, mit dem ich kollidiere) ein `SpikyComponent` hat und, wenn ja, ob dieses aktiv ist (nicht auf Cool Down). Wenn beides der Fall ist, kann ich `you` (also mir, z.B. dem Helden) Schaden hinzufügen. Dafür nehme ich die Informationen aus dem `SpikyComponent` …
=> [GAME] add SpikeSystem, hero now gets damage if he collides with monster

game/src/contrib/level/generator/graphBased/LevelGraphGenerator.java
Beim generieren der Level-Graphen hatte ich am Ende noch zufällig Kanten in den Graphen gezeichnet, damit dieser etwas spannender und abwechslungsreicher wird.
In der praxis werden die Level dadurch aber eher verwirrend und mühsam zu durchqueren (man verläuft sich ständig)
Ich hab diese Funktion jetzt erstmal deaktiviert. 
Perspektivisch könnte man da nochmal ran (#1092)
=> [GAME] remove random edges in levelgraph

game/src/contrib/configuration/KeyboardConfig.java, game/src/contrib/entities/EntityFactory.java, game/src/contrib/hud/inventory/InventoryGUI.java, game/src/contrib/item/Item.java, game/test/contrib/utils/components/item/ItemTest.java
fixes #950
Die Items im Inventar können nun per Tastendruck benutzt werden. Dazu muss mit der Maus über das Item gehovert und die Taste 'E' gedrückt werden. 
*Hinweis*: Items, die in einem anderen Inventar sind (z.B. das der Schatztruhe), können nicht direkt benutzt werden und müssen erst in das Spielerinventar gepackt werden.
=> [GAME] Items aus Inventar per Tastendruck verwenden

game/src/contrib/entities/AIFactory.java, game/src/contrib/entities/EntityFactory.java, game/src/contrib/utils/components/skill/Skill.java, game/test/contrib/utils/components/skill/SkillTest.java
Skill cool down kann nun in Millisekunden angegeben werden, das erlaubt präzisiere Einstellungen.
=> [GAME] change Skill cool down from seconds into milliseconds

game/assets/recipes/healtpotion_berry.recipe, game/assets/recipes/healtpotion_mushroom.recipe, game/src/contrib/item/Item.java, game/src/contrib/item/concreteItem/ItemPotionHealth.java, game/src/contrib/item/concreteItem/ItemPotionWater.java, game/src/contrib/item/concreteItem/ItemResourceBerry.java, game/src/contrib/item/concreteItem/ItemResourceEgg.java, game/src/contrib/item/concreteItem/ItemResourceMushroomRed.java, game/src/contrib/utils/components/health/DamageType.java, game/src/contrib/utils/components/item/ItemDataGenerator.java
Im wesentlichen entfernt dieser PR einen Großteil der Item-Typen als Random-Loot option (die Item machen eh noch nichts, die blockieren also nur den Spiel-Flow).
Einige Items habe ich "fertig" implementiert
- Heiltränke heilen den Spieler
- Wasser und Beeren heilen dien Spieler leicht, können aber zu Heiltränken gebraut werden (2 Beeren + 1 Wasser)
- Pilze fügen den Helden Schaden zu, außer er braut sie mit Wasser zu einen Heiltrank
- Ei lässt ein Monster auf den Helden spawnen.
=> [GAME] better Items and Crafting settings

dungeon/src/reporting/GradingFunctions.java, dungeon/src/task/AssignTask.java, dungeon/src/task/Element.java, dungeon/src/task/ReplacementTask.java, dungeon/src/task/Task.java, dungeon/src/task/quizquestion/MultipleChoice.java, dungeon/src/task/quizquestion/SingleChoice.java, dungeon/test/reporting/GradingFunctionsTest.java, game/src/core/utils/logging/CustomLogLevel.java
fixes #1059, fixes #1099 
Dieser PR fügt einfache Bewertungsfunktionen für verschiedene Task-Typen hinzu.
In diesem PR wird nicht das "Picken" der gegebenen Antworten aus dem Spiel implementiert.
Wir haben bereits in `Task` eine `BiFunction` als `scoringFunction` hinterlegt. Im Wesentlichen fügt dieser PR verschiedene `BiFunction`s hinzu, die dann je nach Aufgabentyp verwendet werden können.
Umgesetzte Grading-Funktionen
Anmerkung: Ein Punkt ist eher symbolisch zu verstehen. Die tatsächlich gegebenen/abgezogenen Punkte pro Antwort hängen von der Anzahl der Antworten und den zu erreichenden Punkten ab."
- ´Task` speichert jetzt die Punkte die nötig sind um die Aufgabe "Erfolgreich" zu beenden. 
- `ReplacementTask` hatten eine Zirkel-Abhängigkeit welch es unmöglich gemacht hat, eine Instanz …
=> [DUNGEON] add grading functions

dungeon/src/task/Task.java, game/src/core/Game.java, game/test/core/GameTest.java
fixes #1125 
- Zuerst wurde der Initiale EntityMapper richtig konfiguriert. Dieser existiert bereits vor jedem Level und wird zwar im richtigen Spiel nicht verwendet, aber in vielen unserer Test-Szenarien (da wir hier kein Level erzeugen). Früher wurde er nicht der `levelStorageMap` in `Game` hinzugefügt. das wurde jetzt geändert (Key-Value ist `null`).
- Fügt die Methode `Game#allEntites` hinzu, welche JEDE Entität im Spiel (nicht nur die im aktuellen Level) zurückliefert.
- Die Methode `removeAllEntites` hat früher nur alle Entitäten im aktuellen Level gelöscht, dieser bug wurde behoben
- Fügt die Methode `Game#find(Component)` hinzu, welche einen die Entität zurückliefert, welche das konkret übergebene Component implementiert (also die Instanz)
- Entfernt die Methode `Task#find` (wurde …
=> [GAME/DUNGEON] fix bugs in Game entity management, add `Game#find(Component)`

dsl/src/antlr/DungeonDSL.g4, dsl/src/interpreter/DSLInterpreter.java, dsl/src/parser/DungeonASTConverter.java, dsl/src/parser/ast/AstVisitor.java, dsl/src/parser/ast/CountingLoopStmtNode.java, dsl/src/parser/ast/ForLoopStmtNode.java, dsl/src/parser/ast/LoopBottomMark.java, dsl/src/parser/ast/LoopStmtNode.java, dsl/src/parser/ast/Node.java, dsl/src/parser/ast/VarDeclNode.java, dsl/src/parser/ast/WhileLoopStmtNode.java, dsl/src/runtime/ListValue.java, dsl/src/runtime/SetValue.java, dsl/src/semanticanalysis/SemanticAnalyzer.java, dsl/src/semanticanalysis/VariableBinder.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/parser/TestDungeonASTConverter.java, dsl/test/semanticanalysis/TestSemanticAnalyzer.java
Fixes #795 
Fügt Schleifen-Statements zur DSL hinzu (`for`-Schleife, die über einen iterierbaren `Value` iteriert, `counting for`-Schleife, die zusätzlich einen Counter für die Iterationen hat und eine `while`-Schleife). Erweitert die Grammatik entsprechend. Implementiert die semantische Analyse von Schleifen-Statements. Fügt `LoopBottomMark`-AST-Knoten hinzu, in dessen visit-Implementierung durch den `DSLInterpreter` die Schleifenbedingung überprüft wird und der interne Zustand der Schleife geupdatet wird. 
Refactored die Erzeugung von Variablensymbolen, da das in der semantischen Analyse für `for`- und `counting for`-Schleifen und für Variablendeklarations-Statements verwendet wird.
~TODO:~
=> [DSL] Loop-Statements hinzufügen

dungeon/src/reporting/AnswerPickingFunctions.java, dungeon/src/task/Task.java, dungeon/test/reporting/AnswerPickingFunctionsTest.java, game/src/contrib/components/InventoryComponent.java
fixes #1117, fixes #1116
- 
- `Task` speichert jetzt ein `Set` an `TaskContent` als container (so müssen dem Task TaskContent bekannt gemacht werden, welche im Spiel durch eine Chest o.ä dargestellt werden) incl. getter/setter
- readd `Task#find`, die funktion durchsucht jetzt alle Entitäten im Spiel
- `InventoryComponent` gibt jetzt ein `Stream` und kein `Array` mehr zurück, wenn man nach Items einer spezifischen Klasse fragt (das konnte sonst class-cast-exceptions verursachen) 
- Fügt die Answer-Picker hinzu
- `singleChestPicker` durchsucht den ersten Container im `Task` und gibt alle (von den `QuestItem`s gespeicherten) `TaskContent`s zurück. Oder in einfach: Guckt in die Kiste und gibt die Antworten zurück
- `multipleChestPicker` durchsucht alle Container im `Task` und gibt eine Set …
=> [DUNGEON] add Answerpicking-Functions

dungeon/assets/scripts/task_test.dng, dungeon/src/graphconverter/TaskGraphConverter.java, dungeon/src/starter/Starter.java, dungeon/src/starter/WizardTaskSelector.java
Beim parsen des Abhängikeitsgraphen in ein Petri-Netz gab es einen dreher im Funktionsaufruf, den hab ich gefixt. 
Außerdem hab ich im Starter ein paar Features hinzugefügt
- QuestLog zeigt nun alle PROCESSING-ACTIVE Tasks an
- Musik und Sound auch im Starter aktiviert
- Zum debuggen: Mit der Taste "F" wird ein aktueller PROCESSING-ACTIVE Task auf FINISHED-CORRECT gesetzt. Damit kann die Schaltung des Petri-Net getestet werden.
=> [DUNGEON] fix bug in petri net parsing, add some (debug) features to starter

game/src/core/level/elements/tile/DoorTile.java
Verbessert die Door-Tiles im geschlossenen Zustand an zwei stellen.
1. geschlossene Türen sind nicht mehr accessible, dadurch kann man als Spieler nicht mehr in die geschlossene Tür laufen (da sah albern aus) 
2. Die Türen werden nur offen gezeigt, wenn BEIDE Türen geöffnet sind. Vorher war die Textur unabhänig von der Partner Tür.
Die Null-Checks sind während der Initialisierung der Level nötig. Zur Game-Laufzeit gibt es keine Türen ohne partner Tür (also nicht verwirren lassen)
=> [GAME] optimize closed `DoorTile` visuals

game/src/contrib/entities/EntityFactory.java
Bisher ist die Kamera nach dem der Spieler gestorben ist immer auf den Levelanfang "gesprungen".
Das sah unschön aus.
In diesen PR wird in der Sterbe-Callback Funktion des Hero eine dummy Entität angelegt und das Position sowie Camera Component des Helden auf die dummy Entity umgelenkt.
Dadurch bleibt die Kamera an der letzten Position des helden stehen.
=> [GAME] fix bug where Camera would recenter after player dies

dsl/src/interpreter/DSLInterpreter.java, dsl/src/runtime/FunctionValue.java, dsl/src/runtime/GameEnvironment.java, dsl/src/runtime/nativefunctions/ExtensionMethod.java, dsl/src/runtime/nativefunctions/NativeFunction.java, dsl/src/semanticanalysis/types/IDSLExtensionMethod.java, dsl/src/semanticanalysis/types/TypeBuilder.java, dsl/src/semanticanalysis/types/TypeInstantiator.java, dsl/src/semanticanalysis/types/callbackadapter/BiFunctionCallbackAdapter.java, dsl/src/semanticanalysis/types/callbackadapter/BiFunctionFunctionTypeBuilder.java, dsl/src/semanticanalysis/types/callbackadapter/CallbackAdapter.java, dsl/src/semanticanalysis/types/callbackadapter/CallbackAdapterBuilder.java, dsl/src/semanticanalysis/types/callbackadapter/ConsumerFunctionTypeBuilder.java, dsl/src/semanticanalysis/types/callbackadapter/FunctionCallbackAdapter.java, dsl/src/semanticanalysis/types/callbackadapter/FunctionFunctionTypeBuilder.java, dsl/src/semanticanalysis/types/callbackadapter/IFunctionTypeBuilder.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/interpreter/mockecs/TestComponent2.java, dungeon/src/task/taskdsltypes/MultipleChoiceTask.java, dungeon/src/task/taskdsltypes/SingleChoiceTask.java
Fixes #916 
Fügt die Möglichkeit hinzu, auch Native Funktionen (also Funktionen, die nicht in der DSL selbst definiert werden) als `CallbackAdapter` zu verpacken und damit als Callback zu verwenden.
Integriert die `singleChoiceGrading` und `multipleChoiceGrading` Funktionen aus `GradingFunctions` als native Funktionen in die DSL. Fügt Extension Methoden zu Single und Multiplechoice tasks hinzu, um auch nachträglich grading funktion setzen zu können.
Kleine Bugfixes (siehe commit messages).
~TODO:~
=> [DSL] Grading-Funktionen in DSL integrieren

game/src/contrib/hud/crafting/CraftingGUI.java, game/src/contrib/hud/inventory/InventoryGUI.java
fix #1138 
anstelle des `FileHandler` mit absoluten Pfad wird nun der Pfad via `Gdx.files.internal` bestimmt.
Damit läuft das Inventar auch in der jar
=> [GAME] fix bug where an absolut path was used to link the font for the gui

game/src/contrib/components/HealthComponent.java, game/test/contrib/systems/HealthSystemTest.java
Fügt die `HealthComponent ` eine Option hinzu in den "god mode" zu gehen.
Im god-mode kann die HP nicht unter 1 fallen, daher kann die Entität nicht sterben.
Das könnte für die Evaluierung nützlich werden, da wir noch kein Save and Load System haben und die Studis bestimmt kein spaß daran haben, immer wieder von vorne anzufangen.
=> [GAME] add god-mode (option to make the player invincible) 

game/src/contrib/entities/EntityFactory.java, game/test/contrib/entities/ChestTest.java
Mit der `EntityFactory` konnten Kisten generiert werden ohne eine Position zu übergeben.
In diesen Fall wurde ein zufälliges (betretbares) Tile im aktuellen Level ausgewählt und die Kiste dort platziert.
Wenn ich die Kiste aber generiere, um sie in einen anderen Raum als den grade aktiven zu platzieren, ist diese Position ggf. ungültig.
Da wir das Problem schon an andere stelle hatten, haben wir dafür da `PositionSystem` und die `ILLEGAL_POSITION` eingeführt.
tldr: Kisten werden jetzt initial mit der ILLEGAL POSITION initalisiert und dann vom System zufällig verteilt. 
Anmerkung: Das ist  #1135 nochmal "neu", nachdem ich den rebase braindead verhauen habe.
=> [GAME] fix bug where Chest in EntityFactory could be placed out of level

dsl/src/interpreter/DSLInterpreter.java, dsl/src/semanticanalysis/types/AggregateType.java, dsl/src/semanticanalysis/types/DSLType.java, dsl/src/semanticanalysis/types/DSLTypeNameMember.java, dsl/src/semanticanalysis/types/TypeBuilder.java, dsl/src/semanticanalysis/types/TypeInstantiator.java, dsl/test/interpreter/TestDSLInterpreter.java, dsl/test/interpreter/mockecs/TestClassWithName.java, dungeon/src/task/Task.java, dungeon/src/task/taskdsltypes/MultipleChoiceTask.java, dungeon/src/task/taskdsltypes/SingleChoiceTask.java
Fügt neue Annotation `DSLTypeNameMember` zur Markierung eines Members hinzu, welchem bei Instanziierung des Typen der Namenswert zugewiesen werden soll.
Fügt für Datentypen, die einen Member mit dieser Annotation haben, ein neues "$NAME$" Symbol; dem entsprechenden `Value` wird beim Bearbeiten der Objektdefinition (`DSLInterpreter::visit(ObjDefNode)`) der Name des Idenitifers der Objektdefinition hinzugefügt.
=> [DSL] Named Aggregate Value ermöglichen -> erlaubt die Benennung von `Task` Objekten mit dem Namen des DSL-Identifiers.

build.gradle, dungeon/src/task/YesNoDialog.java, dungeon/src/task/quizquestion/QuizUI.java, dungeon/src/task/quizquestion/UIAnswerCallback.java, dungeon/test/manual/YesNoDialogTest.java, game/src/contrib/hud/UITools.java
fixes #1128 
*.   Fügt die Klasse `YesNoDialog` hinzu, welche es einfach macht, eine Ja-Nein Frage über das HUD zustellen und hinter jeder Antwort ein Callback zu hinterlegen. `YesNoDialog#showYesNoDialog(Task)` bastelt einen das UI incl Callback für das stellen einer Aufgabe zusammen. 
*   Fügt einen abort Button zu den Quiz-Fragen hinzu, damit man die Frage auch nicht beantworten kann.
Wenn "abort" gedrückt wird, wird der DSL-Callback **nicht** ausgeführt. 
@AHeinisch ich habe den PR bewusst gegen deinen Branch gestellt. Ich denke das passt da ganz gut rein.
=> [DUNGEON] add abort button to quest ui, add yes no dialog

dsl/src/antlr/DungeonDSL.g4, dsl/src/interpreter/DSLEntryPointFinder.java, dsl/src/interpreter/DSLInterpreter.java, dsl/src/parser/DungeonASTConverter.java, dsl/src/parser/ast/AstVisitor.java, dsl/src/parser/ast/MapTypeIdentifierNode.java, dsl/src/parser/ast/Node.java, dsl/src/runtime/GameEnvironment.java, dsl/src/runtime/MapValue.java, dsl/src/runtime/RuntimeObjectTranslator.java, dsl/src/runtime/SetValue.java, dsl/src/semanticanalysis/FunctionDefinitionBinder.java, dsl/src/semanticanalysis/SemanticAnalyzer.java, dsl/src/semanticanalysis/types/DSLType.java, dsl/src/semanticanalysis/types/IType.java, dsl/src/semanticanalysis/types/MapType.java, dsl/src/semanticanalysis/types/SetType.java, dsl/src/semanticanalysis/types/TypeBuilder.java, dsl/src/semanticanalysis/types/TypeInstantiator.java, dsl/test/interpreter/TestDSLInterpreter.java, dungeon/src/dsltypeproperties/EntityExtension.java, dungeon/src/task/AssignTask.java, dungeon/src/task/Element.java, dungeon/src/task/components/TaskContentComponent.java, dungeon/src/task/taskdsltypes/AssignTaskDSLType.java, game/src/contrib/components/InteractionComponent.java, game/src/contrib/components/InventoryComponent.java
Fixes #802 
Fügt den `AssignTaskDSLType` Adaptertyp hinzu (`AssignTask` heißt schon die tatsächliche `Task`-Subklasse, daher kann das Namensschema nicht konsistent zu `SingleChoiceTask` und `MultipleChoiceTask` gehalten werden).
Betrachtet die Eingabe der Zuordnungsregeln als ein set aus listen. In der Builder Methode von `AssignTaskDSLType` werden duplizierte `Element`-Instanzen (die den gleichen Wert haben) aussortiert. Der Einfachheit halber wird festgelegt, dass ein Element, was aus der DSL heraus erstellt wird, nur Strings halten kann, alles andere wäre schöner, macht nur aktuell etwas Probleme mit dem DSL Typsystem (müsste irgendwie abbilden, dass es egal ist, was der Datentyp vom `content` Member von `Element` ist).
Implementiert DSL `map` Typen. Fügt einen Szenariobuilder test für …
=> [DSL] Fügt Assignment Tasks (Zuordnungsaufgaben) zur DSL hinzu.

game/src/core/systems/DrawSystem.java
fixes #1147 
Im `DrawSytem` sortiere ich die Entitäten in zwei Listen
- Liste `players` beinhaltet alle Entitäten mit einen `PlayerComponent`
- Liste `npcs` alle Entitäten ohne `PlayerComponent`
Ich lasse jetzt erst die `npcs` zeichnen und danach die `players`, dadurch werden diese immer "oben" gezeichnet und nicht von Schatzkisten o.ä überdeckt.
=> [GAME] fix bug where player was drawn behind other entities

game/src/core/systems/VelocitySystem.java
fixes #1021
Das `VelocitySystem` hat nun keine Abhängigkeit zum `HealthComponent ` mehr.
Die Frage ob eine Entität tot ist, war unnötig, da tote Entitäten aus dem Spiel entfernt werden.
=> [GAME] Abhängigkeit von `contrib.HealthComponent` in `core.VelocitySystem` entfernt

dungeon/src/starter/Starter.java, game/src/contrib/hud/OkDialog.java
fixes #1149 
fügt einen OK-Dialog hinzu (der richtig skaliert, ähnlich wie der Yes-No Dialog) und verwendet ihn für den Questlog (`gradlew start` und dann `M` drücken)
=> [GAME] add OK-Dialog and use it for the questlog

dungeon/src/task/Quiz.java, dungeon/src/task/Task.java, dungeon/src/task/quizquestion/QuizUI.java, dungeon/src/task/quizquestion/UIAnswerCallback.java, dungeon/test/manual/quizquestion/QuizQuestionUITest.java
Fügt analog zum `YesNoDialog` die Methode `QuizUI.askQuizOnHud(task)` hinzu. 
Damit kann man schnell und einfach eine Quizfrage über das HUD beantworten lassen. Die Bewertungsfunktion wird entsprechend angestoßen, nachdem der Spieler seine Antwort bestätigt. hat.
=> [DUNGEON] add easy to use method to ask and grade a quiz over the hud

game/src/core/utils/components/draw/Painter.java
Hinzufügen des Offsets in dem frustum check.
nach fix:
=> [Game] Frustum check not using offset

dungeon/src/starter/Starter.java, dungeon/src/starter/WizardTaskSelector.java, dungeon/src/task/Task.java, dungeon/src/task/quizquestion/QuizUI.java, game/src/contrib/configuration/KeyboardConfig.java
Fixes #1098
Fügt dem Starter einen "Info-Screen"-Button ("L") hinzu.
Daraufhin wird im Titel der Szenariocode angezeigt, bestehend aus den jeweils ersten Buchstaben der bearbeiteten Tasks (in der Reihenfolge der Bearbeitung).
Ebenfalls wird die gespielte Zeit in Minuten angezeigt.
Danach folgt eine Auflistung der bearbeiteten Tasks (sowohl korrekt als auch inkorrekt) und die erreichten Punkte.
Wenn #1151 abgeschlossen ist, plane ich, den Yes-No-Dialog durch einen OK-Dialog zu ersetzen.
---
BELWOW IS FIXED
Ich habe noch nicht verstanden, woher der Zeilenumbruch bei "wuppie2" stammt. Das HUD sollte in der Lage sein, längere Strings problemlos anzuzeigen.
Siehe:
Vielleicht hat @AHeinisch eine Idee?
Hinweis: Die Levelauswahl beim Zauberer ist ebenfalls als `Task` umgesetzt. Daher filtere ich …
=> [DUNGEON] add info screen to show achieved points, played time and the scenario id

dungeon/src/task/Task.java, game/src/core/utils/logging/CustomLogLevel.java
Ergänzt `Task` um einen speraten Logger, welcher nur die abgegebenen Antworten und Punkte loggt. Das Logfile wird dann in `logs/solutions/` abgelegt.
=> [DUNGEON] add seperate Logger and Logfile for the task solutions

dungeon/src/starter/Starter.java, dungeon/src/starter/TaskSelector.java
Unser kleiner Zaubrer (der jetzt nach Absprache ein blauer Ritter ist), bringt das Spiel jetzt nicht mehr zum absturz, wenn bei der Missionsauswahl keine Aufgabe ausgewählt wird. Das Fenster geht jetzt einfach zu und man muss erneut mit ihm sprechen.
=> [DUNGEON] fix bug where game would crash if no mission was selected

dungeon/src/reporting/GradingFunctions.java, dungeon/src/starter/Starter.java, game/src/contrib/entities/EntityFactory.java, game/src/core/utils/Constants.java
Dieser PR passt den Dungeon-Starter so an, dass er für die Evaluierung verwende werden kann.
Key änderungen sind
* Godmode für den Spieler aktiviert
* Debug Funktionen deaktiviert/entfernt
* Nicht verwendete Syteme enfernt
* Floats werden jetzt auf eine Nachkommerstelle gerundet im HUD angezeigt
=> [DUNGEON] change dungeon starter for the evaluation 

dsl/src/interpreter/ScenarioBuilderStorage.java
Das `ScenarioBuilderStorage` speichert die zuletzt zurückgegebenen Szenariobuilder und wählt welche aus, die noch nicht so häufig zurückgegeben wurden.
=> [DSL] verbessere Randomisierung von ausgewählten Szenario-Buildern

dungeon/src/starter/Starter.java, dungeon/src/task/Task.java, game/src/contrib/entities/WorldItemBuilder.java, game/src/core/systems/PositionSystem.java, game/src/core/systems/VelocitySystem.java, game/test/core/systems/PositionSystemTest.java
Fixes, die ich für die Evaluierung mache (hoffentlich bis die zweite Gruppe dran ist):
* Fixt Bug, der dafür gesorgt hat, dass man nicht mehrfach mit Items auf den Boden interagieren konnte. Das führte dazu, dass man, wenn man einmal mit vollem Inventar versucht hat, das Item aufzuheben, das Item nie mehr aufheben konnte.
* Fixt Bug, bei dem manchmal Entitäten zufällig aufeinander platziert wurden. Wenn so ein Item auf einer Kiste lag, konnte man das Item nicht aufheben, da immer die Kiste aufging.
* Fixt Bug, der das Spiel zum Absturz gebracht hat, wenn eine Entität (aus noch unbekannten Gründen) out of bounds lag.
* löscht jetzt alte questitems aus dem Spielerinventar anstelle sie nur fallen zu lassen (die Studis haben die dann immer wieder aufgesammelt und waren genervt sie wieder …
=> [DUNGEON/GAME| fix bugs found at evaluation

game/src/contrib/components/CollideComponent.java, game/src/contrib/utils/components/skill/DamageProjectile.java
fixes #1174
Der Fehler beim Feuerball war, dass er von der linken unteren Ecke des Heros als Startpunkt ausging und auch mit der linken unteren Ecke des Feuerballs versucht hat, das Ziel (den Cursor) zu treffen. Dies führte dazu, dass die Flugbahnen anders als erwartet waren.
- Beispiel: der Cursor befindet sich unten links auf dem Helden, liegt aber Höher als der Startpunkt. Erwartungshaltung ist, dass der Feuerball nach unten fliegt, aber er flog nach oben.
Es wurde ein Offset eingebaut, damit der Startpunkt mittig des Helden liegt und der Feuerball mit seiner Mitte durch den Cursor fliegt.
Anmerkung: Berechnet werden sollte alles korrekt, jedoch sieht es aufgrund der Texturen so aus, als ob der Feuerball trotzdem nicht ganz durch den Cursor fliegt. Dies ist also ein optisches …
=> [GAME] Offset für Feuerball eingebaut

dungeon/src/reporting/GradingFunctions.java, dungeon/test/reporting/GradingFunctionsTest.java
fixes #1162 
Konzept:
Elemente die keinen Container zugeordnet werden sollen, werden jetzt gleich wie Elemente die einen Container zugeordnet werden sollen behandelt. Der Container "nicht zugeordnet" existiert so im Spiel nicht (also es gibt keine Kiste etc.) in der Bewertungslogik schaue ich daher in das "Leere"-Key-Element (was nicht Leer ist sondern ein Element beinhaltet welches einen leeren content ist) und gucke welche Items dem zugeordnet werden sollen. Ich behandel es also wie einen noralen Container.
Außerdem etwas Refactoring. Die beiden Methoden waren sehr ähnlich also hab ich Sie mit einem boolean `hard` versehen.
=> [DUNGEON] Fix bug in grading function for assignment task where empty sets would not be correctly scored.

dungeon/src/task/AssignTask.java, dungeon/src/task/Quiz.java, dungeon/src/task/ReplacementTask.java, dungeon/src/task/Task.java, dungeon/src/task/YesNoDialog.java, dungeon/src/task/quizquestion/QuizUI.java, dungeon/test/petriNet/PetriNetFactoryTest.java, dungeon/test/petriNet/PlaceTest.java, dungeon/test/task/TaskContentDoorOpenerTest.java, dungeon/test/task/TaskTest.java
fixes #1177 
Nachdem ein Task nicht 100% korrekt gelöst wurde, wird ein Fenster geöffnet, welches dann die richtige Lösung zeigt.
Dafür wurde die abstrakte Methode `correctAnswersAsString` in `Task` hinzugefügt.
Da wir noch keine vollständige Implementierung für die Crafting Aufgaben haben, hab ich auch keine konkrete Idee wie die Ersetzungsregeln aufzuzeigen sind.
Für SC,MC ist die Darstellung: 
Für AssignTask ist die Darsellung:
=> [DUNGEON] show correct answers after question was answered false

game/src/contrib/utils/components/skill/DamageProjectile.java
Ergänzung zu #1181
Die Berechnung im oben genannten PR hat das Offset der Hitbox nicht berücksichtigt. Dies ist nun behoben.
=> [GAME] Berechnung der Flugbahn von Projectile angepasst

game/test/core/components/DrawComponentTest.java
fixes #1188
Der `DrawComponentTest` hat mit einer Animation getestet, die Im `contrib` Package lag. Diese wurde mit einer Animation ersetzt, die im `core` Package liegt.
=> [GAME] Abhängigkeiten zu `contrib` in `DrawComponentTest` entfernt

dungeon/src/dsltypeproperties/EntityExtension.java
Fixes #1172 
Aus Issue:
Folgende "Fehler" sind aufgetreten
Weitere Bugs, die mir aufgefallen sind:
=> [DSL] Fix Fehlkonfiguration QuestChest

dungeon/src/task/Task.java, dungeon/src/task/YesNoDialog.java, dungeon/src/task/quizquestion/QuizUI.java, dungeon/src/task/taskdsltypes/AssignTaskDSLType.java, dungeon/src/task/taskdsltypes/MultipleChoiceTask.java, dungeon/src/task/taskdsltypes/SingleChoiceTask.java
fixes #1178 
Erweitert `Task` um ein Feld zur Erklärung wie eine Aufgabe gelöst werden muss (also auf fachlicher ebene).
Wenn eine Task im Spiel nicht 100% richtig gelöst wird, dann wird nach der Anzeige der erreichten Punkte, die Erklärung angezeigt und danach die richtige Lösung.
Wenn keine Erklärung gesetzt ist, wird nach den erreichten Punkten sofort die richtige Lösung angezeigt
@malt-r du müsstest das jetzt nur noch in der DSL einbauen
=> [DUNGEON] add Anzeige für Erklärungstext und korrekte Antwort an, falls ein Task falsch bearbeitet wurde

dungeon/src/reporting/AnswerPickingFunctions.java, dungeon/test/reporting/AnswerPickingFunctionsTest.java
Die `AnswerPickingFunctions` haben zwar nicht Quest-Items ignoriert, haben aber Items von anderen Quests mit eingesammelt. Das bedeutet ich konnte eine Antwort aus Aufgabe B benutzen, um Aufgabe A zu beantworten (okay, zumindest theoretisch, da die Bewertungsfunktion das nochmal abgefangen hat). 
Jetzt sammeln die Funktionen nurnoch die Antworten vom entsprechenden Task.
=> [DUNGEO] fix bug where answer picking functions would also collect items from other tasks

dungeon/src/task/Task.java
Es werden jetzt alle QuestItems im Spiel entfernt (also aus dem Helden Inventar, aus Kisten und die, die in der Welt liegen), wenn eine Task fertig bearbeitet ist.
=> [DUNGEON] remove all QuestItems after a Task is solved

game/src/core/systems/PositionSystem.java, game/test/core/systems/PositionSystemTest.java
Das PositionSystem platziert jetzt die Entitäten in der mitte eines Tiles.
@AHeinisch ich glaube du hattest das schonmal für die Schatzkisten gemacht. Ist jetzt wieder da, nur woanders :)
=> [GAME] spawn entities on tile center

game/src/core/Entity.java, game/src/core/Game.java, game/src/core/game/ECSManagment.java, game/src/core/game/GameLoop.java, game/src/core/game/PreRunConfiguration.java, game/test/contrib/utils/components/item/ItemTest.java
fixes #970 
Ich habe die Inhalte der Klasse `Game` aufgesplittet.
- In `PreRunConfiguration` liegt jetzt alles, was vor dem Start des eigentlichen Spiels gesetzt/konfiguriert werden muss/kann. 
- In `ECSManagement` liegt alles, was irgendwas mit dem Verwalten der Entitäten oder Systeme zu tun hat. 
- In `GameLoop` liegt alles, was mit dem Schleifendurchlauf zu tun hat (inklusive Starter-Methode).
Ich habe keine neuen Logiken geschrieben, lediglich extrahiert.
Durch diese Auslagerung sollte es einfacher sein, den Code zu navigieren. 
Die Klasse `Game` kann (und sollte) weiterhin als zentrale API verwendet werden. Das bedeutet, dass ich für alle Methoden eine Weiterleitung/Delegation(?) (gibt es dafür eigentlich einen richtigen Namen?) eingebaut habe. Wir hatten das schon einmal für die …
=> [GAME] split `Game` into seperat classes, use `Game` as center API

dungeon/assets/scripts/internal_scenario_builder_usage.dng, dungeon/src/dsl/interpreter/DSLInterpreter.java, dungeon/src/dsl/interpreter/ScenarioBuilderStorage.java, dungeon/src/dsl/runtime/FunctionValue.java, dungeon/src/dsl/runtime/GameEnvironment.java, dungeon/src/dsl/runtime/Value.java, dungeon/src/dsl/semanticanalysis/FunctionDefinitionBinder.java, dungeon/src/dsl/semanticanalysis/SemanticAnalyzer.java, dungeon/src/dsl/semanticanalysis/types/TypeBuilder.java, dungeon/src/dsl/semanticanalysis/types/TypeInstantiator.java, dungeon/src/dsl/semanticanalysis/types/callbackadapter/CallbackAdapter.java, dungeon/src/dslinterop/nativescenariobuilder/NativeScenarioBuilder.java, dungeon/src/task/Task.java, dungeon/src/task/dslinterop/AssignTaskDSLType.java, dungeon/src/task/dslinterop/MultipleChoiceTask.java, dungeon/src/task/dslinterop/SingleChoiceTask.java, dungeon/src/task/utils/hud/QuizUI.java, dungeon/src/task/utils/hud/YesNoDialog.java, dungeon/test/dsl/interpreter/TestDSLInterpreter.java
Implementiert native Scenario Builder, also native Funktionen, die eine Aufgabe als Argument erhalten und ein Set von Entitäts-Sets zurück geben. Nutzt den gleichen Mechanismus wie die bisherigen ScenarioBuilder.
Durch die Änderungen sind einige Tests kaputt gegangen, die davon abhängig sind, dass ein bestimmter Scenario-Builder verwendet wird. Daher implementiert dieser PR auch das forcen eines Scenario builders für einen bestimmten Task.
Enthält kleinere Fixes (z.B. Überprüfung auf "empty" `FunctionValue` in TypeInstantiator).
Wird #1136 obsolet machen, da wir hier in diesem PR die bereits vorhandenen Mittel des `DSLInterpreter`s nutzen und keine neuen Strukturen bauen.
=> [DSL] Native Scenario Builder in DSL integrieren; Forcen von Scenario Builder für einzelne Tasks ermöglichen

dungeon/src/dsl/runtime/EncapsulatedObject.java, dungeon/src/dsl/semanticanalysis/types/AggregateType.java, dungeon/src/dsl/semanticanalysis/types/TypeBuilder.java, dungeon/test/dsl/semanticanalysis/types/TestTypeInstantiator.java
Fixes #698 
Verschiebt die Berechung von besagter Map aus `EncapsulatedObject` in den `TypeBuilder`, sodass das nur einmal pro Datentyp gemacht wird und nicht erneut für jedes erstellte `EncapsulatedObject`.
=> [DSL] DSL Typ-Member zu Field Map pro Datentyp speichern

game/test/contrib/utils/components/item/ItemTest.java, game/test/contrib/utils/components/skill/SkillTest.java
fixes #1220, fixes #1219
zu #1220 
- Der Test hatte eine Zeitabhängigkeit und scheinbar war 1ms cooldown teilweise zu viel, daher hab ich jetzt einen Thread-Sleep eingebaut
zu #1219 
Ich konnte den Fehler nicht ganz reproduzieren, aber es sieht stark danach aus, als ob die Testenv. vorher nicht korrekt aufgeräumt wurde.
=> [GAME] fix `SkillTest #executeWhenCoolDownExpired ` and `ItemTest#testCollectNoInventory`

game/src/contrib/utils/components/skill/Skill.java, game/test/contrib/utils/components/item/ItemTest.java, game/test/contrib/utils/components/skill/SkillTest.java
fixes https://github.com/Programmiermethoden/Dungeon/issues/1219,
fixes #1220
Zu #1219
Wenn ein Level erzeugt wird, welches keinen Ausgang hat, wird automatisch einer platziert. Im Test konnte es daher zufällig passieren, dass der Punkt 0,0 der Ausgang ist und damit ein Item nicht darauf gedroppt wurde.
=> [GAME] fix  `ItemTest#testCollectNoInventory`

dungeon/src/dslinterop/dsltypeadapters/QuestItemAdapter.java, dungeon/src/dslinterop/nativescenariobuilder/NativeScenarioBuilder.java, dungeon/test/dsl/interpreter/TestDSLInterpreter.java, game/src/contrib/hud/crafting/CraftingGUI.java, game/src/contrib/item/Item.java, game/src/contrib/item/concreteItem/ItemPotionHealth.java, game/src/contrib/item/concreteItem/ItemPotionWater.java, game/src/contrib/item/concreteItem/ItemResourceBerry.java, game/src/contrib/item/concreteItem/ItemResourceEgg.java, game/src/contrib/item/concreteItem/ItemResourceMushroomRed.java, game/src/core/components/DrawComponent.java, game/src/core/utils/components/draw/Animation.java, game/src/core/utils/components/draw/SimpleIPath.java, game/test/contrib/components/InventoryComponentTest.java, game/test/contrib/utils/components/item/ItemTest.java, game/test/core/utils/components/draw/AnimationTest.java
Ein großer Teil des aufräumen von Pfaden.
- Entfernt String pfade für Animationen
- Entfernt mix aus Factory und konstruktoren
Teil von #1143 
Da es zu viele Baustellen gibt, würde ich hier Schritt für Schritt in einzelnen PRs weiter aufbauen.
=> [Game] refactor animationclass only using factory methods instead of mix

dungeon/assets/scripts/example.dng, dungeon/doc/dsl/examplescripts/quickstart_task_dependency.dng, dungeon/doc/dsl/task_definition.md, dungeon/doc/readme.md, dungeon/src/task/dslinterop/DSLMultipleChoice.java, dungeon/test/dsl/interpreter/TestDSLInterpreter.java, dungeon/test/dsl/semanticanalysis/TestSemanticAnalyzer.java, dungeon/test_resources/task_test.dng
Fixes #1212 
Beschreibt, wie die implementierten Aufgabentypen in einer DSL-Konfiguration definiert werden, welche Eigenschaften die Aufgabendefinitionen haben und was diese Eigenschaften bedeuten.
=> [DOC] DSL-Taskdefinition dokumentieren

dungeon/src/dslinterop/dsltypeadapters/QuestItemAdapter.java, dungeon/src/dslinterop/nativescenariobuilder/NativeScenarioBuilder.java, game/src/core/utils/components/draw/Animation.java
Fixes #1241 
Die `Animation.fromSingleImage` waren falsch, die `priority` wurden als `frameTime = 0` übergeben. Habe eine `IllegalArgumentException` im ctor von `Animation` hinzugefügt, um das in Zukunft besser debuggen zu können.
=> [GAME/DSL] Fix ArithmeticException in QuestItems von SzenarioBuildern

game/src/core/components/PositionComponent.java, game/test/contrib/entities/ChestTest.java, game/test/core/components/PositionComponentTest.java, game/test/core/level/TileLevelAPITest.java
setzt #1025 für die Klasse `PositionComponent` um.
Nennenswerte Änderung: 
`position()` gibt nun eine Kopie des Punktes. zurück, wodurch eine direkte veränderung der Werte nicht mehr mögliich ist, man muss jetzt immer den setter verwenden.
=> [GAME] cleanup `PositionComponent` 

.github/CODEOWNERS
Wie im letzten Meeting schon einmal angesprochen, haben wir aktuell für das `dungeon`-Projekt nicht die Kapazitäten, die einzelnen Pull Requests richtig zu reviewen (teilweise aus Zeitgründen, teilweise aus Know-How-Gründen). Praktisch führt das dazu, dass @malt-r und ich uns die Pull Requests zuschicken und mehr oder weniger blind abnicken.
Was die Sache noch ärgerlicher macht, ist, dass wir aktuell am Refaktorisieren/Aufräumen sind, und @malt-r mir jetzt immer ein OK geben muss, wenn ich im Framework einen Methodennamen ändere... Das bedeutet Zeitverlust auf beiden Seiten.
Daher mein Vorschlag: Raus mit den Owner-Rechten auf dieser Ebene. Da nur @Programmiermethoden/dungeon in den Master mergen kann, haben wir eine gewisse Absicherung.
Im Framework behalte ich das Vier-Augen-Prinzip …
=> [Org] remove global code owner

game/src/core/components/PlayerComponent.java, game/src/core/systems/PlayerSystem.java
setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `PlayerComponent` und `PlayerSystem` (durch das refaktorn musste ich eh an beide klassen) um.
=> [GAME] cleanup `PlayerComponent` and `PlayerSystem` 

game/src/contrib/crafting/Crafting.java
Im `Crafting` wird (wenn das Dungeon im jar ausgeführt wird) eine Resourcen-Referenz als Root benötigt. 
Ich habe das damals (dummerweise) von `Main.class` auf `Crafting.class` geändert. Mit `Game.class` geht es wieder + die Klasse `Game` läuft nicht Gefahr gelöscht zu werden. 
So richtig sexy ist das aber auch nicht.
=> [GAME] fix bug where jar would crash, use Game as Resource Reference root in `Crafting` 

blockly/src/client/Client.java, dungeon/src/starter/Starter.java, dungeon/test/manual/quizquestion/CallbackTest.java, dungeon/test/manual/taskgeneration/TaskGenerationTest.java, game/doc/quickstart.md, game/src/contrib/components/IdleSoundComponent.java, game/src/contrib/entities/MonsterFactory.java, game/src/contrib/hud/UIUtils.java, game/src/contrib/hud/crafting/CraftingGUI.java, game/src/contrib/hud/elements/Button.java, game/src/contrib/hud/inventory/InventoryGUI.java, game/src/contrib/systems/IdleSoundSystem.java, game/src/core/Game.java, game/src/core/configuration/Configuration.java, game/src/core/game/GameLoop.java, game/src/core/game/PreRunConfiguration.java, game/src/core/systems/DrawSystem.java, game/src/core/systems/LevelSystem.java, game/src/core/utils/components/draw/Animation.java, game/src/core/utils/components/draw/Painter.java, game/src/core/utils/components/draw/PainterConfig.java, game/src/core/utils/components/draw/TextureMap.java, game/src/starter/RandomDungeon.java, game/src/starter/RoomBasedDungeon.java, game/test/core/level/TileLevelAPITest.java, game/test/core/utils/components/draw/AnimationTest.java
fixes #1143 
Ich bin noch einmal rum gegangen und habe alle String-Pfade durch `IPath`s ausgetauscht.
Das `Dungeon`-Projekt hab ich nicht durchwühlt, aber wichtig ist das Framework
@AHeinisch damit wäre das dann auch durch.
=> [GAME] replace last String-Paths with `IPath` 

.github/CODEOWNERS
fixes #1048 
Macht @cagix zum globalen code owner.
=> [ORG] set cagix as global code owner, archive project (30.11.2023)

build.gradle, doc/wiki/code-conventions.md
SpotBugs ist ganz nett, um typische Anti-Pattern zu finden bzw. gar nicht erst einzubauen. Allerdings wurde während der gesamten aktiven Projektentwicklung nicht darauf geachtet, und wer soll das jetzt nachträglich alles gerade ziehen?! 
=> SpotBugs wird mit diesem PR aus der Konfiguration entfernt.
(siehe auch #1226)
=> tool: remove spotbugs

build.gradle
https://github.com/Programmiermethoden/Dungeon/blob/a5aaa0ab62fa11c4fdbd2e66d0a7d70d1d93db20/build.gradle#L25-L27
Es wird für die `repositories` eigentlich nur noch der Standardeintrag `mavenCentral()` benötigt. Dort werden alle `dependencies` gefunden, und es baut und läuft ohne die extra Einträge.
fixes #1329
=> Gradle: remove superfluous repositories

build.gradle
According to the Gradle documentation `org.gradle.nativeplatform.platform.internal.DefaultNativePlatform` is supposed an _internal_ package and not to be used in customers code.
Using `System.properties['os.name'].toLowerCase().contains('mac')` instead of `DefaultNativePlatform.currentOperatingSystem.isMacOsX()` we can also avoid the solo import `import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform` ... 
fixes #1331
=> Gradle: simplify recognition of macOS

.github/dependabot.yml
Depandabot fügt selbstständig neue Label in das Projekt ein, die es für die PR braucht. Das nervt auf Dauer, deshalb soll dieser PR das Verhalten abstellen.
Lt. Doku soll ein `labels: [ ]` hinzugefügt werden, um das Nutzen (und entsprechend Neudefinieren) von Labels durch Dependabot abzuschalten.
Dokumentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels
=> Dependabot: disable all labels

build.gradle
Remove ext vars
fixes #1330 
Tested on Windows with:
`run`, `start`, `debug`, `jar`, `starterJar`
without any special incidents
=> Gradle: remove superfluous "ext" definitions

dungeon/build.gradle, dungeon/src/dslinterop/nativescenariobuilder/NativeScenarioBuilder.java
In `dungeon/src/dslinterop/nativescenariobuilder/NativeScenarioBuilder.java` hard-coded references to assets from the game subproject were present. 
This PR changes that: Instead of `character/knight` from the Game subproject use `character/blue_knight`, which is actually defined in the Dungeon subproject.
This also makes the reference `{project(':game').sourceSets.main.resources.srcDirs}` to the Game subproject assets in `build.gradle` of Dungeon superfluous and resolves IntelliJ's warning about duplicate content roots.
closes #1418
=> DSL: fix hard coded references to assets from Game subproject

dungeon/src/entrypoint/DSLFileLoader.java
This should allow to start the dungeon using relative and/or absolute paths to a .dng file:
```
./gradlew :dungeon:runStarter --args=doc/dsl/examplescripts/example_scenario.dng  
./gradlew :dungeon:runStarter --args=/Users/foo/bar/pm-dungeon/dungeon/doc/dsl/examplescripts/example_scenario.dng
```
Note: Since `./gradlew :dungeon:runStarter` starts **inside** the `dungeon` subproject, we can't use `--args=dungeon/doc/dsl/examplescripts/example_scenario.dng`, but have to use a relative path inside the `dungeon` subproject like `--args=doc/dsl/examplescripts/example_scenario.dng`.
=> DSL-Loader: allow relative path to .dng file

dungeon/src/starter/Starter.java
Aktuell kann der Starter mit und ohne Argumente gestartet werden. 
- Wenn ohne Argumente gestartet, versucht er dynamisch per JFileChooser eine Konfiguration zu erfragen und beendet das Spiel, wenn der User keine Datei auswählt.
- Wenn mit Argumenten gestartet, werden die Strings als Pfade aufgelöst und es wird versucht, diese Dateien zu laden.
- Wenn es keine ".dng"-Dateien sind, werden sie stillschweigend ignoriert.
- Wenn aus einer .dng-Datei keine Entrypoints geladen werden können, wird das stillschweigend ignoriert.
Das Problem ist aber, dass die Liste der Entrypoints u.U. leer ist und das Spiel damit startet und man sich fragt, was grad kaputt ist (siehe #1420). Es wäre besser, wenn das Spiel dann abgebrochen würde.
Dieser PR bricht das Spiel ab, wenn keinerlei Entrypoints geladen …
=> Dungeon: do not start with empty task list

dungeon/assets/scripts/example.dng, dungeon/assets/scripts/template.dng, dungeon/doc/dsl/examplescripts/example_scenario.dng, dungeon/doc/dsl/scenario_builder.md, dungeon/doc/how_to_play.md, dungeon/test_resources/task_test.dng
Use "blue_knight" (present in `Dungeon` subproject) instead of "knight" (only present in `Game` subproject for the time being):
`grep -Irl "character/knight" dungeon/ | xargs sed -i 's/character\/knight/character\/blue_knight/g'` and manual adjustments...
=> Dungeon Starter: Fix example.dng - use "blue_knight" from dungeon/assets instead of "knight" from game/assets

.github/workflows/github_ci.yml
Es lag an dem Gradle-Cache (des Gradle-Plugins). Diesen habe ich in diesem PR entfernt.
closes #1354 
---
It was due to the Gradle cache (of the Gradle plugin). I removed it in this pull request.
=> CI: remove Gradle caching in actions/setup-java to avoid warnings on Windows runners

blockly/build.gradle, dungeon/build.gradle
@tgrothe Ich habe die in https://github.com/Dungeon-CampusMinden/Dungeon/issues/1426#issuecomment-1973527393 vorgeschlagenen Änderungen hier mal eingebaut:
> @tgrothe So, ich habe jetzt mal ein wenig für Dich recherchiert.
> 
> Wie eingangs erwähnt, werden die Ressourcen (Assets) beim Auflösen der Projektabhängigkeiten nicht mitgenommen. Also für `dungeon` fehlen die Assets aus `game`, obwohl dieses Subprojekt eine Dependency für `dungeon` ist. Für die .class-Files ist das kein Problem, weil Gradle hier das Jar-File aus `game` einfach in den Classpath für `dungeon` packt. Die Lösung besteht darin, die Assets aus `game` beim Bearbeiten von `dungeon` in den Build-Path von `dungeon` kopieren zu lassen: [processResources](https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.Proces …
=> Gradle: fix asset configuration

build.gradle, dependencies.gradle
Brauchen wir `com.github.ben-manes.versions` wirklich? Das Plugin sorgt dafür, dass man auch lokal nach Updates der Gradle-Plugins und/oder genutzten Dependencies suchen kann. Da das aber Dependabot auf der CI übernimmt, ist das Plugin eigentlich überflüssig.
Dieser PR soll das Plugin entfernen. Damit sind nur noch wirklich benötigte Plugins konfiguriert.
closes #1339
=> Gradle: remove Ben-Manes plugin

dungeon/src/contrib/level/generator/graphBased/levelGraph/LevelNode.java
`contrib/level/generator/graphBased/levelGraph/LevelNode.java`: use `getFirst()`  (available since Java 21) to retrieve first element of a list/set instead of `get(0)` to improve readability. 
no changes in API, just minor refactoring.
=> Dungeon: refactor LevelNode to use getFirst()

dungeon/src/contrib/hud/UIUtils.java, dungeon/src/contrib/hud/dialogs/OkDialog.java, dungeon/src/contrib/hud/dialogs/TextDialog.java, dungeon/src/contrib/hud/dialogs/YesNoDialog.java, dungeon/src/contrib/systems/HealthBarSystem.java, dungeon/src/task/game/hud/QuizUI.java
Die Klasse `contrib.hud.UIUtils` enthält mit dem Feld `DEFAULT_SKIN` libGDX-Abhängigkeiten, die direkt vom ClassLoader geladen/initialisiert werden. Dadurch kann diese Klasse bisher nicht in JUnit-Tests getestet werden.
Dieser Pull-Request führt ein Refactoring durch und führt das Singleton-Pattern in der Variante Lazy-Loading ein für das Feld `DEFAULT_SKIN`: In der API wird das Feld `public static final Skin DEFAULT_SKIN` durch die neue Hilfsmethode `public static Skin defaultSkin()` ersetzt, die beim ersten Aufruf das interne statische Feld initialisiert. 
Alle abhängigen Klassen werden ebenfalls umgestellt.
=> Dungeon: refactor UIUtils to allow load-on-demand for libGDX elements

blockly/src/client/Client.java, dojo-dungeon/src/starter/DojoStarter.java, dungeon/src/starter/RandomDungeon.java, dungeon/src/starter/RoomBasedDungeon.java, dungeon/src/starter/Starter.java, dungeon/test/manual/YesNoDialogTest.java, dungeon/test/manual/quizquestion/CallbackTest.java, dungeon/test/manual/quizquestion/QuizQuestionUITest.java, dungeon/test/manual/taskgeneration/TaskGenerationTest.java, game/src/core/Game.java, game/src/core/game/PreRunConfiguration.java, game/src/core/utils/logging/LoggerConfig.java, game/src/starter/BasicStarter.java
Der Logger ist per Default so konfiguriert, in **jedem Durchlauf** der Gameloop wirklich einfach **ALLE Logmeldungen** rauszuschreiben. Dadurch werden schnell mehrere Hunderte Megabyte an Daten erzeugt, was im Nicht-Debugging-Einsatz problematisch werden kann (und auch schlicht unsinnig ist) ...
Dieser PR ändert die API in Bezug auf die Logging-Initialisierung und erlaubt es, bei der Initialisierung des `baseLogger` das gewünschte Log-Level mitzugeben. 
Durch das hohe (und zunächst nicht direkt erklärliche) Maß an Indirektionen beim Setup des Loggers sind u.a. folgende Klassen betroffen:
1. Starter (diverse): In den Startern in den verschiedenen Sub-Projekten wird i.d.R. in der Methode `configGame()` die Initialisierung des Loggers per `Game.initBaseLogger()` vorgenommen. **Änderung**: Es …
=> Logger: change internal API to support the configuration of the log level during setup

build.gradle, dungeon/src/task/Task.java, game/src/core/utils/logging/LoggerConfig.java, gradle.properties
In #1467 wurde eine Abhängigkeit zwischen Code und Gradle-Konfiguration eingeführt: Der Name des Ordners, in dem die Log-Dateien abgelegt werden sollen, wurde bereits vor #1467 an zwei Stellen im Code fest definiert und in #1467 nun auch noch einmal in der `build.gradle`, um in den `clean`-Tasks die Log-Ordner löschen zu können.
Dieser PR hebt diese Einschränkung auf und definiert den Basis-Log-Ordner in `gradle.properties` und instrumentiert damit den Java-Code:
1. In `gradle.properties` wird eine System-Property `BASELOGDIR` für den Log-Ordner definiert. Diese wird im `clean`-Task benutzt, und zusätzlich werden alle System Properties den `Exec`-Tasks als solche mitgegeben (unschön, aber sonst kommen diese da nicht an). Damit wird auch die System-Property `BASELOGDIR` innerhalb der …
=> Gradle: configure the logging base folder via a system property

build.gradle, gradle.properties
In #1469 wurde die Konfiguration des Log-Ordner auf eine System Property umgestellt. Der konfigurierte Wert kommt korrekt in den Sub-Projekten an und wird auch innerhalb der Java-Methoden (beispielsweise https://github.com/Dungeon-CampusMinden/Dungeon/blob/69d2a1dc56923f43acb377da980cebc7642e38e7/game/src/core/utils/logging/LoggerConfig.java#L29) korrekt gelesen. 
**Aber es macht auf einmal einen Unterschied**, ob man 
- (a) `./gradlew dungeon:runStarter` (oder einen beliebigen anderen Starter) auf der Konsole aufruft, oder 
- (b) aus der IDE heraus anklickt. 
Im ersten Fall (Konsole) wird der Log-Ordner auf einmal im Top-Level-Ordner erzeugt (**falsch**!) und der Logger findet den Ordner anschließend nicht, da er anschließend im Subprojekt danach sucht!?! Beim Start aus der IDE oder dem …
=> Gradle: fix logging config

dungeon/doc/readme.md
In der [Readme.md](https://github.com/Dungeon-CampusMinden/Dungeon/blob/master/dungeon/doc/readme.md) wird noch auf das mitlerweile geschlossene [Issue 1215](https://github.com/Dungeon-CampusMinden/Dungeon/issues/1215) verlinkt. Aus dem Kommentar 'Fixes https://github.com/Dungeon-CampusMinden/Dungeon/issues/1215 (als Link auf die Petri-Netz-Doku)' am zugehörigen [Pull Request 1300](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1300) habe ich den gemeinten Link geschlussfolgert.
=> DSL: fix links in docs

dojo-dungeon/src/dojo/rooms/rooms/boss/Fragen_Lambda.java
Dieser PR fixt die als "richtig" vorgegebene Antwortoption für den Lambda-Boss-Raum (dojo-dungeon/src/dojo/rooms/rooms/boss/Fragen_Lambda.java). 
Statt der nicht korrekten Option "Interface mit 1 Methode" ist nun korrekt "namenslose Methode" als richtige Antwort vorgegeben.
closes #1502
=> Dojo: Fix choices in lambda boss room

dojo-dungeon/src/dojo/compiler/DojoCompiler.java, dojo-dungeon/todo-assets/Fehler_Syntax/FehlerhafteKlasse.java
Beim Vergleich der erwarteten Antwort und der tatsächlichen Antwort (String) soll die Gross-/Klein-Schreibung keine Rolle spielen.
Dieser PR ändert den Vergleich für den Test von `FehlerhafteKlasse` entsprechend auf `equalsIgnoreCase`.
Follows from #1503 
closes #1501
=> Dojo: DojoCompiler: Ignore cases in string comparison

blockly/build.gradle
Räume die Konfiguration des Blockly-Subprojekts ein wenig auf:
- Entferne das Plugin "java". Dieses wird global definiert, kein Bedarf für eine Wiederholung hier.
- Füge eine Konfiguration für die Assets ein. Wir haben hier zwar keine eigenen Assets, nutzen aber die aus `game` und `dungeon`. Interessanterweise scheint es auch ohne diesen expliziten Pfad zu funktionieren, aber nun ist es explizit.
- Passe die Schreibweisen an die anderen Gradle-Konfigurationsfiles an.
=> Gradle: cleanup blockly configuration

dojo-dungeon/build.gradle
Räume die Konfiguration des Dojo-Dungeons ein wenig auf:
- Stufe die Dependency für das Sub-Projekt "dungeon" von `api` auf `implementation` herunter. Wir brauchen hier das Sub-Projekt "dungeon", aber wir brauchen es nicht transitiv bzw. wir wollen keine API o.ä. anbieten. 
- Entferne das Plugin "java-library". Es wurde nur für die Dependency-Settings `api` gebraucht. Da wir das nicht mehr haben/brauchen, kann das Plugin entfernt werden (es wurde "java" global gesetzt, das reicht).
- Entferne die Settings für Test-Sourcen und -Assets. Wir haben keine Tests hier.
- Benenne Start-Task in `runDojoDungeon` um, um konsistent zu den anderen Sub-Projekten zu werden
- Entferne den überflüssigen Kommentar. Entweder überall Kommentare oder nirgendwo.
=> Gradle: cleanup dojo configuration

dependencies.gradle, game/build.gradle
Wir haben immer noch die Abhängigkeit zu Gson in unserer Konfiguration und exportieren die sogar als "API". Dabei nutzen wir das scheinbar gar nicht (mehr) - ein grep nach "gson" und/oder "Gson" findet nichts und alle Starter/Builder/Tests laufen auch ohne Gson. 
Dieser PR entfernt Gson aus der Build-Konfiguration.
=> Gradle: remove Gson config (not needed anymore)

dependencies.gradle, dungeon/build.gradle, game/build.gradle
Game führt Dependencies für libGDX ein, die transitiv auch von Dungeon genutzt werden. Dieser PR soll die Sub-Projekte stärker entkoppeln, und es soll deutlicher ersichtlich werden, was im jeweiligen Sub-Projekt wirklich gebraucht wird. 
Zugleich sollte die von uns in Game und/oder Dungeon genutzte libGDX-API nicht für die Kunden von Game/Dungeon weitergegeben (_exposed_) werden - wenn jemand Dungeon als Basis nutzt und zusätzlich gern noch etwas aus libGDX in der eigenen Implementierung nutzen möchte, dann sollte er/sie/es auch selbst in der eigenen Konfiguration deklarieren (und nicht einfach stillschweigend transitiv von uns mitnutzen).
1. Führe die in Dungeon benötigten libGDX-Dependencies in der build.gradle vom Dungeon-Subprojekt explizit ein.
2. Entferne alle nicht benötigten …
=> Gradle: cleanup gradle for game and dungeon

dungeon/src/task/game/hud/QuizDialogDesign.java
In Level 2 wird zur Eingabe der Antwort ein Texteingabefeld genutzt, in dem ein zur Antworteingabe animierender Default-Text steht. Dieser soll beim Klick in das Feld gelöscht werden, damit User die Eingabe sofort vornehmen können.
Dieser PR fügt einen `ClickHandler` zum Textfeld in Level 2 hinzu, der den Defaulttext im Textfeld bei Klick in das Feld löscht.
closes #1519
=> Dojo: lösche Texteingabefeld bei Klick in das Feld (betrifft Level 2, Pattern-Abfrage)

dojo-dungeon/src/dojo/rooms/rooms/riddle/Fragen_Pattern.java, dojo-dungeon/src/starter/DojoStarter.java
Der Zauberer im zweiten Raum im zweiten Level hat die selbe Textur wie der Held. Das sieht nicht besonders gelungen aus und könnte bei den Studis zu Verwirrung führen. 
Dieser PR behebt das Problem und weist dem Zauberer eine Orc-Schamanen-Textur zu.
closes #1516
=> Dojo: ändere Textur des Zauberers in Level 2 (Pattern-Abfrage)

dojo-dungeon/src/dojo/rooms/rooms/riddle/Fragen_Pattern.java
Bei der Pattern-Aufgabe in Level 2 sollen die Studierenden ihre Antwort als String eingeben, der dann gegen eine vorgegebene Lösung verglichen wird. 
Um die Studierenden nicht zu frustrieren, stellt dieser PR den Vergleich auf einen Match mit RegExp um. Dadurch werden leichte Variationen in der Antwort noch als korrekt erkannt. Beispiel: Gesucht ist "Foo". Durch den Regexp würden dann "Foo", "foo", "Foo Pattern", "Foo-Pattern", "Foomuster", ... noch als korrekt erkannt.
closes #1517 closes #1520
=> Dojo: erlaube Toleranzen bei String-Vergleichen Lösung vs. Antwort (Level 2, Pattern-Abfrage)

.github/dependabot.yml
add dependabot configuration for blockly sub-project (npm)
=> Dependabot: add blockly sub-project

game/src/core/Game.java, game/src/core/systems/CameraSystem.java
Das Problem war, dass Dialoge nicht im Zentrum des Bildschirms erscheinen, wenn die Fenstergröße verändert wird. Dies lag daran, dass die Viewports von `Game` verwendet werden, welche nur die PreRun-Konfiguration lesen und nicht die aktuelle Größe der Gdx-App.
- `Game.java`: Methoden `windowWidth` und `windowHeight` verwenden jetzt Gdx anstatt PreRunConfiguration.
- `CameraSystem.java`: Beibehaltung der PreRunConfiguration in `viewportWidth` und `viewportHeight`, um denselben Zoom zu gewährleisten.
=> Core: Fix dialog centering issue on window resize

game/src/core/Game.java
Das Problem war, dass die Methode `entityAtTile` einen NullPointerException warf, wenn das übergebene Tile `null` war. Dies wird nun behoben, indem ein leerer Stream zurückgegeben wird, falls das Tile `null` ist. Dies macht die Methode benutzerfreundlicher und weniger fehleranfällig, da sie vorhersehbarer auf ungültige Eingaben reagiert.
- `Game.java`: Check hinzugefügt, ob das gegebene Tile null ist, falls ja, wird ein leerer Stream zurückgegeben.
=> Core: Fixed nullpointer in `entityAtTile`

game/src/core/components/DrawComponent.java, game/src/core/level/Tile.java, game/src/core/systems/DrawSystem.java, game/src/core/systems/LevelSystem.java, game/src/core/utils/components/draw/Painter.java, game/src/core/utils/components/draw/PainterConfig.java, game/test/core/level/TileLevelAPITest.java
Das Problem war, dass es keine Möglichkeit gab, die Sichtbarkeit von Entities und Tiles zu steuern oder sie einzufärben. Dies machte es schwierig, bestimmte Objekte auszublenden oder hervorzuheben. Jetzt können Entities und Tiles eine Sichtbarkeit und Tönung haben.
- `DrawComponent.java`, `Tile.java`: Sichtbarkeits- und Tönungsfunktionen hinzugefügt.
- `DrawSystem.java`: Überprüfung der Sichtbarkeit und Anwendung der Tönung beim Rendern von Entities. Entities werden nur gerendert, wenn das Tile, auf dem sie stehen, und sie selbst sichtbar sind.
- `LevelSystem.java`, `Painter.java` und `PainterConfig.java`: Unterstützung für Tönung hinzugefügt.
- Standard-Tönung ist -1 (keine Tönung). Alternativ könnte auch 0xFFFFFFFF (weiß, also keine sichtbare Tönung) verwendet werden
- Tests angepasst …
=> Core: Add visibility and tinting options for entities and tiles

dungeon/src/contrib/entities/HeroFactory.java, dungeon/src/contrib/utils/components/skill/DamageProjectile.java, game/src/core/components/VelocityComponent.java, game/src/core/systems/VelocitySystem.java
Ich habe eine Möglichkeit hinzugefügt, das Entitäten wie z.B. Projektile offene Pit-Tiles betreten können.
- `HeroFactory.java`: VelocityComponent für den Helden so angepasst, dass er in Pit-Tiles fallen kann.
- `DamageProjectile.java`: VelocityComponent für Projektile so angepasst, dass sie über Pit-Tiles fliegen können.
- `VelocityComponent.java`: Neue Eigenschaft `canEnterOpenPits` hinzugefügt, um zu bestimmen, ob eine Entität offene Pit-Tiles betreten kann.
- `VelocitySystem.java`: Überprüfung hinzugefügt, ob eine Entität Pit-Tiles betreten kann.
=> Core: Add support for interaction of entities with tile pits

game/src/core/level/utils/Coordinate.java, game/src/core/utils/Point.java
Ich habe ein paar Utils-Methoden zu `Point` und `Coordinate` hinzugefügt, um die Vollständigkeit zu erhöhen und als Debug-Hilfe später zu dienen. Das sollte die Benutzerfreundlichkeit etwas verbesseren für diese Klassen.
- `Coordinate.java`: Methoden `toCenteredPoint`, `toString` und `distance` hinzugefügt.
- `toCenteredPoint`: Konvertiert eine `Coordinate` in einen zentrierten Punkt des Tiles.
- `distance`: Berechnet die Manhattan-Distanz zwischen zwei `Coordinates`.
- `Point.java`: Methoden `toString` und `distance` hinzugefügt.
- `distance`: Berechnet die euklidische Distanz zwischen zwei `Points`.
=> Core: add utility methods to Point and Coordinate

game/src/core/level/elements/tile/ExitTile.java, game/src/core/systems/LevelSystem.java, game/test/core/level/TileLevelAPITest.java
Ich habe hinzugefügt, dass `ExitTiles` jetzt offen und geschlossen sein können. Da es keine Textur für geschlossen gibt, werden sie rot eingefärbt. Wenn sie geschlossen sind, teleportieren sie nicht zum nächsten Level. Außerdem habe ich den Test angepasst, sodass der Exit dort offen ist. Standardmäßig ist der Exit offen. Das LevelSystem wurde überarbeitet, um eine onEndTile-Callback-Funktion hinzuzufügen. Standardmäßig wird das nächste Level geladen, und die Callback-Funktion wird nur aufgerufen, wenn das Exit-Tile offen ist. `isTilePitAndOpen` wurde hinzugefügt, um offene Pits nicht zu rendern, da die "Textur" einfach leer sein soll. Dies kann später angepasst bzw. wieder gelöscht werden, falls eine Textur dafür vorhanden ist. `isOnDoor` wurde überarbeitet und verwendet keine Schleife …
=> Core: add open/close functionality to exit tiles

dungeon/src/contrib/entities/HeroFactory.java, dungeon/src/starter/Starter.java, game/src/core/components/PlayerComponent.java, game/src/core/systems/PlayerSystem.java
Ich habe `pauseable` in `InputData` für das `PlayerSystem` invertiert, sodass es mehr Sinn macht. Die Defaults wurden ebenfalls gedreht, sodass sich in der Logik nichts ändern sollte, es sei denn, der Wert wurde explizit gesetzt, ich habe sonst alle gesetzten Werte entsprechend angepasst. Zusätzlich wurde Mausunterstützung in der `execute`-Methode des `PlayerSystem` hinzugefügt. `InputData` wurde nach unten verschoben, da Unterklassen am Ende der Klasse stehen sollten.
- `HeroFactory.java`: Aufruf geändert, jetzt auf eine `registerCallback` verwiesen um die neuen default Werte zu verwenden.
- `PlayerComponent.java`: `pauseable` invertiert und `InputData` nach unten verschoben.
- `PlayerSystem.java`: Mausunterstützung in der `execute` Methode hinzugefügt und `pauseable` Logik angepasst.
=> Core: add mouse support

game/src/core/level/Tile.java, game/src/core/level/elements/ILevel.java, game/src/core/level/elements/tile/DoorTile.java, game/src/core/level/utils/LevelElement.java
Ich habe ein Attribut `canSeeThrough` zu Tiles hinzugefügt, das angibt, ob ein Tile durchsichtig ist oder nicht. Dies kann z.B. für ein Fog-of-War verwendet werden. Türen haben diese Eigenschaft überschrieben bekommen und sind nur durchsichtig, wenn sie offen sind. Außerdem habe ich die `toString` Methode zu Tiles und Doors hinzugefügt, um das Debuggen zu erleichtern. Die Methode `changeTileElementType` wurde angepasst, um auch Parameter für das AI-Pathfinding, die Tint-Farbe und die Sichtbarkeit zu übernehmen, wenn das Element geändert wird.
- `Tile.java`: Neue Methode `canSeeThrough` hinzugefügt und `toString` Methode erweitert.
- `ILevel.java`: Methode `changeTileElementType` angepasst, um Pfadfindungs-Parameter, Tint-Farbe und Sichtbarkeit zu übernehmen.
- `DoorTile.java`: …
=> Core: allow Tile to be transparent

dojo-dungeon/src/dojo/rooms/rooms/boss/Fragen_Lambda.java, dungeon/src/task/Task.java, dungeon/src/task/TaskContent.java, dungeon/src/task/game/hud/QuizDialogDesign.java, dungeon/src/task/tasktype/Quiz.java
Ich habe die Methoden angepasst, sodass man mehrere Inhalte (Contents) gleichzeitig zu einer Aufgabe (Task) oder einem Quiz hinzufügen kann. Zudem wurde ein Tippfehler behoben. Im Dojo-Dungeon wurden die neuen Signaturen bereits übernommen, was den Code lesbarer und kompakter macht.
- `Task.java`: `addContent` Methode so geändert, dass mehrere Inhalte gleichzeitig hinzugefügt werden können.
- `TaskContent.java`: Dokumentation angepasst, um die neue `addContent(TaskContent...)` Methode zu reflektieren.
- `Quiz.java`: `addAnswer` Methode so geändert, dass mehrere Antworten gleichzeitig hinzugefügt werden können.
- `QuizDialogDesign.java`: Tippfehler in der Variablen `QUIZ_MESSAGE_TASK` korrigiert.
- `Fragen_Lambda.java` im Dojo-Dungeon: Code auf neue Signatur geändert, um die Lesbarkeit zu …
=> Dungeon: support multiple contents simultaneously in Task and Quiz

dungeon/src/contrib/systems/IdleSoundSystem.java
Ich habe einen Filter hinzugefügt, der dafür sorgt, dass nur nahegelegene Monster Geräusche machen, da aktuell alle Monster zu hören sind und das die Spieler verwirren kann.
- `IdleSoundSystem.java`: Filter hinzugefügt, um nur nahegelegene Entities Geräusche machen zu lassen.
- `DISTANCE_THRESHOLD` definiert, um die maximale Distanz festzulegen, innerhalb derer Geräusche gehört werden können.
- Methode `onlyKeepNearbyEntities` hinzugefügt, die prüft, ob eine Entity innerhalb der festgelegten Distanz zum Helden ist.
=> Dungeon: mute distant entities via proximity filter (IdleSoundSystem)

dungeon/src/contrib/components/HealthComponent.java
Ich habe einen `onHit` Callback für Entities hinzugefügt und den `onDeath` Setter öffentlich gemacht, um ihn ändern zu können.
- `HealthComponent.java`: 
- `onHit` hinzugefügt, um eine Funktion auszuführen, wenn eine Entity Schaden erhält.
- `onDeath` Setter öffentlich gemacht, um es zu erlauben die Funktion zu ändern, die beim Tod einer Entity ausgeführt wird.
- `receiveHit` Methode angepasst, um den `onHit` Callback aufzurufen.
=> Dungeon: add onHit callback to HealthComponent

dungeon/src/contrib/crafting/Crafting.java
Dieser Pull Request erweitert das Crafting-System, um Parameter für Crafting-Zutaten zu unterstützen. Das ermöglicht die Erstellung von komplexeren Gegenständen durch die Verwendung von Konstruktoren mit Parametern.
- `Crafting.java`: Logik hinzugefügt, um Parameter für Crafting-Zutaten zu verarbeiten. Wenn ein `item` Parameter hat, wird der passende Konstruktor gesucht und mit diesen Parametern aufgerufen. Verbesserte Fehlerbehandlung für fehlende Konstruktoren.
Die dient als Ergänzung zu #1558.
=> Dungeon: Add support for parameterized crafting ingredients

dungeon/src/contrib/components/SignComponent.java, dungeon/src/contrib/entities/SignFactory.java, dungeon/src/contrib/hud/DialogUtils.java, dungeon/src/task/game/hud/UIAnswerCallback.java
Der Pull Request fügt Schilder und Utility-Methoden hinzu, die es erlaubt Text-Popups und Fragen im Spiel anzuzeigen. 
- **SignComponent.java**:
- Klasse `SignComponent` hinzugefügt, die ein Schild mit Titel und Text darstellt.
- Konstruktoren für das Setzen von Titel und Text, mit Behandlung von Leerzeichen.
- Methoden zum Abrufen und Setzen von Titel und Text und zum Anzeigen eines Dialogs.
- **SignFactory.java**:
- Klasse `SignFactory` hinzugefügt, um Schilder im Spiel zu erstellen.
- Methoden `createSign(Text, Pos)` und `createSign(Text, Titel, Pos, onInteract)` um Schilder mit Standard- oder benutzerdefinierten Titeln und `onInteract` zu erstellen.
- Verwendet `SignComponent` für Schildeigenschaften und `InteractionComponent` für Interaktionen.
- **DialogUtils.java**:
- Die Klasse …
=> Dungeon: Add signs and util-methods for dialogs

dungeon/src/contrib/systems/AISystem.java, dungeon/src/contrib/systems/CollisionSystem.java, dungeon/src/contrib/systems/HealthBarSystem.java, dungeon/src/contrib/systems/HealthSystem.java, dungeon/src/contrib/systems/HudSystem.java, dungeon/src/contrib/systems/IdleSoundSystem.java, dungeon/src/contrib/systems/ProjectileSystem.java, dungeon/src/contrib/systems/SpikeSystem.java, game/src/core/System.java, game/src/core/systems/CameraSystem.java, game/src/core/systems/DrawSystem.java, game/src/core/systems/LevelSystem.java, game/src/core/systems/PlayerSystem.java, game/src/core/systems/PositionSystem.java, game/src/core/systems/VelocitySystem.java, game/test/core/SystemTest.java
**fixes #1553**
Überarbeitet den Umgang mit dem Entity-Stream in `System#execute`-Methoden, um eine bessere Code-Lesbarkeit zu erreichen.
Anmerkung: Durch die gemachten Änderungen kommt es zu Redundanz im Hinblick auf die Filterregeln. Diese werden weiterhin im System gespeichert, können jetzt aber optional als Parameter eigenständig verwendet werden. Wenn sich für das eigenständige Verwenden als Parameter entschieden wird, muss bei Änderungen an den Filtern darauf geachtet werden, diese überall einzutragen (im Konstruktor UND in der Execute-Funktion).
Für leichtere Bedienung und Abwärtskompatibilität ist die alte Variante aber weiterhin verfügbar.
Änderungen im Überblick:
* Umbenennung der Methode `System#entityStream` in `System#filteredEntityStream`
* Hinzufügen von parametisierten …
=> Dungeon: improve readability by replacing implicit filtering (entityStream) with explicit filtering (filteredEntityStream, both System)

game/src/core/systems/CameraSystem.java
see https://github.com/Dungeon-CampusMinden/Dungeon/pull/1564#discussion_r1660951335
```java
public void execute() {
if (filteredEntityStream(CameraComponent.class, PositionComponent.class).findAny().isEmpty())
focus();
else filteredEntityStream().forEach(this::focus);
```
Hier wird der Stream bis zu 2x gebaut, was (a) aufwändig und (b) schlecht lesbar ist.
Zudem wird bei Vorliegen eines oder mehrerer Entitäten mit einer `CameraComponent` für **alle** Entitäten in einer nicht vorhersehbaren Reihenfolge die Methode `focus(e)` aufgerufen - die zuletzt iterierte Entität "gewinnt", da es nur eine Kamera (-position) gibt.
Refactoring: Dies wird durch **einmaliges Erzeugen des Streams** und durch Nutzen einer **zufälligen Entität mit `CameraComponent`** zum Setzen der Kamera abgelöst.
Keine …
=> Dungeon: avoid building the same stream more than once (refactoring, CameraComponent)

dungeon/src/contrib/utils/components/interaction/DropItemsInteraction.java
Dieser PR verbessert die Logik von Item-Drops aus Inventaren.
Die Änderungen führen eine robustere Methode zum Finden geeigneter Ablagepositionen ein und implementieren einen Fallback-Mechanismus für Fälle, in denen keine geeignete Position in der Nähe gefunden werden kann.
- **DropItemsInteraction.java**:
- Einführung einer neuen Konstante `MAX_ITEM_DROP_RADIUS` zur Begrenzung des Suchradius für Ablagepositionen.
- Implementierung der Methode `tryDropItem()`, die versucht, ein Item in einem zufälligen zugänglichen Feld innerhalb eines bestimmten Radius abzulegen.
- Neue Methode `dropItemAtHeroPosition()` als Fallback-Lösung.
- Aktualisierung der `accept()`-Methode zur Verwendung der neuen Logik.
- Entfernung nicht mehr benötigter Importe und Hilfsmethoden.
Diese Änderungen wurden …
=> Dungeon: improve item dropping logic, introduce fallback to hero's position

dungeon/src/contrib/entities/MonsterFactory.java
Dieser PR führt Verbesserungen in der `MonsterFactory`-Klasse ein, um die Erstellung von Monstern flexibler zu gestalten und die Sound-Logik zu optimieren.
- **MonsterFactory.java**:
- Neue `buildMonster`-Methode zur parametrisierten Monster-Erstellung.
- Überarbeitung der `randomMonster`-Methode zur Nutzung von `buildMonster`.
- Einführung von `randomMonsterDeathSound` und `randomMonsterIdleSound` Methoden.
- Implementierung von `playDeathSoundIfNearby` für distanzbasierte Soundwiedergabe.
- Aktualisierung der Item-Drop-Logik mit konfigurierbarer Wahrscheinlichkeit.
- Entfernung hartcodierter Werte und Einführung von Konstanten.
Diese Änderungen wurden eingeführt, um die Flexibilität bei der Monster-Erstellung zu erhöhen. Die neue `buildMonster`-Methode ermöglicht es, Monster mit …
=> Dungeon: enhance monster creation flexibility and death sound logic (MonsterFactory)

dungeon/src/contrib/components/AIComponent.java, dungeon/src/contrib/components/SpikyComponent.java
Dieser PR führt einen Aktivierungszustand für die `AIComponent `und `SpikyComponent` ein, um eine flexiblere Kontrolle über das Verhalten von Entitäten zu ermöglichen.
- **AIComponent.java**:
- Hinzufügung eines `active` Feldes mit Getter- und Setter-Methoden.
- Anpassung der `shouldFight()` und `idleBehavior()` Methoden, um den Aktivierungszustand zu berücksichtigen.
- **SpikyComponent.java**:
- Hinzufügung eines `active` Feldes mit Getter- und Setter-Methoden.
- Anpassung der `isActive()` Methode, um den neuen Aktivierungszustand zu berücksichtigen.
Diese Änderungen wurden eingeführt, um eine Kontrolle über das Verhalten von Entitäten zu ermöglichen, ohne die Komponenten entfernen zu müssen. Dies kann besonders nützlich sein für temporäre Deaktivierungen, beispielsweise während …
=> Dungeon: Add activation state to AI and Spiky components

dungeon/src/contrib/utils/components/skill/DamageProjectile.java, dungeon/src/contrib/utils/components/skill/FireballSkill.java, dungeon/src/contrib/utils/components/skill/Skill.java
Dieser PR führt neue Funktionalitäten für Projektile und Skills ein, um mehr Flexibilität und Kontrolle zu ermöglichen.
- **DamageProjectile.java**:
- Hinzufügen eines Namens für Projektile
- Implementierung einer Ignore-Liste für Entities, die nicht vom Projektil getroffen werden sollen
- Einführung von Tint-Farben für Projektile
- Hinzufügen eines Callbacks für Treffer auf Entities, der vor dem Schaden ausgeführt wird
- Neue Methoden zum Verwalten der Ignore-Liste und Tint-Farbe
- **FireballSkill.java**:
- Anpassung des Konstruktors zur Unterstützung der neuen `DamageProjectile`-Funktionalitäten
- Konstante Werte wie Projektilgeschwindigkeit, Schaden und Reichweite wurde umbenannt.
- Neuer Konstruktor für benutzerdefinierte Werte
- **Skill.java**:
- Hinzufügen von Methoden zum Setzen …
=> Dungeon: Enhance Projectile and Skill Logic

dungeon/src/contrib/systems/SpikeSystem.java
see https://github.com/Dungeon-CampusMinden/Dungeon/pull/1564#discussion_r1660926970
In 
```java
public void execute() {
filteredEntityStream(SpikyComponent.class)
.forEach(e -> e.fetch(SpikyComponent.class).orElseThrow().reduceCoolDown());
}
```
wird ein Stream aller Entitäten mit einer `SpikyComponent` vom `System` angefordert. Bei der Iteration über diese Entitäten wird dann (a) die `SpikyComponent` extrahiert, (b) eine Exception geworfen im Nichtvorhandensein-Fall, und (c) auf der Component eine Methode aufgerufen.
Dies ist aus zwei Gründen problematisch: Zum werden mehrere Operationen in die `forEach`-Schleife verpackt, und zum anderen sollte man keine Exceptions in einer Stream-Operation werfen. (OK, das dürfte hier in der Realität auch nie passieren, da wir ja vorher exakt nach der …
=> Dungeon: do not throw exceptions in stream operations (refactoring, SpikeSystem)

game/src/core/components/DrawComponent.java
Die Methode `queueAnimation` hat eine Überladung, mit der man Animationen in die Warteschlange stellen kann, ohne explizit eine Dauer anzugeben.
Aus irgendeinem (nicht näher erklärten) Grund wurde in diesem Fall die Dauer auf **1 Frame** gesetzt statt auf die intrinsische Dauer der jeweiligen Animation. 
Dieser PR behebt das und nutzt die intrinsische Dauer einer Animation, sofern keine explizite Dauer angegeben wird. Dadurch vereinfacht sich das Handling in `HealthSystem` signifikant.
=> Dungeon: allow intrinsic duration when enqueuing an animation as next animation (DrawComponent)

dungeon/src/contrib/systems/HealthSystem.java
Dieser PR behebt das Problem, dass im `HealthSystem` bei der Iteration über den Entity-Stream bereits Entitäten aus dem Game und damit der Basisdatenstruktur für den Stream selbst gelöscht werden. 
Eine Modifikation des Streams in einer Stream-Operation ist i.d.R. nicht zulässig und führt zu undefiniertem Verhalten. Nach dem Mergen dieses PRs wird zunächst über die gefilterten Entitäten iteriert und wie bisher das Datenobjekt gebaut. Danach werden alle Objekte gefiltert, ob die Entität noch lebendig ist oder nicht, und der Stream damit abgeschlossen. Die lebendigen Entitäten werden danach separat behandelt, dito die nicht mehr lebendigen Entitäten. Das Löschen in Game sollte nun gefahrlos sein, weil wir uns nicht mehr in der Iteration der Ursprungsdatenstruktur befinden.
**Erst nach #1580 …
=> Dungeon: do not modify the entity stream whilst streaming (HealthSystem)

dungeon/build.gradle
Im Dungeon-Projekt wurde der Ordner 'build/generated-src/antlr/main/' als zusätzlicher Java-Sourceordner konfiguriert. Das ist für die IDE ein Problem, da der Subpfad 'antlr/main/' das Package darstellt - das (generierte) Package 'antlr.main' kann also nicht gefunden werden.
Dies fällt auf, wenn man in der IDE eine der DSL-Klassen öffnet, die mit dem generierten Parser zusammenhängen - es ist alles "rot".
Dieser PR korrigiert dies und konfiguriert nur den Oberordner 'build/generated-src/' als weiteren Java-Sourceordner. Damit findet die IDE darunter das generierte Package 'antlr/main/'.
Warum ist da bisher noch niemand drüber gestolpert?
=> Gradle: fix ANTLR configuration

dungeon/src/contrib/components/InventoryComponent.java
Dieser PR führt eine neue Methode in der InventoryComponent-Klasse ein, die es ermöglicht, das Vorhandensein eines bestimmten Item-Typs im Inventar zu überprüfen.
- **InventoryComponent.java**:
- Hinzufügen der Methode `hasItem(Class<? extends Item> klass)`
- Überprüft, ob das Inventar ein Item der angegebenen Klasse enthält
- Rückgabewert ist ein Boolean (true, wenn ein Item des Typs vorhanden ist, sonst false)
Für zukünftige Erweiterungen könnte auch eine Methode in Betracht gezogen werden, die den Index des ersten gefundenen Items des angegebenen Typs zurückgibt. Dies würde die Implementierung von Hotkey-Funktionalitäten für spezifische Item-Typen erleichtern.
=> Dungeon: Add method to check for item type in inventory

game/src/core/Entity.java
Dieser PR fügt einen Getter für den Namen eines Entity hinzu, um die Konsistenz und Vollständigkeit der Entity-Klasse zu verbessern.
* `Entity.java`: Hinzufügen der Methode `name()` diese gibt den Name des Entity zurück
Diese Methode wird später im DevDungeon benötigt um Entities wieder zu finden.
=> Core: Add getter for Entity name

game/src/core/components/DrawComponent.java
Dieser PR fügt eine neue Methode zur `DrawComponent` hinzu, die es ermöglicht, Animationen anhand ihres Namens auszuwählen, anstatt den Pfad zu verwenden.
- **DrawComponent.java**:
- Hinzufügen einer neuen `currentAnimation(String animationName)` Methode
- Diese Methode ermöglicht es, die aktuelle Animation durch Angabe des Animationsnamens zu setzen
Diese Änderung bietet eine alternative und in manchen Fällen intuitivere Möglichkeit, Animationen auszuwählen. Sie ist besonders nützlich in Kontexten, in denen der Name der Animation bekannt ist, aber nicht unbedingt der vollständige Pfad.
=> Dungeon: Add animation selection by name in DrawComponent

dungeon/src/contrib/systems/HealthSystem.java, dungeon/src/contrib/utils/components/health/IHealthObserver.java
Dieser PR führt ein Observer-System für Gesundheitsereignisse ein, das es ermöglicht, auf Treffer- und Todesereignisse zu reagieren und entsprechende Methoden auszuführen.
- **HealthSystem.java**:
- Implementierung einer Liste von IHealthObserver-Objekten
- Hinzufügen von Methoden zum Registrieren und Entfernen von Observern
- Benachrichtigung der Observer bei Schadens- und Todesereignissen
- HSData wurde auf public angepasst sodass es vom Interface verwendet werden kann
- **IHealthObserver.java**:
- Definition des IHealthObserver-Interfaces mit der Methode onHealthEvent
- Einführung des HealthEvent-Enums für DAMAGE und DEATH Ereignisse
=> Dungeon: Add Health Event Observer System

dungeon/src/contrib/utils/components/ai/fight/MeleeAI.java, dungeon/src/contrib/utils/components/ai/fight/RangeAI.java, dungeon/src/contrib/utils/components/ai/transition/RangeTransition.java, dungeon/src/contrib/utils/components/skill/ISkillUser.java
Dieser PR bringt zwei Änderungen mit sich, der die Anpassungsfähigkeit von AIs verbessert. Einmal der `stayInFightMode` Boolean-Parameter für die `RangeTransition`-AI, der es der AI ermöglicht, im Kampfmodus zu bleiben, auch wenn der Held wegrennt. Und ein neues Interface `ISkillUser`, das es ermöglicht, die Skills von `RangeAI` und `MeleeAI` nachträglich zu ändern.
- **MeleeAI.java** & **RangeAI.java**:
- Interface `ISkillUser` hinzugefügt und implementiert.
- Anpassung der Skill-Nutzung zur Verwendung der `useSkill` Methode.
- **RangeTransition.java**:
- Hinzufügen des `stayInFightMode` Boolean-Parameters zu einen neuen Konstruktor.
- Der bestehende Konstruktor setzt den Wert standardgemäß auf `false`.
- Implementierung der Logik, die die AI im Kampfmodus hält, wenn der Spieler zuvor in …
=> Dungeon: Add stayInFightMode to RangeTransition and ISkillUser interface for dynamic skill assignment

dungeon/src/contrib/entities/HeroFactory.java
Ich habe einen Bug behoben, bei dem das Mausmovement-Pathfinding nicht gecleart wurde, wenn man sich manuell bewegt hat. Dies führte dazu, dass man, wenn man sich nicht zum letzten Path-Node bewegt hat, vom Pathfinding wieder weggesteuert wurde.
- **HeroFactory.java**:
- Path wird vom `PathComponent` gelöscht wenn man sich bewegt.
=> Dungeon: clear mouse movement pathfinding upon manual movement (bug fix)

dungeon/src/contrib/systems/HealthBarSystem.java
Ich habe das System so angepasst, dass die HealthBar nur sichtbar ist, wenn das Entity auch sichtbar ist. Zusätzlich habe ich den überflüssigen `remove`-Aufruf entfernt, der ausgeführt wurde, wenn die HP 0 oder weniger sind, da bereits oben `this.onEntityRemove = (x) -> healthBarMapping.remove(x.id()).remove();` gesetzt wird, sodass es schon gelöscht wird wenn das Entity gelöscht wird.
- **HealthBarSystem.java**:
- Hinzufügen einer Abfrage, um die Sichtbarkeit der HealthBar nur dann zu setzen, wenn die Entität sichtbar ist und Gesundheitspunkte verloren hat.
- Entfernen des überflüssigen `remove`-Aufrufs.
- Hinzufügen des `DrawComponent` zu `EnemyData` für die Sichtbarkeitsprüfung.
=> Dungeon: Adjust HealthBarSystem to show health bar only when entity is visible

dungeon/src/task/tasktype/Quiz.java
Ich habe eine Methode hinzugefügt, die die Reihenfolge der Antwortmöglichkeiten in einem Quiz zufällig verändert. Dadurch kann man nicht einfach die gleiche Position anklicken, sondern muss sich den Inhalt merken. Die Indizes der korrekten Antworten werden entsprechend angepasst.
- **Quiz.java**:
- Hinzufügen der Methode `shuffleAnswers`, um die Reihenfolge der Antworten zufällig zu verändern und die Indizes der korrekten Antworten zu aktualisieren.
Diese Änderungen wurden vorgenommen, um sicherzustellen, dass die Teilnehmer eines Quizzes sich die Inhalte der Antworten merken müssen, anstatt einfach eine feste Position anzuklicken. Jedoch muss die neue Methode vorher aufgerufen werden, falls man die Reihenfolge zufällig verändern will.
=> Dungeon: allow to shuffle quiz answers

dungeon/src/contrib/entities/MiscFactory.java, dungeon/src/contrib/entities/MonsterFactory.java, dungeon/src/contrib/item/HealthPotionType.java, dungeon/src/contrib/item/Item.java, dungeon/src/contrib/utils/components/item/ItemGenerator.java
Ich habe den `ItemGenerator` angepasst, sodass man eigene Logik implementieren kann, da er nicht mehr statisch ist, sondern die Klassen, die ihn verwenden, einfach eine öffentliche statische Instanz davon haben. Der Generator kann jetzt per `addItem` gefüllt werden, standardmäßig ist er jedoch mit allen Items gefüllt. 
Zusätzlich sind alle registrierten Items jetzt per Getter und Setter in `Item` modifizierbar. Und die Methode `getWeightedRandomHealthPotionType` wurde in das Enum `HealthPotionType` verschoben.
- **MiscFactory.java** & **MonsterFactory.java**:
- Hinzufügen einer statischen Instanz von `ItemGenerator`, um zufällige Items zu generieren.
- **HealthPotionType.java**:
- Hinzufügen einer Methode `randomType`, die eine zufällige `HealthPotionType` basierend auf Gewichtungen …
=> Dungeon: add weighted random selection to ItemGenerator

dungeon/src/contrib/entities/HeroFactory.java, dungeon/src/contrib/entities/MonsterFactory.java, dungeon/src/contrib/utils/components/skill/FireballSkill.java
Als letzte Vorbereitung vor dem Mergen des DevDungeon habe ich die Werte für HP und Schaden angepasst:
- HeroFactory.java:
- HERO_HP von 100 auf 25 reduziert
- MonsterFactory.java:
- MAX_MONSTER_HEALTH von 50 auf 20 reduziert
- FireballSkill.java:
- DEFAULT_DAMAGE_AMOUNT von 5 auf 2 reduziert (dieser Wert wird für Monster Feuerbälle verwendet)
Monster und Held verursachen jetzt gleich viel Schaden und die Monster haben nun maximal weniger HP als der Held. Dies dient als Grundlage für den DevDungeon und als gute Vorlage für andere Spiele.
=> Dungeon: Balanced Hero and Monster Stats

devDungeon/src/level/utils/DungeonSaver.java, devDungeon/src/systems/FallingSystem.java, game/src/core/Game.java, game/src/core/game/GameLoop.java, game/src/core/level/elements/ILevel.java, game/src/core/level/utils/LevelUtils.java, game/src/core/systems/PositionSystem.java, game/test/core/level/TileLevelTest.java, game/test/core/systems/CameraSystemTest.java, game/test/core/systems/PositionSystemTest.java
Fixes #1575
Konkret wird hier:
- Das erste Level wird nun durch ein `LevelSystem#execute` im Setup geladen. Damit entfällt ein null Check zur Laufzeit
- Das rekursive Verhalten beim Suchen nach freien Tiles entfernt und durch BFS ersetzt
- Einige API-Methoden zum Finden von Tiles hinzugefügt (haben sich aus dem Punkt oben ergeben).
- `Game#allTiles` gibt alle Tiles als Set zurück
- `Game#allTiles(LevelElement)` gibt alle Tiles des aktuellen Levels zurück
- ` Game#allTiles(Predicate<Tile>)` gibt alle Tiles  des aktuellen Levels zurück dessen Predicate Ergebnis True ist. 
- `Game#freeTile()` gibt ein freies Tile zurück (als Optional)
- `Game#allFreeTiles()`gibt ein Set alle Freien Tiles zurück  
- `Game#freePostion()` gibt die Position eines freien Tile zurück (als Optional)
- …
=> Dungeon: improve handling of tiles in game API

README.md
Fügt ein GIF hinzu, um die Funktion von Blockly zu zeigen.
Ersetzt den statischen Screenshot in der Readme
=> Readme: add a gif for blockly

blockly/frontend/src/blocks/dungeon.ts
changed names of field_number fields of Movement blocks to "amount" #1673 
fixes #1673
=> Blockly: fix movement blocks with integrated counter

blockly/src/client/Client.java
closes #1686 
Dieser PR sollte jetzt erst den Server beenden wenn auch die Game Loop zu Ende ist.
=> Blockly: Fix server instantly stopping

blockly/src/client/Client.java, blockly/src/client/KeyboardConfig.java, blockly/src/entities/VariableHUD.java
Ich habe eine Funktion eingebaut mit dem man das `VariableHUD` unsichtbar und wieder sichbar machen kann per Tastendruck.
Die Tastenbelegung ist: **B**
Änderungen:
1. Der Ctor Parameter für das `VariableHUD` ist nicht mehr Optional, da das HUD die Stage braucht.
2. Das `VariableHUD` speichert nicht mehr die Stage, sondern ein `Table`. Hier dient `Table` als Gruppe von Objekten im UI, es wird `Table` statt `Group` verwendet um dynamisch die Größe zu ändern per `table.setFillParent(true)` . Groups bzw. Tables haben das Field `visible` um die Actors (UI-Elemente) auszublenden. Dieses Field ist per Getter und Setter im `VariableHUD` veränderbar.
3. Es wurde ein neue `KeyboardConfig` für Blockly erstellt. Diese hat den neuen Keybind für das Togglen des `VariableHUD`. Die Logik dafür ist im …
=> Blockly: Toggle VariableHUD on Keystroke

blockly/src/entities/VariableHUD.java
Ich habe den Memory Leak im `VariableHUD` behoben. Das Problem lag darin, dass bei jeder Erstellung des HUDs mehrfach identische `BitmapFont` Instanzen (sowie die dazugehörige `LabelStyle`) neu erstellt wurden, anstatt diese als statischen Wert zu einmalig zu speichern. Das HUD verbraucht jetzt nur noch circa 10MB Speicher, statt 100-300MB
Änderungen:
1. `BitmapFont` und `LabelStyle` werden nun als statische Instanzen genutzt, um mehrfaches Allozieren von Memory zu verhindern.
closes #1706
=> Blockly: Fix memory leak in VariableHUD

blockly/src/entities/VariableHUD.java
Es wurde behoben, dass das HUD beim Maximieren des Spiels nicht korrekt neu skaliert wurde. Der Fehler lag darin, dass der `hudContainer` nicht an die neue Größe der `stage ` angepasst wurde. Mit dieser Änderung wird der Container nun mit der Stage skaliert, sodass das HUD ordnungsgemäß dargestellt wird.
Zusätzlich habe ich die Anzahl der im HUD erstellten Images korrigiert: Statt fälschlicherweise 2000 werden nun nur noch 84 Bilder erzeugt. 
Änderungen:
1. `hudContainer` wird dynamisch auf die aktuelle Stage-Größe angepasst.
2. Reduzierung der im HUD erstellten Images von ~2000 auf 84.
3. Konsistente Skalierung des HUDs durch Anpassung des Containers an die Stage.
fixes #1708
=> Blockly: Fix HUD scaling on maximize

blockly/frontend/src/api/api.ts, blockly/frontend/src/index.ts, blockly/frontend/src/utils/utils.ts
Ich habe die Blockly Alerts (Popups) ersetzt, sodass bei Auftreten eines Codefehlers nun eine spezifische Warnmeldung am betroffenen Block ausgegeben wird – ergänzt durch einen Konsolen-Log. Dadurch wird nicht mehr ein generisches Popup angezeigt, sondern ein zielgerichteter Hinweis zur schnelleren Fehlerfindung.
Änderungen:
1. `console.log` statt Alert verwendet (wo es sinnvoll erscheint), um detaillierte Fehlermeldungen zu dokumentieren.
2. Bei Codefehlern: Der entsprechende Block erhält eine spezifische Warnmeldung (`displayErrorOnBlock`)
3. Die sleep-Methode wurde in eine eigene Utils-Datei ausgelagert.
4. Reduzierung von Code-Duplizierung durch Auslagerung von Methoden in der Index-Datei (`handleResponse`)
closes #1676
=> Blockly: Enhance alert popup with console log and improved error messaging

.github/workflows/github_ci.yml, blockly/frontend/.editorconfig, blockly/frontend/eslint.config.js, blockly/frontend/package-lock.json, blockly/frontend/package.json, blockly/frontend/src/generators/java.ts, blockly/frontend/src/index.ts
Ich habe den Coding Style im Typescript-Projekt an die Standard-ESLint-Richtlinien angepasst. Dafür wurde ESLint eingerichtet und die .editorconfig entsprechend aktualisiert. Mit diesen Änderungen wurden einmal alle Linting-Fehler im Code behoben. Zusätzlich wurde eine GitHub Action integriert, die bei jedem PR das Formatting automatisch testet.
Änderungen:
1. Einrichtung von ESLint mit den empfohlenen ESLint-Coding Style-Richtlinien.
2. Anpassung der .editorconfig für 2 Indents bei js und ts Files.
3. Integration einer GitHub Action zur automatischen Überprüfung des Formats.
4. Behebung aller bestehenden Linting-Fehler.
closes #1714
=> Typescript: Enforce Default ESLint Coding Style with ESLint and EditorConfig

dungeon/src/contrib/configuration/KeyboardConfig.java, dungeon/src/contrib/entities/HeroFactory.java, dungeon/src/contrib/hud/inventory/InventoryGUI.java
In diesem PR wurde die Maussteuerung erweitert:
- Das Inventar kann nun per Mausrad (mittlere Maustaste) geöffnet und geschlossen werden.
- Items können per Rechtsklick direkt im Inventar verwendet werden. Analog zum Verschieben in einem Cauldron oder einer Kiste.
- In der `Herofactory ` wurde die Logik für das Toggle des Inventars in eine eigene Methode refactored, sodass sie nun auch für die Maussteuerung aufgerufen werden kann.
=> Dungeon: Mouse control for Inventory and Item Usag

blockly/src/server/Server.java
Ich habe die Bewegung des Helden auf ein tilebasiertes System umgestellt. Jetzt bewegt sich der Held pro Befehl genau um ein Tile. Vor jeder Bewegung wird der Held in die Mitte des aktuellen Tiles teleportiert. Dadurch kann die erste Bewegung etwas seltsam aussehen, da der Held initial nicht mittig auf einem Tile gespawnt wird. Danach verläuft die Bewegung jedoch flüssig. Die Umsetzung erfolgte in der `move()` der `Server.java`. Der Held bewegt sich so lange, bis der Zielpunkt (die Mitte des nächsten Tiles) erreicht ist, und stoppt dann.  
closes #1745
=> Blockly: change blockly movement to tile movement

blockly/frontend/eslint.config.js
Ich habe eine neue Linter-Regel `eol-last` hinzugefügt, um sicherzustellen, dass jede `.ts` und `.js` Datei mit einer neuen Zeile endet.  
- `.eslint.config.js`: Regel `eol-last` hinzugefügt.
=> Blockly: Add new linter rule to enforce newline at end of files

game/src/core/components/PositionComponent.java, game/src/core/systems/VelocitySystem.java, game/src/core/utils/components/position/Direction.java
DIeser PR führt die Blickrichtung (`direction_of_view`) im `PositionComponent` hinzu.  
Für Entitäten mit `PositionComponent` und `VelocityComponent` aktualisiert das `VelocitySystem` die Blickrichtung entsprechend der Bewegung.  
Das Feature wird für #1756 #1772  #1760 etc. benötigt
- Außerdem wurde ein Check im `VelocitySystem` vereinfacht: Anstelle der alten Bewegungsgeschwindigkeit als Indikator der Blickrichtung wird jetzt die Blickrichtung verwendet.  
Passt am besten da rein, jede Entität, die irgendwo steht, ist in irgendeine Blickrichtung ausgerichtet.  
Alternativen:  
- Im `VelocityComponent` wäre die Blickrichtung für unbewegliche Entitäten verwehrt geblieben.  
- Eigenes `DirectionComponent` wäre m.M.n. Overkill. Es gibt kein `DirectionSystem` und die `direction_of_view` ist …
=> Core: add direction of view

blockly/frontend/src/blocks/dungeon.ts, blockly/frontend/src/generators/java/skills.ts, blockly/frontend/src/toolbox.ts, blockly/src/server/Server.java, game/src/core/Game.java
Fixes #1779 
Fügt den block `benutzen` ein.
Der Block führt für jede Entität die sich auf dem Tile vor dem Helden (Blickrichtung wird beachtet) und die ein `InteractionComponent` hat, die Interaktion aus.
Ich habs mit Items und Schatztruhen erfolgreich getestet.
Außerdem habe ich in `core` noch zwei Helper-Funktionen eingebaut, um das Tile in einer bestimmten Richtung vom übergebenen Punkt zu bekommen.
=> Blockly: add use block

blockly/src/client/Client.java
Ich habe das `PlayerSystem` innerhalb der `onSetup()` in der `client.java` entfernt, um alle Steuerungen über Maus und Tastatur zu deaktivieren.
Zusätzlich habe ich auf Wunsch von @Flamtky den Keybind des BlocklyHUDs in der `createHero()`  entfernt, da es nicht mehr verwendet wird. 
closes #1747
=> Blockly: Disable Keyboard and Mouse

blockly/frontend/src/blocks/dungeon.ts, blockly/frontend/src/generators/java/skills.ts, blockly/frontend/src/toolbox.ts, blockly/src/server/Server.java, game/src/core/components/PositionComponent.java
Neben den in #1805 eingefügten "Schieben" fügt dieser PR das "Ziehen" hinzu.  
Konzeptuell ist das Ganze identisch, nur wird nicht nach vorne geguckt, sondern nach hinten.  
Ich habe noch ein Problem mit der Animation.  
Da der Held sich beim Ziehen nach hinten bewegt, wechselt das VelocitySystem die Animation entsprechend. Es sieht eher so aus, als würde der Held den Stein hinter sich herziehen (naja, damit kann man erstmal leben):  
Dabei ändert das VS aber auch die Blickrichtung des Helden (Rückwärtsgehen geht ja nicht).  
Das führt dazu, dass jedes Mal, wenn der Held einmal am Stein zieht, er danach nicht mehr den Stein anschaut. Ich müsste ihn in Blockly erst einmal umdrehen … doof.  
Daher dachte ich, ein einfaches  
```java
pc.viewDirection(viewDirection);
waitDelta();
```  
am …
=> [Blockly] add pull feature

blockly/src/entities/MiscFactory.java
fixes #1750 
Ergänzt die `MiscFactory` um eine Funktion zum Erstellen eines Buches, das beim Interagieren ein Text-Popup öffnet.
Damit soll der Spieler in manchen Leveln belohnt werden, z. B. schaltet er #1753 frei.
ACHTUNG: Das hier ist ein reines Dummy-Item, um dem Spieler im Spiel etwas zu geben, ein bisschen Text zu präsentieren etc. Es ist nicht gedacht, dass das Ding wirklich etwas in Blockly freischaltet. Das können wir später extern definieren und so "faken".
Usage
```java
MiscFacory.bookPickup(position,"Neuer Block freigeschaltet", "Oh schaumal, mit diesem Block kannst du direkt zum Ausgang");
```
Es ist ein reines "Story-Telling"-Device.
=> [Blockly] add book to MiscFactory

blockly/frontend/src/blocks/dungeon.ts, blockly/frontend/src/generators/java.ts, blockly/frontend/src/generators/java/items.ts, blockly/frontend/src/generators/java/skills.ts, blockly/frontend/src/toolbox.ts, blockly/src/components/BlocklyItemComponent.java, blockly/src/entities/MiscFactory.java, blockly/src/server/Server.java
fixes #1777  
- Fügt die Blöcke `aufsammeln` und `fallen lassen %1` mit dem möglichen Parameter `Brotkrumen` hinzu.  
- `aufsammeln` löst `onInteraction` für alle Entitäten mit `BlocklyItemComponent` aus, die sich auf dem gleichen Tile wie der Held befinden.  
- `fallen lassen` erzeugt eine neue Item-Entität auf dem Feld des Helden. Da Blockly kein Inventar benötigt, gibt es keinen Check, ob genug Items vorhanden sind (und das ist aktuell auch nicht vorgesehen).  
- `MiscFactory#breadcrumb` erstellt ein Item, das später in Rätseln als Wegmarkierung genutzt wird (z. B. Hänsel und Gretel).  
- Fügt `BlocklyItemComponent` als Marker-Komponente hinzu.  
---  
**Konzeptioneller Hinweis:**  
Im `Dungeon.contrib` haben wir ein recht ausgeklügeltes Item-System mit Enums, Buildern, Crafting etc. …
=> [Blockly] add Item blocks

blockly/frontend/src/blocks/dungeon.ts, blockly/frontend/src/generators/java/skills.ts, blockly/frontend/src/toolbox.ts, blockly/src/client/Client.java, blockly/src/components/AmmunitionComponent.java, blockly/src/entities/MiscFactory.java, blockly/src/server/Server.java
Ich habe den bisher existierenden Feuerball-Block abgeändert, sodass dieser immer in die Blickrichtung des Helden schießt. Außerdem muss eine `fireballScroll` aufgesammelt werden, damit der Held Munition für einen Feuerball hat.
Für die Munition habe ich das `AmmunitionComponent()` erstellt und dem Helden in der  `createHero()` zugewiesen.
Die Munition wird in der `onLevelLoad()` zurückgesetzt und somit nicht ins nächste Level übernommen.
Aktuell ist noch kein UI-Element vorhanden, und dafür bräuchten wir dementsprechend ein separates Issue.
closes #1759 , abgesehen von dem UI-Element
=> Blockly: change fieball block to require ammunition

blockly/src/server/Server.java
fixes #1815
Der Bug wurde verursacht, da der `move`-Command die Entitäten am Ende immer zentriert. 
Problem: Es wurden die Coordinaten des Target-Tiles (also wohin der Spieler sich bewegt wird) zum zentrieren verwendet. Das klappt im selben Level ohne Probleme da `targetTile == Game.tileAt(playerPosition)` ABER wenn ein neues Level geladen wird, passt das nicht mehr.
- Ersetzt `currentTile` in der Abfrage mit `Game.tileAt(entityPosition)`
=> [Blockly] fix bug where player was centered on the wrong coordinate 

blockly/frontend/src/blocks/dungeon.ts, blockly/frontend/src/generators/java/condition.ts, blockly/frontend/src/toolbox.ts, blockly/src/antlr/BlocklyConditionVisitor.java, blockly/src/client/Client.java, blockly/src/server/Server.java
fixes #1833 
fügt einen Block ein, der mittels Direction Input prüft ob auf dem Tile was "aktives" ist
Aktiv sind
- offene türen
- Schalter im On State
=> [Blockly] add `aktiv` Block

blockly/frontend/src/index.ts, blockly/frontend/src/style.css, blockly/frontend/src/toolbox.ts, blockly/frontend/src/utils/variableList.ts, blockly/frontend/src/variableList.ts, blockly/src/server/Server.java
Ich habe eine Variable-Anzeige im Blockly UI ergänzt. In dieser UI kann man Variablen erstellen, löschen und in Echtzeit den aktuellen Wert sehen – was Issue #1752 obsolet macht.
- `Server.java`: Neue API-Schnittstelle liefert die aktuellen Variablen samt Wert.
- `index.ts` & `variableList.ts`: Logik für die Variablen-Ansicht implementiert.
- Anzeige: Fehlt ein Wert, wird standardmäßig „?“ angezeigt.
Screenshot von der Variablen Anzeige:
closes #1780
=> Blockly: Variables Display

game/src/core/game/GameLoop.java, game/src/core/game/PreRunConfiguration.java
Als Workaround für #1842 hab ich die PreGameConfig um die Option ergänzt, das resizing zu deaktiveren. 
WICHTIG: Das fixt den Bug nicht, es um geht ihn
=> [CORE] add resize to pregameconfig and disable it per default

blockly/frontend/src/blocks/dungeon.ts, blockly/src/server/Server.java
fixes #1864 
Dieser PR überarbeitet die Richtungsabfrage bei Checks (also ist Wand-Rechts,Links,Oben,Unten etc.) so, dass die geprüften Richtung jetzt relativ zu der Blickrichtung des Helden ist.
Guck ich also nach unten bedeutet "Ist wand rechts?" ob das Tile im globalen System links vom Helden eine Wand ist. 
Die Richtungsblöcke Oben/Unten wurden entsprechend zu vorne/hinten umbenannt.
=> Blockly: use relative directions for tile-checks

blockly/frontend/webserver/webserver.ts
Um zu verhindern, dass der Blockly Server und der Webserver für das Frontend den gleichen Port verwenden, habe ich den Standard-Port vom Webserver geändert.
=> Blockly: Change webserver default port

blockly/frontend/src/api/api.ts, blockly/frontend/src/index.ts, blockly/frontend/src/utils/workspace.ts
Ich habe die `index.ts` im Blockly Frontend refactored. Der Großteil der Logik wurde in `workspace.ts` ausgelagert, und die API-Methoden befinden sich jetzt in `api.ts`. Zudem wurde das Problem mit mehreren Start-Blöcken, das in Issue #1868 beschrieben wurde, behoben. Nun wird beim Platzieren eines Blocks überprüft, ob es mehrere Start-Blöcke gibt, und der älteste Block wird gelöscht. Das Laden und Speichern der letzten Session wurde ebenfalls korrekt implementiert: Wenn keine vorherige Session vorhanden ist, wird ein Start-Block platziert.
- `index.ts`: Refactoring der Logik und Auslagerung in separate Dateien.
- `workspace.ts`: Auslagerung der Hauptlogik, die zuvor in `index.ts` war.
- `api.ts`: Verschiebung der API-Methoden für eine bessere Strukturierung.
- Start-Block Fix: Verhindert …
=> Blockly: Refactor Frontend Logic and Fix Multiple Start Block Issue

blockly/frontend/src/blocks/dungeon.ts, blockly/frontend/src/toolbox.ts
Ich habe in `toolbox.ts` die Blöcke sortiert und mich dabei an @AMatutat Vorschlag orientiert.
Außerdem habe ich die Farben angepasst so wie ich es für hübsch und sinvoll halte.
In `dungeon.ts` sind ebenfalls Farb änderungen und zusätzliche Kommentare zur Kategorisierung.
closes #1784 
Die Tooltips in der `dungeon.ts` habe ich ebenfalls angepasst bzw. neue hinzugefügt. Allerdings fehlen noch die Tooltips für:
- var_number
- set_number_expression
- get_variable
- get_number
Diese sind alle unter dem Menüpunkt 'Variablen' zu finden. Mir ist nicht ganz bewusst, wie sie angewendet werden.
closes #1811, abgesehen der vier genannten
=> Blockly: UI Cleaning

blockly/src/entities/MiscFactory.java, blockly/src/server/Server.java
Setzt Feedback aus #1783 um
- Steine können nicht mehr in Monster geschoben werden
- Blockly-Schalter sind jetzt Blockable (außer die Trittschalter), dafür muss dann aber die `MiscFactory` aus Blockly zum generieren von Schaltern verwendet werden, nicht mehr die `LeverFactory`
=> [blockly] make lever blockable, disable stone push into monster

blockly/frontend/src/utils/level.ts
Dieser PR behebt ein Problem, bei dem durch das erneute Abschließen eines niedrigeren Levels der gespeicherte Level-Fortschritt zurückgesetzt wurde. Es wurde eine Abfrage ergänzt, die nur den höheren Fortschritt speichert.
fixes #1894
=> Blockly: Prevent level progress downgrade in localStorage

blockly/src/components/TintDirectionComponent.java
Guards haben beim Tod eingefärbte Tiles hinterlassen, die auch nach Levelwechsel sichtbar blieben. Ursache war, dass beim Speichern der Originalfarben versehentlich die bereits eingefärbten Farben (z. B. rot) gespeichert wurden. Nun wird korrekt der ursprüngliche Farbzustand gesichert.
fixes #1875
=> Blockly: Fix tint persisting after Guard death and level change

blockly/frontend/src/utils/workspace.ts
Behebt einen Bug, bei dem zuvor ausgeblendete Kategorien wieder sichtbar wurden, sobald ein Block platziert wurde.
fixes #1901
=> Blockly: Fix category visibility toggling on block placement

game/src/core/game/GameLoop.java
Beim Levelwechsel wurde die Blickrichtung des Helden nicht korrekt zurückgesetzt. Jetzt werden beim Wechsel alle RUN-Animationen des Helden geleert, sodass der Held wie erwartet nach unten schaut.  
fixes #1903
=> Blockly: Fix hero direction reset on level change

blockly/src/utils/pathfinding/AStarPathFinding.java, blockly/src/utils/pathfinding/AStarPriorityQueue.java, blockly/src/utils/pathfinding/PathfindingLogic.java, game/src/core/level/Tile.java, game/src/core/level/elements/astar/TileConnection.java, game/src/core/level/elements/astar/TileHeuristic.java
Ich habe den A\* Algorithmus in das neuen `PathfindingSystem` integriert, um ihn visuell darzustellen.
* `Tile.java`: Hinzufügen der Methode `distance(Tile other)` zur Berechnung der Manhattan-Distanz.
* `PathfindingLogic.java`: Rausgeben des FrontierSets um auch Prioritäten zu unterstützen.
* `TileHeuristic.java` & `TileConnection.java`: Anpassung der Distanzberechnung auf Manhattan-Distanz.
* `PathfindingSystem.java`: Aufruf der A\*-Logik und Weitergabe der einzelnen Schritte an den `PathfindingVisualizer.java`.
Die Manhattan-Distanz wird verwendet, da sich die Mobs ausschließlich in orthogonalen Richtungen bewegen und so die Pfadfindung effizienter (genauere Kosten) wird.
closes #1859
=> Blockly: Implement A* in PathfindingSystem

blockly/frontend/index.html, blockly/frontend/src/style.css, blockly/src/client/Client.java, game/src/core/Game.java
Um Blockly richtig nutzen zu können, muss man Web und Spiel im Split-View Side by Side haben. 
Auf kleinen Monitoren ist das ganz schön doof:
Ich hab hier (mehr quick and dirty als stukturiert) die Ansicht für den generierten Code entfernt und die Buttons nach unten geschoben, dadurch hat das Block Feld deutlich mehr platz.
So sieht das jetzt auf meinen MacBook aus (ich hab etwas seltsame Skalierungseinstellungne, da ich die Sehhilfe optionen von Mac nutze)
=> Blockly: declutter webview, allow game resizing 

blockly/build.gradle, blockly/src/entities/BlocklyMonster.java, blockly/src/level/AiMazeLevel.java, blockly/src/starter/ComparePathfindigsStarter.java, blockly/src/starter/ComparePathfindingStarter.java, blockly/src/starter/PathfinderStarter.java, blockly/src/systems/PathfindingSystem.java, blockly/src/utils/pathfinding/PathfindingVisualizer.java, dungeon/src/contrib/level/DevDungeonLoader.java
Ich habe eine neue Starter-Klasse `ComparePathfindingStarter.java` erstellt, mit der zwei Pathfinding-Algorithmen parallel angezeigt und ausgeführt werden.
* `ComparePathfindingStarter.java`: Dupliziert das aktuelle Level nach oben, platziert den Helden im Original und einen Dummy-Runner im Duplikat, und startet beide Algorithmen nebeneinander über das erweiterte `PathfindingSystem`. Es wird automatisch eine passende Zoom Stufe für das Spiel gefunden und gesetzt. Das Fenster ist per Default Maximiert.
* `PathfindingSystem.java`: Unterstützung für mehrere Pathfinding-Instanzen, um parallele Ausführung und Visualisierung zu ermöglichen.
* `AiMazeLevel.java`: Neue Kamera-Zoom-Einstellung, damit beide Level-Duplikate gleichzeitig gut sichtbar sind.
* `PathfindingVisualizer.java`: Bugfix – …
=> Blockly: Compare two Pathfinding Algorithms side by side

blockly/src/level/AiMazeLevel.java, blockly/src/starter/PathfinderStarter.java, dungeon/src/contrib/systems/PathSystem.java
Ich habe zwei Probleme behoben, die beim Verwenden mehrerer Levels im `PathfindingStarter` auftraten.
* `AiMazeLevel.java`: Zoom wird jetzt nur einmalig auf den gewünschten Wert gesetzt und nicht bei jedem Level-Wechsel angewandt.
* `PathSystem.java`: Entfernt die `PathComponent` von Entities nach Beenden des Pfads, sodass der Held nicht dauerhaft als "laufend“ markiert bleibt.
=> Dungeon: Fix multi-level issues in PathfindingStarter

game/src/core/game/GameLoop.java, game/src/core/game/WindowEventManager.java
Ich habe eine zentrale Klasse `WindowEventManager` im Game-Projekt erstellt, die das Registrieren, Entfernen und Ausführen von Fensterereignis-Listenern kapselt. Damit lassen sich alle relevanten Fenster-Events über eine einheitliche API abonnieren.
* `WindowEventManager.java`:
* Statische Listener-Listen für Fenstererstellung, Iconify, Maximieren, Fokusänderung, Close-Request, Datei-Drops und Refresh-Events.
* `register…Listener(...)` und `unregister…Listener(...)`-Methoden für jedes Event.
* `clearAllListeners()` zum Entfernen aller Listener.
* `windowListener()`: Liefert und erstellt den `Lwjgl3WindowListener`, der in `GameLoop.java` gesetzt wird.
Beispielaufrufe:
```java
WindowEventManager.registerFocusChangeListener(focus -> System.out.println("Focus: " + focus)); // focus = …
```
=> Core: Add `WindowEventManager` for window event handling

blockly/src/starter/PathfinderStarter.java, blockly/src/systems/PathfindingSystem.java, blockly/src/utils/pathfinding/PathfindingVisualizer.java
Ich habe den `PathfindingStarter` so angepasst, dass er bei einem Levelwechsel alle Algorithmen zurücksetzt um mehrere Levels hintereinander zu unterstützen. Zudem kann jetzt ein Algorithmus neu ausgewählt werden, solange noch keiner läuft – der Titel zeigt zudem den Status, wenn kein Algorithmus ausgewählt wurde. Zur Reduzierung von Code-Duplizierung wurde die Klasse mit privaten Helper-Methoden refactored.
* `ComparePathfindingStarter.java`:
* Zurücksetzen aller Algorithmen bei Levelwechsel.
* Erlauben deine Algo-Auswahl zu ändern, solange noch keine gestartet wurde
* Refactoring durch private Helper-Methoden.
* Refactoring bessere Benutzung von Streams.
* `PathfindingSystem.java`:
* Neue Public-Methoden `isEveryAlgorithmRunning()` und `isEveryAlgorithmFinished()` zur Abfrage des …
=> Pathfinder: PathfindingStarter reset and reselection support

blockly/src/produsAdvanced/abstraction/FireballSkill.java
Standardwerte für Feuerball wurden im Konstruktor nicht gesetzt, sodass per Default kein Feuerball geschossen wurde. Jetzt werden im Ctor folgende Felder initialisiert:
* `FireballSkill.java`:
```java
this.texture     = texture;
this.range       = range;
this.speed       = speed;
this.damage      = damageAmount;
```
=> AdvancedDungeon: Fix fireball missing defaults in constructor

blockly/src/produsAdvanced/AdvancedDungeon.java
Ich habe dafür gesorgt, dass der Code aus `MyPlayerController` direkt beim ersten Spielstart geladen wird, ohne dass das Fenster den Fokus wechseln muss.
* `AdvancedDungeon.java`:
* Aufruf von `recompileHeroControl()` von der `restart()`-Methode in die `createHero()`-Methode verschoben, damit die Hero-Controller-Logik bereits beim Initialisieren des Helden kompiliert wird.
closes #2002
=> AdvancedDungeon: Load `MyPlayerController` at initial startup

blockly/src/produsAdvanced/abstraction/FireballSkill.java
Ich habe in der Klasse `FireballSkill` in der `onHit` Methode eine `try catch` hinzugefügt, um die `UnsupportedOperationException` der `onBerryHit` aus `MyFireball` zu fangen.
Dementsprechend wurde noch der Logger zur Klasse hinzugefügt.
closes #2003
=> Advanced Dungeon: catch Exception for onBerryHit

blockly/src/level/produs/Chapter16Level.java
In Level 6 wurden die Steine unter die Schalter gezeichnet, dass sah doof aus.
Durch die veränderte add Reihenfolge der Entitäten ist das jetzt gefixt.
Perspektvisch ein Layer-System einführen?
=> Blockly: fix order of drawing in level 6

blockly/frontend/src/utils/level.ts
Setzt im `localStorage` den Schlüssel `levelProgress` per Default auf 0, falls er noch nicht existiert.
closes #2015
=> Blockly: Initialize `levelProgress` to 0 if missing

blockly/src/client/Client.java, blockly/src/server/Server.java, blockly/src/utils/BlocklyCodeRunner.java, blockly/vs-code-extension/src/extension.ts
Die VS Code Extension stellt nun Methoden bereit, mit denen man das nächste Level laden (`loadNextLevel`) oder ein spezifisches Level per Index auswählen (`loadLevel(index)`) kann.
closes #2014
=> Blockly: Add `loadNextLevel` and `loadLevel(index)` 

blockly/frontend/src/index.ts, blockly/frontend/src/utils/level.ts
Wenn im Frontend keine Levels gefunden werden, wird jetzt alle 5 Sekunden erneut versucht, die Level-Liste zu aktualisieren, wobei die Wartezeit nach jedem Versuch um 5 Sekunden erhöht wird. Dieser Vorgang wird fortgesetzt, bis Levels gefunden werden oder die Wartezeit 60 Sekunden überschreitet.
=> Blockly: Retry fetching levels until timeout

blockly/frontend/src/blocks/dungeon.ts, blockly/frontend/src/toolbox.ts
Ich habe die numerischen Vergleichsblöcke so angepasst, dass jetzt Variablen in Bedingungen verwendet werden können (z. B. `var < 5`). Bisher waren nur Konstantenzahlen erlaubt. Da aktuell alle Variablen Zahlen repräsentieren, werden nun Variablen, numerische Literale, Expressions (z. B. `1+1`) und Array-Werte unterstützt.
* `dungeon.ts` - Block-Definition: Inputs erweitert, um die neuen Typen zu akzeptieren.
* `toolbox.ts` - `get_number` aus der Auswahlliste entfernt.
closes #2064
=> Blockly: Support variables in numeric comparisons

blockly/src/utils/BlocklyCommands.java, dungeon/src/contrib/utils/Direction.java, dungeon/src/contrib/utils/EntityUtils.java, game/src/core/Game.java
This is a follow-up to #2110, where changes to the `active()` method in [BlocklyCommands](url) were introduced. This required multiple terminating and reopening operations on the stream, which is not particularly attractive. In addition, the value `null` was also returned in the auxiliary method `active()`, which forces all callers to use the usual scheme `var wuppie = active(); if (wuppie == null) foo();`.
This refactoring introduces an `Optional<Tile>` as return of `active()`, which should lead to a better readability and maintainability of the code.
Additionally, some convenience methods were defined to make the code more readable and increase the symmetry of the operations.
---
~~edit: waiting for #2120 (`Direction` gets moved)~~
=> Blockly: refactor BlocklyCommands#active()

README.md
fixes #1481; fixes #1898
* Fügt den Header **"Funding"** hinzu
* Listet die bisherigen Förderprojekte 
* Entfernt den Header **"Dungeon: Learning by Questing"** (DSL-Dungeon), da das Projekt nicht mehr Teil der Seite ist
* Führt kleinere Aufräumarbeiten durch (Entfernung veralteter Informationen)
* Fügt link auf die Produs Webseite hinzu?
→ @cagix: Passt dir die Position, oder das eher zu "Funding" neben der Förderung?
@cagix ich habe jetzt bewusst noch nicht die Subprojekte beschrieben. Wenn wir die eh noch anders bennenen, gruppieren und co mach ich mir die arbeit zwei mal 
EDIT: Oh #1481 beantwortet ein paar meiner Fragen, ich komme ja von #1898
Edit Edit:
* Beim Digi-Fellows Projekt habe ich recht wenig Projekt-Metadaten gefunden (nit mal ne nummer)
*.Bei der Beschreibung für das …
=> Orga: add funding to readme

blockly/src/utils/components/skill/InevitableFireballSkill.java
fixes #2074
In seltenen Fällen konnte man den Helden in genau so einen Winkel zum Monster bewegen, dass das Monster den Helden zwar sehen und besiegen **sollte** (wichtig: das war im Level-Design auch so gedacht, dass der Held dort nicht stehen kann), aber der Feuerball, der vom Monster verschossen wird, den Helden nicht trifft, weil eine Wand in der Flugbahn liegt.
In diesem PR wird der `InevitableFireball` so erweitert, dass er das Level auch neu startet, wenn er eine Wand trifft.
Cooler wäre es, wenn der Feuerball einfach durch die Wand oder um die Wand fliegen würde, aber das würde größere Umbauarbeiten im Core voraussetzen, die für diesen super Edge-Case nicht gerechtfertigt sind.
Hier in Gründ konnte man sonst vorher stehen.
=> Blockly: `InevitableFireball` now restarts the level, even if it hits a wall

advancedDungeon/build.gradle, blockly/build.gradle, devDungeon/build.gradle, dungeon/build.gradle
1. Alle Starter werden in die Gradle-Group "starter" assoziert.
2. Alle Jar-Building-Tasks werden in die Gradle-Group "jar" assoziert.
3. Die Namen sind halbwegs vereinheitlicht: 
- "runXYZ" zum Starten eines Dungeons
- "buildXYZ" zum Bauen der Jars
Damit hat man für das Gesamtprojekt die Reiter "starter" und "jar" mit allen entsprechenden Tasks, und für die Subprojekte dann nochmal individuell. 
fixes #1336
=> Gradle: associate custom starter with gradle group 'starter'

dungeon/src/contrib/utils/components/ai/idle/StaticRadiusWalk.java, dungeon/src/contrib/utils/components/interaction/DropItemsInteraction.java, dungeon/src/core/level/utils/LevelUtils.java
The method `LevelUtils#randomAccessibleTileCoordinateInRange` was returning the `Coordinate` of a random tile in range. However, all uses would convert the result to `Point` - so let's do this right in the method itself. 
Also, just use `findAny()` instead of a custom randomisation. According to the [doc](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/stream/Stream.html#findAny()) `findAny()` is "_explicitly nondeterministic_", thus it will return a random element from the stream.
=> LevelUtils: refactor randomAccessibleTileCoordinateInRange to improve readability

devDungeon/src/systems/FogOfWarSystem.java, dungeon/src/contrib/systems/FogSystem.java, dungeon/src/core/utils/Point.java
`heroPos.toCoordinate().toPoint()` transforms a point into a coordinate into a point - just to floor the floating x and y fields in `Point`. The need for a comment suggests a refactoring ... 
This PR introduces a dedicated method to floor the field of `Point` improve readability.
=> Fog: refactor magic conversions

blockly/src/utils/BlocklyCodeRunner.java
Ich habe eine Whitelist hinzugefügt, die bestimmte Blockly-Kommandos enthält. In der angepassten Methode `addSleepCalls()` wird hinter jedem dieser Kommandos ein `sleep();` eingefügt.
Dadurch sind auch Kontrollstrukturen wie switch-case wieder uneingeschränkt verwendbar, da Keywords wie `break;`, `continue;` und `yield;` nicht in der Whitelist enthalten sind und somit nicht verändert werden.
closes #2135
=>  Vs-Code: allow break continue yield

blockly/src/utils/BlocklyCommands.java, dungeon/src/core/utils/Direction.java
Der in #2263 beschriebene Fehler entsteht in der Methode `targetTile()` in `BlocklyCommands`. 
Dort wird `applyRelative` aufgerufen. Da NONE jedoch keine tatsächliche Richtung repräsentiert, sollte in diesem Fall keine Umrechung erfolgen.  Hierdurch wird aktuell fälschlicherweise die Blickrichtung des Helden ab diesem Punkt als Zielrichtung verwendet, obwohl die ursprüngliche Intention war, die aktuelle Position des Helden (`hier`-Block) zu prüfen. 
Als Lösung habe ich die Methoden `isNearTile` und `isNearComponent` um jeweils eine zusätzliche Abfrage ergänzt. Wenn `Direction.NONE` übergeben wird, arbeiten beide Methoden nun direkt mit der aktuellen Position des Helden, da diese in diesem Fall unabhängig von dessen Blickrichtung ist. 
fixes #2263
=> Blockly: fixes hier-Block to work for isNearTile and isNearComponent

blockly/src/client/Client.java, dungeon/src/contrib/components/PressurePlateComponent.java, dungeon/src/contrib/entities/LeverFactory.java, dungeon/src/contrib/systems/PressurePlateSystem.java, dungeon/test/contrib/components/PressurePlateComponentTest.java, dungeon/test/contrib/systems/PressurePlateSystemTest.java
Dieser PR verändert die Druckplatten so, dass sie jetzt mit der aufliegenden Masse agieren.
Im Component kann angegeben werden, ab welchem Wert eine Platte auslösen soll, also quasi wie schwer der Typ (oder die Sammlung an Typen) auf der Platte sein muss, damit sie gedrückt wird.
Das System prüft dann entsprechend und setzt das LeverComponent entsprechend auf an oder aus.
Rechts hat einen Druckwert von 0.1f, das kann Kiste oder Held alleine schaffen, links braucht es beide.
(Hab schlecht gespielt)
https://github.com/user-attachments/assets/fb1dc342-24f6-4853-80e3-8a3cdd8559cf
=> Dungeon: Make Pressureplates mass related

advancedDungeon/src/produsAdvanced/level/AdvancedBerryLevel.java, blockly/src/level/produs/Level011.java, blockly/src/level/produs/Level022.java, devDungeon/src/level/devlevel/TutorialLevel.java, devDungeon/src/systems/DevHealthSystem.java, devDungeon/src/utils/EntityUtils.java, dungeon/src/contrib/components/HealthComponent.java, dungeon/src/contrib/entities/HeroFactory.java, dungeon/src/contrib/entities/MonsterFactory.java, dungeon/src/contrib/systems/HealthSystem.java, dungeon/src/core/components/DrawComponent.java, dungeon/test/contrib/systems/HealthSystemTest.java
Bisher hat das `HealthSystem` alle Entitäten die hp<=0 haben automatisch gelöscht.
Diese Implikation habe ich entfernt. Das entfernen der Entität muss jetzt expliziet im `onDeath` callback implementiert werden.
Das erlaubt es, im Callback des Heldentot, via `DungeonLoader` das aktuelle Level neu zu laden. 
Dabei wird
* eine neue Instanz der Level-Manger Klasse erstellt und daher `onFirstTick` des Levels erneut ausgeführt
* das Level wird dadurch in Ausgangsposition zurück gesetzt (Monster, Items, Kisten, Türen etc.)
* Die HP des Helden wieder auf sein maximum gesetzt
* Die Animation Queue des Helden geleert
* Das Inventar des Helden wird **nicht** reseted.
* Die Blickrichtung des Helden wird **nicht** reseted, das kann bei Bedarf in der
* Es werden **keine** statics aufgeräumt oder Level …
=> Dungeon: reload level on hero death; use DeathAnimation if possible

dungeon/src/contrib/components/CatapultableComponent.java, dungeon/src/contrib/entities/MiscFactory.java, dungeon/src/contrib/systems/FallingSystem.java
Es gab mehrere kleine Probleme mit den Katapulten
* Das Fallingsystem hat nicht geprüft, ob eine entität fliegen kann. `canEnterOpenPits` im VelocityComponent sagt nur, ob ich das Tile betreten kann, schützt mich aber nicht vorm Absturz. Ab jetzt können Entitäten mit den `FlyComponent` über Pits drüber fliegen.
* Wenn ich von einem Katapult auf ein anderes Katapult gesprungen bin, speicherte das zweite Katapult mein temporäres VelocityComponent vom erste Flug als "mein default" ab und gibts mir das am Ende zurück. Das `CatapultableComponent`trackt jetzt, ob ich grade am fliegen bin und wenn ja, kann ich nicht wieder katapultiert werden. 
Das bedeutet auch erstmal, dass man nicht direkt von einem Katapult auf das andere fliegen kann. Etwas schade, aber vermjtlich für unser Design auch …
=> Dungeon: fix catapults

devDungeon/src/entities/MonsterType.java, devDungeon/src/level/devlevel/BossLevel.java, devDungeon/src/level/devlevel/IllusionRiddleLevel.java, dungeon/src/contrib/components/AIComponent.java, dungeon/src/contrib/entities/AIFactory.java, dungeon/src/contrib/utils/components/ai/fight/AIRangeBehaviour.java, dungeon/src/contrib/utils/components/ai/fight/RangeAI.java, dungeon/src/contrib/utils/components/skill/ISkillUser.java
Die Klasse hatte folgende Probleme:
- Variablen Namen die Verwirrung erzeugen
- Eine unübersichtliche `accept`-Methode
Ich habe die betroffenen Variablen Namen umbenannt und die `accept`-Methode mithilfe von Helfer Methoden übersichtlicher gestaltet.
Allerdings gibt es nach wie vor ein Logik Problem: Die AI geht nicht auf Abstand, wenn der Spieler (Hero) zu nah kommt.
=> Dungeon: refactor `RangeAI`

dungeon/src/contrib/utils/components/ai/transition/ProtectOnApproach.java
Die Methode prüft, ob der Spieler in der Nähe ist. Wenn das einmal der Fall ist, wird isInFight auf true gesetzt. Die Figur bleibt dann im Kampfmodus – auch wenn der Spieler später wieder weggeht.
Das ist so gewollt und steht jetzt klar in der JavaDoc. Die Methode gibt es nur noch eine Stelle, wo sie endet. Dadurch ist sie besser zu verstehen und leichter zu testen.
=> Dungeon: refactor ProtectOnApproach for clearer apply() method behavior

dungeon/src/contrib/utils/components/ai/AIUtils.java
=> AIUtils: use stream operation to avoid potentially out-of-bound index operations

advancedDungeon/src/aiAdvanced/starter/ComparePathfindingStarter.java, blockly/src/client/Client.java, dungeon/src/core/Game.java, dungeon/src/core/game/GameLoop.java, dungeon/src/core/game/PreRunConfiguration.java
Mit diesem PR wird das hübsche Schachmuster per default Einstellung in jedem Dungeon verwendet.
Optional kann das ganze über die Config ausgeschaltet werden. 
Ohne
Mit
=> Dungeon: enable checkpattern as default

advancedDungeon/src/aiAdvanced/starter/ComparePathfindingStarter.java, advancedDungeon/src/aiAdvanced/starter/PathfinderStarter.java, advancedDungeon/src/produsAdvanced/abstraction/Hero.java, blockly/src/client/Client.java, blockly/src/entities/HeroTankControlledFactory.java, dungeon/src/contrib/components/InteractionComponent.java, dungeon/src/contrib/entities/HeroFactory.java, dungeon/src/contrib/item/concreteItem/ItemWoodenBow.java, dungeon/src/core/components/InputComponent.java, dungeon/src/core/components/PlayerComponent.java, dungeon/src/core/game/GameLoop.java, dungeon/src/core/systems/InputSystem.java, dungeon/test/core/components/PlayerComponentTest.java
Dieser PR splittet die Player- und Input-Logik, benennt das Input-System um und aktualisiert Javadoc.
- `PlayerComponent` dient jetzt nur noch als Marker und speichert offene Dialoge; `InputComponent` verwaltet Input-Callbacks.
- `HeroFactory` hat nun beide Komponenten.
- `PlayerSystem`, heißt nun `InputSystem`; JavaDoc angepasst/ergänzt.
- `InputSystem`-Refactor: Feld `running` zu `paused` umbenannt, um die Logik besser verstehen.
=> Dungeon: Split Player components and system to InputSystem

blockly/src/entities/HeroTankControlledFactory.java, dungeon/src/contrib/entities/HeroFactory.java, dungeon/src/core/Entity.java, dungeon/src/core/game/ECSManagment.java, dungeon/src/core/game/GameLoop.java
Fügt ein Flag `persistant` in `Entity` hinzu.
Wenn das Flag auf True ist, wird die Entität mit in das nächste Level genommen.
Das ist grade für so unsichtbare ControllerEntitäten oder HUD geschichten praktisch. 
Achtung: Die Position wird nicht neu gesetzt.
=> Dungeon: allow persistent entities

escapeRoom/src/petriNet/PetriNetSystem.java, escapeRoom/src/petriNet/PlaceComponent.java, escapeRoom/test/petriNet/PetriNetSystemTest.java, escapeRoom/test/petriNet/PlaceComponentTest.java
Erweitert PR #2337.
Dort hatte ich die Bedingung eingebaut, dass eine Transition immer nur ein Token pro Place konsumieren bzw. produzieren kann.
Diese Bedingung ist Unsinn und schränkt nur ein.
Dieser PR ergänzt die Arcs im Petri-Netz um Weights.
=> Escaperoom: add weight to PetriNet Arcs

escapeRoom/src/petriNet/PetriNetSystem.java, escapeRoom/test/petriNet/PetriNetSystemTest.java
Das ist #2337 einführte `PetriNetSystem` hatte einige statische Methoden und auch das gespeicherte Petri-Netz war statisch.
Das braucht es aber gar nicht sein, ich hab das damals falsch modeliert.
Dieser PR macht die Methoden non-static und passt die Test an.
Im Demo Level 01 habe ich es auch die ganze Zeit (korrekt) non-static verwendet (weil ich wusste, dass ich das ändere)
=> Escaperoom: make petri net non static

dungeon/src/core/Game.java
**Problem**
Beim Wechsel von einem Level zum anderen stürzte das Spiel sofort ab.
Die Ursache war ein `StackOverflowError` in der Methode
```java
public static Optional<Point> randomTilePoint(final LevelElement elementTyp)
```
In der alten Version rief sich die Methode selbst immer wieder über `Game.randomTilePoint(...)` auf → Endlosschleife → Crash.
---
**Lösung**
Der Aufruf wurde korrigiert, sodass nun die Implementierung des aktuellen Levels verwendet wird:
```java
return currentLevel().flatMap(level -> level.randomTilePoint(elementTyp));
```
Damit wird die Anfrage korrekt an das aktuelle Level delegiert, ohne Endlosschleife.
---
**Tests/Checkliste:**
---
**Ergebnis**
* Spiel läuft wieder stabil
* Levelwechsel funktioniert fehlerfrei
* Keine Auswirkungen auf andere Methoden
=> Dungeon: Hotfix Game.randomTilePoint() – Endlosschleife/StackOverflow behoben

dungeon/src/contrib/hud/dialogs/FreeInputDialog.java
In diesem Pull Request wurde die Klasse `FreeInputDialog` hinzugefügt, mit der sich Dialoge inklusive Texteingabe vom Spieler anzeigen lassen. Die Dialoge bestehen aus einem Titel, einer Fragestellung, einem Textfeld sowie OK- und Abbrechen-Buttons.
Die Klasse kann über die statische Methode `showTextInputDialog(String title, String question, Consumer<Optional<String>> callback)` verwendet werden. Dabei wird intern ein HUD-Entity erstellt, das den Dialog anzeigt. Sobald der Dialog geschlossen wird, wird das HUD-Entity entfernt und das Callback mit dem eingegebenen (oder leeren) Text aufgerufen.
**Hinweis:**
Im aktivierten Debug-Modus des Spiels, der über eine `public static final`-Variable gesteuert wird, können durch Tasteneingaben Debug-Kommandos ausgeführt werden (z.B. Teleport). Diese …
=> Dungeon: Add FreeInputDialog

build.gradle
Ein kleiner Fix, der sich in #2380 versteckt, den ich aber unabhängig von den Ergebnissen dort haben möchte.
Aktuell ist das `workingDir` immer das Verzeichnis, in dem sich das Start-Target befindet.
Also für `runDevDungeon` wäre das `USERSTUFF/dungeon-repo/devDungeon/`.
Ich passe hier die Top-Level `build.gradle` an, damit **alle Projekte** den Project-Root als `workingDir` verwenden.
Das vereinheitlicht zusätzlich das Verhalten, egal ob über Gradle oder über die IDE gestartet wird (IntelliJ verwendet nämlich immer das Root-Project als srcDir).
=> set working directory to project root for all subprojects

dungeon/src/contrib/item/Item.java, dungeon/src/contrib/item/concreteItem/ItemFairy.java, dungeon/src/contrib/item/concreteItem/ItemHeart.java, dungeon/src/contrib/item/concreteItem/ItemWoodenArrow.java, dungeon/src/contrib/item/concreteItem/ItemWoodenBow.java, dungeon/src/contrib/utils/components/skill/Skill.java, dungeon/src/contrib/utils/components/skill/projectileSkill/BowSkill.java, dungeon/src/contrib/utils/components/skill/projectileSkill/ProjectileSkill.java
Pfeile können jetzt in der Wand stecken bleiben und wieder aufgesammelt werden.
Technisch wird ein Arrow bei der `onWallhit` gespawnt.
Das ganze ist Chancenbasiert (default 10%)
Dafür musste ich `Item#drop` nicht mehr ein boolean sondern ein `Optional<Entity>` returnen lassen. 
Mit #2397 passt dann auch optisch die Rotation
Wer testen will: Im `runDemoRoom` hat man direkt nen Hero mit Bogen (reminder mit . und , wechselt man zwischen den skills)
=> Dungeon: make `Item#drop` return Entity + arrows stick in wall

advancedDungeon/src/aiAdvanced/starter/ComparePathfindingStarter.java, advancedDungeon/src/aiAdvanced/starter/PathfinderStarter.java, advancedDungeon/src/produsAdvanced/AdvancedDungeon.java, blockly/src/client/Client.java, devDungeon/src/starter/DevDungeon.java, dungeon/src/starter/BasicStarter.java, escapeRoom/src/starter/CoopDungeon.java, escapeRoom/src/starter/DemoRoom.java
Fixt den `BasicStarter` und `DemoRoom` (siehe #2401)
Ergänzt im AdvancedDungeon und den EscapeRooms die neuen Resourcen Systeme aus #2368 
Fügt jedem Starter in der Javadoc einen Hinweis auf das gradle target hinzu
=> All: Fix Starter and add gradle target to javadoc

dungeon/src/core/utils/Vector2.java, dungeon/test/core/utils/Vector2Test.java
Angle-API und mehrere Randfälle in `Vector2` korrigiert und dokumentiert.
- `Vector2`
- `angleDeg(Vector2 other)` (mehrdeutig) -> `angleToDeg(Vector2 target)` mit klarer Semantik (Winkel von `this` → `target`).
- `angleDeg()` (ohne Parameter) repariert: nutzt jetzt `Math.toDegrees(Math.atan2(y, x))`.
- `MAX` von `Double.MAX_VALUE` auf `Float.MAX_VALUE` umgestellt (vermeidet `Infinity` beim Cast).
- `isZero()` nutzt `lengthSquared()`, `normalize()` vermeidet doppelte Längenberechnung.
- `direction()`: Bei `|x| == |y|` gewinnt die horizontale Achse.
- `Vector2Test`
- Neuer Test für `angleToDeg`.
=> Dungeon: Clarify Vector2 angle, fix edge-cases and better Docs

dungeon/src/contrib/systems/DebugDrawSystem.java, dungeon/src/contrib/systems/FallingSystem.java, dungeon/src/contrib/systems/PitSystem.java, dungeon/src/core/components/VelocityComponent.java, dungeon/src/core/systems/MoveSystem.java, dungeon/test/core/systems/MoveSystemTest.java
Baut auf #2444 auf.
Ich hab @viddie Idee aus seiner MA geklaut/übernommen.
Im VelocityComponent gibt es jetzt eine Move Hitbox (analog zur Hitbox im CollisionComponent).
Im ´MoveSystem` überprüft das System jetzt, ob alle 4-Punkte der Move Hitbox auf einem gültigen Tile stehen.
https://github.com/user-attachments/assets/93cc76cc-6bd5-4767-b121-4366d4bd1664
https://github.com/user-attachments/assets/69e62878-f29c-41ce-9293-e4597611c33d
Es funktioniert, aber die letzen 5% sind manchmal etwas ruckelig. (later?)
Pits und Falling wird mit dem Center der Move-Hitbox getriggered.
@Flamtky und ich haben eben kurz gesprochen und sind über eine Menge Sachen gestoßen, die mal entschieden werden müssten. Daher geht dieser PR den KISS weg. 
Für die Discussion mach ich was auf
Edit: …
=> Dungeon: add Move-Colidebox

dungeon/assets/character/knight/knight.json, dungeon/src/contrib/entities/HeroFactory.java
Fix für https://github.com/Dungeon-CampusMinden/Dungeon/issues/2402
Problem war: Falsches Signal in der Transition und der Knight hatte die death Animation nicht als `looping` gesetzt.
=> Dungeon: Fix death animation not working

blockly/src/client/Client.java
fixes #2462 
Beim laden eines neuen Levels wird jetzt die Velocity auf 0 gesetzt und alle noch aktiven Forces gecleard. 
Das verhindert Bewegung im neuen Level.
=> Blockly: reset velocity at level load

blockly/src/coderunner/BlocklyCommands.java
fixes #2483 
Beim Prüfen des Tiles hinter dem Helden wurde der Offset nicht hinzugefügt.
#2448 beschreibt das bekannte Problem.
=> Blockly: fix Tile check for Pull Command

blockly/src/client/Client.java, blockly/src/coderunner/BlocklyCommands.java, blockly/src/systems/ScheduleShootFireballSystem.java
In Blockly konnte der Held keinen Feuerball schießen, weil die Textur aufgrund des fehlenden libGDX Kontext im Blockly-Thread nicht geladen werden konnte.
DIeser PR nutz den EventSchedular, um das schießen des Feuerballs in den ECS-Thread zu bewegen
=> Blockly: use `EventSchedular` for Hero Fireball

advancedDungeon/src/produsAdvanced/AdvancedDungeon.java, blockly/src/client/Client.java, devDungeon/src/starter/DevDungeon.java, dungeon/src/contrib/components/HealthComponent.java, dungeon/src/contrib/configuration/KeyboardConfig.java, dungeon/src/contrib/systems/DebugDrawSystem.java, dungeon/src/contrib/utils/CollisionUtils.java, dungeon/src/contrib/utils/components/Debugger.java, dungeon/src/core/game/GameLoop.java, dungeon/src/core/systems/CameraSystem.java, escapeRoom/src/starter/CoopDungeon.java, escapeRoom/src/starter/DemoRoom.java
Das `DebugDrawSystem` ist jetzt per Default im Spiel, jedoch ausgeblendet. Mit `F3` kann man das HUD ein und ausblenden.
Dafür braucht man den Debugger, der jetzt auch ein System ist, um den Keystroke aufzufragen.
Zusätzlich kann das `DebugDrawSystem` Entity-Informationen anzeigen, wenn man über ein Entity mit der Maus hovert (siehe Bild). Diese Version ist erstmal nur ein Mini-Prototype zum debuggen, später sollte man evtl. ein Interface ergänzen, was dann von Components implementiert werden kann um eine `Debug-Line` zu ergänzen. So könnte dann auch Blockly oder DevDungeon Komponente angezeigt werden.
=> Dungeon: Update Debugger

dungeon/src/contrib/entities/HeroFactory.java
Eigentlich wurde es durch #2471 gefixt. Aber #2456 hat es ausersehen wieder in der onEnter verschoben
=> Dungeon: spiky damage now caused by onHold 

dungeon/src/contrib/systems/DebugDrawSystem.java, dungeon/src/core/systems/CameraSystem.java
Das Debug-HUD rendert jetzt Kreise mit mehr Segments und zeichnet (falls vorhanden) den Interaktions-Radius ein.
Zusätzlich verwendet jetzt die Hover-Logik die Sprite Dimensionen statt die Kollision-Hitbox
=> Dungeon: Debug-HUD Render Interaction Range

blockly/src/client/Client.java, blockly/src/coderunner/BlocklyCommands.java, blockly/src/systems/FireballSchedular.java
Eigentlich sollte das hier schon in #2479 passiert sein.
Beim rebasen und co muss da was mächtig schief gelaufen sein.
Dieser PR baut den gewünschen EventSchedular zum schießen von Feuerbällen in Blocky ein
=> Blockly: use FireballSchedular

blockly/src/entities/monster/InevitableFireballSkill.java
fixes #2484
Selber spaß wie immer: Durch Float Rundungen stimmt die `tileAt` bestimmung nicht immer
Lösung: Apply MagicOffset
=> Blockly: center hero on the correct tile for fireball

dungeon/src/contrib/components/ShowImageComponent.java, dungeon/src/contrib/entities/ShowImageFactory.java, dungeon/src/contrib/hud/DialogUtils.java, dungeon/src/contrib/systems/ShowImageSystem.java, dungeon/src/contrib/utils/components/showImage/ShowImageText.java, dungeon/src/contrib/utils/components/showImage/ShowImageUI.java, dungeon/src/contrib/utils/components/showImage/TransitionSpeed.java
Platziert ein Entity in der Welt, das bei Interaktion ein Bild (mit optionalem zentrierten Text) in Fullscreen auf dem Bildschirm anzeigen lässt. Beinhaltet System, Component und Factory-Methoden.
~~Hilft bei #2419, aber ändert nichts an der Dialog API.~~
Fügt `DialogUtils.showImagePopUp` hinzu, um Bilder als eigener Dialog auch ohne in-world entity anzeigen zu können. Immer noch nicht alle Funktionen, die in #2419 gefordert werden.
@AMatutat @Flamtky thoughts?
=> Dungeon: Add ShowImage module

dungeon/src/contrib/entities/MiscFactory.java, dungeon/src/core/systems/DrawSystem.java, dungeon/src/core/utils/components/draw/state/State.java, dungeon/src/core/utils/components/draw/state/StateMachine.java
Fixes #2521
- Breakables werden non-solid, sobald die break-Animation startet. 
- `State.onEnter` und `State.onExit` können callbacks erhalten, um Sachen auszuführen, wenn eine Animation einen bestimmten Zustand erreicht.
- Fixed ebenfalls ein Problem im DrawSystem das gerade dazu führt, dass die DrawComponent.depth ignoriert wird.
=> Dungeon: Add breakables turning non-solid upon breaking
