game/src/character/objects/TreasureChest.java
game/src/mydungeon/Starter.java

Call gradle spotlessApply

---

dsl/src/interpreter/DSLInterpreter.java
dsl/src/interpreter/dot/Interpreter.java
dsl/test/interpreter/TestDSLInterpreter.java
game/src/dslToGame/QuestConfig.java

Simplifies interface of DSLInterpreter, to get a `QuestConfig`-object from DSL-input
Offers `QuestConfig` as way for implementing #49

[DSL->Game] Handoff

---

game/src/character/monster/Monster.java
game/src/collision/CollisionMap.java
game/src/collision/TileCollidable.java

Change import level.elements.Tile to level.elements.tile.Tile

---

dsl/src/interpreter/DSLInterpreter.java
dsl/src/runtime/MemorySpace.java
dsl/src/runtime/Value.java
dsl/test/interpreter/TestDSLInterpreter.java

Fix setting of Value.NULL

---

game/src/ecs/components/AnimationComponent.java
game/src/ecs/components/PlayableComponent.java
game/src/ecs/components/VelocityComponent.java
game/src/ecs/systems/KeyboardSystem.java
game/src/ecs/systems/MovementSystem.java
game/test/ecs/components/AnimationComponentTest.java
game/test/ecs/components/PlayableComponentTest.java
game/test/ecs/components/PositionComponentTest.java
game/test/ecs/components/VelocityComponentTest.java
game/test/ecs/systems/DrawSystemTest.java
game/test/ecs/systems/KeyboardSystemTest.java
game/test/ecs/systems/MovementSystemTest.java

Ich hab schonmal für die vorhandenen Klassen passende Unit Testfälle geschrieben.

[GAME] JUnit Tests für ECS

---

game/src/ecs/components/AnimationComponent.java
game/src/ecs/components/PlayableComponent.java
game/src/ecs/components/PositionComponent.java
game/src/ecs/components/VelocityComponent.java
game/src/ecs/entitys/Hero.java
game/src/ecs/systems/DrawSystem.java
game/src/ecs/systems/ECS_System.java
game/src/ecs/systems/KeyboardSystem.java
game/src/ecs/systems/MovementSystem.java
game/src/ecs/systems/SystemController.java
game/src/mydungeon/ECS.java
game/test/ecs/components/AnimationComponentTest.java
game/test/ecs/components/PlayableComponentTest.java
game/test/ecs/components/PositionComponentTest.java
game/test/ecs/components/VelocityComponentTest.java
game/test/ecs/systems/DrawSystemTest.java
game/test/ecs/systems/MovementSystemTest.java

- add `SystemController` für die Integration des ECS in das Framework
- add `DrawSystem` zum zeichnen von Texturen
- add `KeyboardSystem` zur Steuerung des Helden
- add `AnimationComponent` (WIP siehe #94)
- add `PlayabaleComponent` um Spielcharacter zu markieren
- add `Hero` als vorgefertigte Entität 
- incl JUnit-Tests

[GAME] Hero und Steuerung 

---

dsl/src/semanticAnalysis/SymbolTableParser.java
dsl/src/semanticAnalysis/typebulder/TypeBuilder.java
dsl/test/interpreter/TestDSLInterpreter.java
dsl/test/semanticAnalysis/typebuilder/TestTypeBuilder.java
game/src/dslToGame/QuestConfig.java
game/src/quest/GraphSearchQuest.java
game/src/quest/Quest.java

Enables annotation-based building of DSL types from java classes and records.

Add annotation based TypeBuilder

---

CONTRIBUTING.MD
LICENSE.md
README.md

fixes #116 
Kleiner Einschub. 
Hab den großteil aus dem PM-Dungeon übernommen. 
In ferner Zukunft sollten hier nochmal nette Beispiele rein

[Documentation] Update Readme and co

---

dsl/src/runtime/GameEnvironment.java
game/src/ecs/components/VelocityComponent.java
game/src/mydungeon/ECS.java

Das `VelocityComponent` ist noch nicht in der DSL "hinterlegt".
Was ich bisher gemacht habe:
- `VelocityComponent` um die benötigten Annoations ergänzt
- Das `VelocityComponent` in der DSL als Type hinzugefügt
- Test DSL Input ergänzt
Aktuell bekomme ich folgenden Fehler
````
Task :run
operating system 'Mac OS X'
line 5:13 token recognition error at: '0'
line 5:14 token recognition error at: '.'
line 5:16 no viable alternative at input 'velocity_component{x_speed:5f'
line 4:23 extraneous input '{' expecting ID
line 5:11 mismatched input ':' expecting '{'
line 5:17 extraneous input ',' expecting ID
line 6:13 token recognition error at: '0'
line 6:14 token recognition error at: '.'
line 6:11 mismatched input ':' expecting '{'
line 6:17 extraneous input ',' expecting ID
line 7:24 mismatched …
```

[GAME] setup velocityComponent for DSL use

---

dsl/src/runtime/GameEnvironment.java
game/src/ecs/components/HitboxComponent.java
game/src/ecs/entities/Hero.java
game/src/ecs/systems/CollisionSystem.java
game/src/mydungeon/ECS.java

fixes #87
Die Hitbox Komponente und das dazugehörige System.
Nutzt wie die zuvor vereinfachte Hitbox Variante. (Alle Boxen befinden sich in derselben Rotation)
Level wird in einem Extra Issue hinzugefügt. #149
#Time:2

[GAME] Hitbox Component und System

---

game/src/ecs/components/VelocityComponent.java
game/src/ecs/components/ai/AITools.java
game/src/ecs/entities/Hero.java
game/src/ecs/systems/KeyboardSystem.java
game/src/ecs/systems/VelocitySystem.java
game/test/ecs/components/VelocityComponentTest.java
game/test/ecs/systems/VelocitySystemTest.java

fixes #146
- Javadoc angepasst
- Refactoring von Attributnamen

[GAME] refactored VelocityComponent

---

game/src/ecs/components/AnimationComponent.java
game/src/ecs/components/Component.java
game/src/ecs/components/HitboxComponent.java
game/src/ecs/components/PlayableComponent.java
game/src/ecs/components/VelocityComponent.java
game/src/ecs/components/ai/AIComponent.java
game/src/ecs/components/ai/AITools.java
game/src/ecs/components/ai/fight/MeleeAI.java
game/src/ecs/components/ai/transition/ITransition.java
game/src/ecs/entities/Entity.java
game/src/ecs/systems/CollisionSystem.java
game/src/ecs/systems/DrawSystem.java
game/src/levelgraph/DoorDirection.java
game/src/levelgraph/GraphLevel.java
game/src/levelgraph/GraphLevelGenerator.java
game/src/levelgraph/LevelNode.java
game/src/mydungeon/ECS.java
game/src/quest/Evaluateable.java
game/src/room/Room.java

Großteil des IJ-Feedback umgesetzt
- Typos gefixt
- finals hinzugefügt 
- code Optimierung

[GAME] Cleancode: IJ-Feedback umgesetzt

---

.github/workflows/github_ci.yml

fixes #204 
- JUnit in den Workflow integriert (copy pasta aus dem PM-Dungeon)

[CI] add JUnit to CI-Workflow

---

game/src/ecs/systems/VelocitySystem.java
game/test/ecs/systems/VelocitySystemTest.java

fixes #201 indem die Klammer richtig gesetzt wurde.
Außerdem Testfälle ergänzt, damit geprüft wird, ob die Velocity auf 0 gesetzt wird.

[GAME] fix velocity system bug

---

game/src/ecs/components/ai/AITools.java
game/src/ecs/components/ai/idle/RadiusWalk.java

fixes #283 
Hab die Methode `pathFinished` abgeändert, diese prüft nun auch, ob der Pfad verlassen wurde. 
Wir nutzen die Methode um zu bestimmen, ob ein neuer Pfad berechnet werden muss.

[GAME] changed pathFinished to pathFinishedOrLeft

---

game/src/ecs/components/HitboxComponent.java
game/src/ecs/components/collision/ICollide.java
game/src/ecs/entities/Hero.java

Fixes #174 
- Kollision nutzt nun Strategie Pattern anstelle von Reflection.
- Die vorgefertigten Demomethoden wurden umgebaut.

[GAME] Collision per Strategy Pattern

---

doc/dsl/typebuilding.md

[DSL] Dokumentation von `DSLContext`-Annotationen

---

game/src/ecs/components/HealthComponent.java
game/src/ecs/damage/Damage.java
game/src/ecs/damage/DamageType.java
game/src/ecs/systems/HealthSystem.java
game/src/mydungeon/ECS.java

@AMatutat Hatte Langeweile im Meeting bzw. so gar keine Lust auf die x. Überarbeitung der Modulbeschreibungen. Anbei ein kleines Rework der komischen `update`-Loop in `HealthSystem`. Schau mal, ob das so passt. (Nicht formatiert, nicht getestet - aber IJ war erstmal happy bzgl. der Typen.)

[GAME] Healthy Damage: rework strange update-loop in HealthSystem (proof of concept)

---

game/src/ecs/components/ai/fight/MeleeAI.java
game/src/ecs/components/skill/ISkillFunction.java
game/src/ecs/components/skill/Skill.java
game/test/ecs/components/SkillTest.java

fixes #220 
- Interface `ISkillFunction` erstellt
- Klasse `Skill` angepasst
- `SkillTest` angepasst

[GAME] Skill Methode per Strategy Pattern

---

game/src/ecs/components/ai/AIComponent.java
game/src/ecs/components/ai/AITools.java
game/src/ecs/components/ai/idle/StaticRadiusWalk.java

fixes #139
-Entität bewegt sich innerhalb eines festen Bereichs
-unterscheidet sich zu #21 darin, dass der Radius dieses Bereiches sich nicht mit der Entität bewegt

[GAME] IIdle: StatischeRadiusWalk

---

game/src/ecs/items/Item.java
game/src/ecs/items/ItemType.java
game/test/ecs/items/ItemTest.java

#279 
Implementation von einem abstrakten Item, wie im Issue vorgegeben.
- Implementation
- Tests
- simple Doc

[GAME] abstract Item

---

game/src/ecs/components/HitboxComponent.java
game/src/ecs/systems/CollisionSystem.java

fixes #159 
- javadoc hinzugefügt

[GAME] HitBox-System javadoc

---

doc/tasks/README.md

@malt-r ich hab mir dein Dokument mal geschnappt und weitere BP für die Strukturierung eingefügt.
So hatte ich mir das vorgestellt, glaub wir sind da gestern doch nicht mit dem selben Bild rausgegangen.

task documentation erweitern

---

doc/ecs/gameelements/onDeathDropLoot
game/src/ecs/components/DropLoot.java
game/test/ecs/components/DropLootTest.java

fixes #288 
Ich werde nochmal darüber schauen, ob ich irgendwelche Tests vergessen habe.
Javadoc fehlt für die Tests und Doku allgemein fehlt noch.
Dieser PR basiert auf dem InventoryComponent und muss rebased werden, sobald der PR #388 durch ist.

[GAME] onDeath drop Loot

---

game/src/ecs/components/skill/DamageProjectileSkill.java
game/src/ecs/components/skill/FireballSkill.java
game/src/ecs/components/skill/ProjectileComponent.java
game/src/ecs/components/skill/SkillTools.java
game/src/ecs/entities/Entity.java
game/src/ecs/entities/Hero.java
game/src/ecs/systems/ProjectileSystem.java
game/src/starter/Game.java
game/test/ecs/EntityTest.java
game/test/ecs/entities/ChestTest.java
game/test/ecs/systems/AISystemTest.java
game/test/ecs/systems/CollisionSystemTest.java
game/test/ecs/systems/DrawSystemTest.java
game/test/ecs/systems/HealthSystemTest.java
game/test/ecs/systems/SkillSystemTest.java
game/test/ecs/systems/VelocitySystemTest.java
game/test/ecs/systems/XPSystemTest.java
game/test/ecs/tools/interaction/InteractionToolTest.java

fixes #486:
- Taste Q bringt das Spiel nicht mehr zum Abstürzen
- beim Rebase ist ein Set verloren gegangen, dies wurde wieder hinzugefügt
fixes #472 & fixes #471 :
- die Methode `SkillTools.calculateLastPositionInRange` wurde umgeschrieben und benutzt jetzt als Vektorrechnung um die Flugbahn und Distanz zu berechnen
- Projectile fliegt seine maximale Distanz unabhängig vom Cursor
- Flugbahn und Distanz werden korrekt berechnet
fixes #473 : 
- javadoc hinzugefügt

[GAME] Bugs in Skill behoben

---

game/src/graphic/DungeonCamera.java
game/src/starter/Game.java
game/src/tools/Constants.java
game/test/graphic/DungeonCameraTest.java

fix #403 
Ersetzen der alten, nicht funktionalen Tests mit neuen.

[Game] Fix DungeonCamera Tests

---

game/src/contrib/utils/components/item/ItemData.java

closes #575 
Die Klasse und Inhalte sollte genauer dokumentiert werden, da Studis beim Aufsammeln eines Items auf einen Fehler gestoßen sind.
Alle javadocs erweitert und im Speziellen die Methode defaultOnCollect() genauer beschrieben.

[Doc] add ItemData documentation

---

game/src/contrib/utils/components/ai/fight/RangeAI.java

Ich habe hier die Aufgabe Fernkampf bearbeitet.
fixes #140 (5p-bounty)

[GAME] add rangeCombat AI

---

doc/control-mechanisms/reporting.md
doc/dsl/readme.md

Fixes #541 
Fügt der Doku eine Beschreibung der Konzepte zum Reporting hinzu.

[Doc] Definiere Reporting-Konzept

---

game/src/contrib/utils/components/ai/transition/ProtectOnAttack.java
game/test/contrib/utils/components/ai/ProtectOnAttackTest.java

Fixes #143, die von @Pascal378 (und ggf. Team?) als Bounty-Aufgabe gelöst wurde.
Angepasst auf die neue Struktur des Dungeons.

[GAME] Implement ProtectOnAttack

---

game/src/contrib/utils/components/skill/Skill.java
game/test/contrib/systems/SkillTest.java
game/test/contrib/utils/components/skill/SkillTest.java

fixes #467
Die Tests für Skill wurden umgeschrieben und angepasst

[GAME] update skill tests

---

dungeon/src/quizquestion/QuizDialogDesign.java
dungeon/src/quizquestion/QuizQuestionUI.java
game/assets/skin/uiskin.json
game/src/core/hud/DialogDesign.java
game/src/core/hud/DialogFactory.java
game/src/core/hud/UITools.java

- radiobuttons für singlechoice Fragen
- Inhalt füllt immer die gesamte Fläche
- antworten sind linksbündig
- PauseMenü Text ist zentriert
fixes #615 
fixes #625

[Game][Dungeon] fix Dialog style

---

game/src/contrib/systems/ProjectileSystem.java

closes  #684
execute() so umgeschrieben, dass die PSData direkt weitergeleitet wird und Attribute in hasReachedEndpoint() auseinanderklamüsert werden

[GAME] ProjectileSystem execute verbessern

---

game/src/core/components/PositionComponent.java

In diesem Pull-Request wurde das `PositionComponent` refactored.

[GAME] refactor PositionComponent (JavaDoc, Clean Code)

---

game/src/contrib/entities/EntityFactory.java
game/src/core/components/PlayerComponent.java
game/test/core/components/PlayerComponentTest.java

In diesem Pull-Request wurde das `PlayerComponent` refactored.

[GAME] refactor PlayerComponent (JavaDoc, Clean Code)

---

game/src/contrib/systems/CollisionSystem.java

fixes #682
Einmal etwas mehr Doc und etwas besser Aufteilung der Methoden.

[GAME] CollisionSystem execute stream verbessern 

---

game/src/core/systems/HudSystem.java

Implementiert das Verhalten gewünscht in Issue #727 für das hudsystem aktuell sehe ich zwar keinen Grund, warum #727 damit dann nicht auch geschlossen wird, wollte es hier nur noch nicht anhängen, falls ich was vergesse.

[Game] improve hudsystem using new addEntity and removeEntity Observers

---

game/src/core/Game.java
game/src/core/configuration/KeyboardConfig.java
game/src/core/systems/CameraSystem.java
game/src/starter/Main.java

(fix #797)
- Fix das Strecken des Bildes bei Fenstergrößenänderungen.
- Hinzufügen von Vollbild (`F11`)

[GAME] Fix stretching on window rescale + Add Fullscreen

---

game/src/contrib/entities/AIFactory.java
game/src/contrib/entities/EntityFactory.java
game/src/contrib/utils/components/skill/SkillTools.java
game/src/core/Game.java
game/src/core/utils/MissingHeroException.java
game/src/starter/Main.java
game/test/contrib/entities/MonsterTest.java

fixes #239
Dies ist ein Hilfs-PR für PR #776 von @DaniBor.
Es wurde zusätzlich ein Rebase und eine Anpassung auf den aktuellen Master-Branch durchgeführt
Außerdem:
- Magic Numbers entfernt
- MissingHeroEception erstellt
- kleinere Anpassungen am Code für Lesbarkeit

[GAME] add Monsterbuilder to EntityFactory, add AIFactory, add MissingHeroException

---

game/src/contrib/components/CollideComponent.java

In diesem Pull-Request wurde das `CollideComponent` refactored.

[GAME] refactor CollideComponent (JavaDoc, Clean Code)

---

game/src/contrib/components/HealthComponent.java
game/src/contrib/entities/EntityFactory.java
game/test/contrib/components/HealthComponentTest.java

In diesem Pull-Request wurde das `HealthComponent` refactored.

[GAME] refactor HealthComponent (JavaDoc, Clean Code)

---

game/src/contrib/entities/EntityFactory.java

Es wurde eine MissingComponentException geworfen, da das Component für die AI benötigt wird aber erst danach initialisiert wird

[GAME] fix bug in EntityFactory

---

game/src/core/components/CameraComponent.java

In diesem Pull-Request wurde das `CameraComponent` refactored.

[GAME] refactor CameraComponent (JavaDoc, Clean Code)

---

game/src/contrib/components/ProjectileComponent.java

In diesem Pull-Request wurde das `ProjectileComponent` refactored.

[GAME] refactor ProjectileComponent (JavaDoc, Clean Code)

---

game/src/contrib/components/InventoryComponent.java
game/src/contrib/entities/EntityFactory.java
game/src/contrib/utils/components/health/DropLoot.java
game/src/contrib/utils/components/interaction/DropItemsInteraction.java
game/src/contrib/utils/components/item/ItemData.java
game/test/contrib/components/InventoryComponentTest.java
game/test/contrib/entities/ChestTest.java
game/test/contrib/utils/components/item/ItemDataTest.java

In diesem Pull-Request wurde das `InventoryComponent` refactored.

[GAME] refactor InventoryComponent (JavaDoc, Clean Code)

---

game/src/contrib/components/InteractionComponent.java
game/test/contrib/components/InteractionComponentTest.java

In diesem Pull-Request wurde das `InteractionComponent` refactored.
Dieser Pull-Request nimmt keine Änderungen am Logging (#683) oder an der Testabdeckung vor. 
PS: War das letzte Component <3

[GAME] refactor InteractionComponent (JavaDoc, Clean Code)

---

doc/dsl/typebuilding.md
dsl/src/interpreter/DSLInterpreter.java
dsl/src/runtime/EncapsulatedObject.java
dsl/src/runtime/IEvironment.java
dsl/src/runtime/RuntimeEnvironment.java
dsl/src/runtime/RuntimeObjectTranslator.java
dsl/src/semanticanalysis/types/ConsumerFunctionTypeBuilder.java
dsl/src/semanticanalysis/types/DSLCallback.java
dsl/src/semanticanalysis/types/FunctionFunctionTypeBuilder.java
dsl/src/semanticanalysis/types/IFunctionTypeBuilder.java
dsl/src/semanticanalysis/types/TypeBuilder.java
dsl/src/semanticanalysis/types/TypeInstantiator.java
dsl/test/interpreter/mockecs/MockEntityTranslator.java
dsl/test/interpreter/mockecs/TestComponentWithCallback.java
dsl/test/interpreter/mockecs/TestComponentWithFunctionCallback.java
dsl/test/interpreter/mockecs/TestComponentWithTriConsumerCallback.java
dsl/test/semanticanalysis/types/TestTypeBuilder.java
dungeon/src/dslToGame/EntityTranslator.java

[DSL] `DSLCallback`-Annotation in Typebuilding integrieren

---

game/src/core/Game.java

Ändert die Auflösung vom Fenster auf 1280x720 (HD, 16:9)

[Game] Standardauflösung von Fenster zu 16:9

---

game/src/contrib/utils/components/ai/AITools.java
game/src/contrib/utils/components/ai/AIUtils.java
game/src/contrib/utils/components/ai/fight/CollideAI.java
game/src/contrib/utils/components/ai/fight/MeleeAI.java
game/src/contrib/utils/components/ai/fight/RangeAI.java
game/src/contrib/utils/components/ai/idle/PatrouilleWalk.java
game/src/contrib/utils/components/ai/idle/RadiusWalk.java
game/src/contrib/utils/components/ai/idle/StaticRadiusWalk.java
game/src/contrib/utils/components/ai/transition/ProtectOnApproach.java
game/src/contrib/utils/components/ai/transition/RangeTransition.java
game/src/core/level/utils/LevelUtils.java

fixes #573 
Die Klasse `LevelUtils` wurde erstellt und einige Methoden aus `AITools` dahin verschoben.

[GAME] created `LevelUtils`, moved methods from `AITools`, rename `AITools` into `AIUtils` 

---

game/src/contrib/utils/components/draw/AdditionalAnimations.java
game/src/core/System.java
game/src/core/components/DrawComponent.java
game/src/core/utils/components/draw/CoreAnimations.java

- Make systems log their state only on toggle, not every time they run
- Fix "animation not set" warning logs

[Game] Fix logging & console spamming

---

doc/tasks/anleitung_task_test.md

Ich habe eine kleine Beschreibung hinzugefügt, wie das Spiel zu spielen ist.

[DEMO] add how to play

---

.github/CODEOWNERS

Fixes #895 
Im Meeting besprochen

Codeowner: reduziere Ownership auf Dungeon-Team

---

CITATION.cff

@AMatutat Bitte ein kurzes Review+Freigabe. Dieser PR fügt ein sogenanntes CFF hinzu, um Nachnutzenden eine korrekte Zitation zu ermöglichen.

[Org] add how to cite

---

game/src/core/level/utils/DesignLabel.java

Fügt dem `DesignLabel` eine Chance in Prozent hinzu, um von der `DesignLabel#randomDesign` Funktion zurückgegeben zu werden. 
Chance für Rainbow Level ist 0%

[GAME] add chance for DesignLabel to get picked

---

game/src/contrib/entities/EntityFactory.java

(closes #952)
Kisten haben jetzt ein Inventar, welches via GUI angezeigt wird, wenn mit ihnen interagiert wird.

[Game] Kisten haben ein Inventar, statt die Items fallen zu lassen

---

dsl/src/interpreter/DSLInterpreter.java
dsl/src/semanticanalysis/SemanticAnalyzer.java
dsl/src/semanticanalysis/VariableBinder.java
dsl/test/interpreter/TestDSLInterpreter.java

[DSL] Assignment-Expression implementieren

---

dungeon/src/task/quizquestion/QuizDialogDesign.java

Da gab es einen dreher im if-else Statement.

[Dungeon] fixed bug in the QuizUI where you could select multiple answers for SC and only one for MC 

---

game/src/contrib/configuration/KeyboardConfig.java
game/src/contrib/entities/EntityFactory.java
game/src/contrib/systems/HealthbarSystem.java
game/src/contrib/systems/HeroUISystem.java
game/src/core/components/UIComponent.java

Erster Ansatz, hier nutze ich einfach den zIndex vom libgdx actor. Dies kann noch in unsere Struktur gezogen werden, um ein von uns gesteuerten Stack oder anderes abzubilden.
Alternativ kann ja auch ein Stack von UI Elementen existieren, anhand welchen die UI Elemente gelöscht werden.
fixes #966

[Game] Globale Möglichkeit GUIs mit ESC zu schließen

---

dungeon/src/task/Task.java

[DUNGEON] add verschieden `TaskState`s für verschiedene Lösungsqualitäten

---

game/src/core/Game.java

[Game] fix pausemenu can be stacked

---

dungeon/src/task/QuestItem.java
game/src/contrib/components/InventoryComponent.java
game/src/starter/Main.java

@Lena241 ich habe heute mit @malt-r über #903 und #924 gesprochen
Ich habe die beiden Issues für den stand deines Item-rework Branches gefixt.
Kannst du eigentlich so übernehmen, dann beim testen mit betrachten.
Denk dran das in deinen PR als fixed zu markieren.

[Dungeon] for (fw/rework-item) add QuestItem and Inventory Filter

---

CONTRIBUTING.md
README.md

Changing 2 Links as the recent ones did not work.

Repo: fix invalid links

---

doc/related_work/digi_komp_ass_escape_room.md

fixes #1069 
Fügt die Kontaktdaten sowie einen weiteren Link zur Doukemnation hinzu.

[Antrag] add Kontaktdaten Educational Escape Room 

---

doc/related_work/designing_an_educational_game_evaluation_framework_based_on_game_mechanics.md

fixes #749 
Fügt eine kurze Zusammenfassung + Bewertung unserer Dokumentation hinzu. Ich glaube, für uns ist das Paper nicht besonders gewinnbringend."

[Related Work] add notes for "Designing an Educational Game Evaluation Framework Based on Game Mechanics"

---

game/src/core/utils/Constants.java

bringt das ganze geschehen etwas näher an die Kamera.

[GAME] change default camera zoom to 0.35

---

dungeon/src/task/Task.java
dungeon/test/task/TaskTest.java

[DUNGEON] add id to task

---

dungeon/src/task/Task.java
dungeon/src/task/components/TaskContentComponent.java

[DUNGEON] change `TaskContentComponent` so it only stores one `TaskContent`

---

game/src/contrib/hud/inventory/InventoryGUI.java

[GAME] use Entity name on Inventory HUD

---

game/src/contrib/entities/EntityFactory.java

Da wir aktuell im Spiel mit Feuerbällen um uns werfen, ist der Zauberer vielleicht eine bessere wahl für den Player.
Dieser Pr setzt die Texturen für den Helden auf die Texturen des Zauberes.

[GAME] use wizard textures for player character

---

game/src/contrib/entities/EntityFactory.java

fixes #1141
Das Spiel pausiert nun bei geöffneter Schatztruhe.

[GAME] Öffnen des Inventars der Schatztruhe pausiert das Spiel

---

dungeon/src/task/QuestItem.java

Man kann jetzt keine QuestItems mehr essen.

[DUNGEON] fix bug where you could eat questitems

---

dungeon/src/task/Task.java
dungeon/test/reporting/GradingFunctionsTest.java

Jetzt werden alle QuestItems aus den Spieler Inventar geworfen, wenn eine Task erledigt ist.

[DUNGEON] drop questitems after task is done

---

dungeon/src/starter/Starter.java

Spawn ein Craftingcauldron im vierten Raum.

[DUNGEON] spawn crafting cauldron on level 4

---

game/src/contrib/configuration/KeyboardConfig.java
game/src/contrib/entities/EntityFactory.java
game/src/core/Game.java
game/src/core/components/PlayerComponent.java

fixes #1175 
Die linke Maustaste kann nun zum Interagieren genutzt werden. Die Funktion ist dabei diesselbe wie mit der Taste E. Der Cursor muss sich auf dem Objekt, mit dem interagiert werden soll, befinden.

[GAME] Interaktion per Linksklick hinzugefügt

---

game/src/contrib/utils/components/skill/DamageProjectile.java
game/src/core/components/DrawComponent.java
game/src/core/components/VelocityComponent.java
game/src/core/systems/VelocitySystem.java

fixes #1020
Die letzten Abhängigkeiten zum `contrib` Package innerhalb von `core` wurden entfernt. 
Im Zusammenhang damit hat das VelocityComponent den Callback `onWallHit` bekommen.

[GAME] Abhängigkeiten zu `contrib` Package in `core` entfernt

---

game/src/contrib/hud/OkDialog.java
game/src/contrib/hud/UITools.java
game/src/contrib/utils/components/Debugger.java

Wir hatten so ein denglishes HUD, ich habe es mal auf Deutsch umgestellt.

[GAME] use german in hud

---

game/src/contrib/entities/EntityFactory.java
game/src/contrib/hud/crafting/CraftingGUI.java

Eine simple erste Implementierung des reagieren auf das Schließen eines Crafting UIs mithilfe der onClose vom UIComponent.
Fixes #1170

[Game] closing crafting UI uses onClose function to cancel crafting

---

game/src/contrib/item/Item.java
game/src/contrib/utils/components/interaction/DropItemsInteraction.java
game/src/contrib/utils/level/NoTileFoundException.java
game/src/core/level/utils/LevelUtils.java
game/test/contrib/utils/components/item/ItemTest.java

LevelUtils welches von der AI Logik genutzt wird gibt nicht mehr Tiles des Typens Tür zurück.
Außerdem wird beim Item.drop kontrolliert ob es sich um ein floortile handelt oder nicht.
fixes #1171

[Game] AI no longer goes onto doors, dropping items only on FloorTile

---

dungeon/src/dsl/antlr/DungeonDSL.g4
dungeon/src/dsl/parser/DungeonASTConverter.java
dungeon/src/dsl/parser/ast/ObjectDefNode.java

[DSL] Cleanup von obsoleten Strukturen aus der Grammatik und ASTConverter

---

game/doc/readme.md

Soll direkt vor #1227 gemerged werden, um den commit zu taggen.

[ORG] add Tag `before-remove-unused-features`

---

game/src/contrib/utils/components/ai/fight/RangeAI.java
game/src/contrib/utils/components/ai/transition/ProtectOnAttack.java

fixes #825
Die Klasse `ProtectOnAttack` hat die Methode `doSetup` bekommen und checkt nun dort erst auf das HealthComponent und nicht bereits im Konstruktor.

[GAME] Existenz des `HealthComponent`s in `ProtectOnAttack` wird zur Laufzeit geprüft

---

game/src/core/systems/PositionSystem.java

Setzt #1025 für das `PositionSystem` um

[GAME] cleanup `PositionSystem` 

---

game/src/core/System.java

setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `System` um.

[GAME] cleanup class `System`

---

game/src/core/System.java
game/src/core/game/GameLoop.java

[Game] allow systems to be only run every x frames

---

game/src/contrib/utils/components/skill/SkillTools.java

Setzt #178 für die Klasse `SkillTools` um.

[GAME] cleanup class `SkillTools`

---

game/src/contrib/utils/components/Debugger.java
game/src/core/components/VelocityComponent.java

setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `VelocityComponent` um.

[GAME] cleanup `VelocityComponent` 

---

game/src/core/systems/DrawSystem.java

setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `DrawComponent` um.

[GAME] cleanup `DrawSystem` 

---

game/src/core/systems/VelocitySystem.java

setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `VelocitySystem` um.

[GAME] cleanup `VelocitySystem` 

---

game/src/core/systems/CameraSystem.java

setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `CameraSystem` um.

[GAME] cleanup `CameraSystem` 

---

game/src/core/systems/LevelSystem.java

setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `LevelSystem` um.

[GAME] cleanup `LevelSystem` 

---

game/src/contrib/level/generator/graphBased/RoombasedLevelGenerator.java
game/src/core/level/Tile.java
game/src/core/level/elements/tile/DoorTile.java
game/src/core/level/elements/tile/ExitTile.java
game/src/core/level/elements/tile/FloorTile.java
game/src/core/level/elements/tile/HoleTile.java
game/src/core/level/elements/tile/SkipTile.java
game/src/core/level/elements/tile/TileFactory.java
game/src/core/level/elements/tile/WallTile.java
game/src/core/systems/LevelSystem.java
game/test/core/level/TileLevelTest.java
game/test/core/level/TileTest.java

Setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `Tile` sowie die spezfischen sub-Tiles hinzu .

[GAME] cleanup `Tile` 

---

game/src/core/level/utils/Coordinate.java
game/src/core/level/utils/DesignLabel.java
game/src/core/level/utils/LevelElement.java
game/src/core/level/utils/LevelSize.java
game/src/core/utils/IVoidFunction.java
game/src/core/utils/Point.java
game/src/core/utils/TriConsumer.java
game/src/core/utils/Tuple.java
game/src/core/utils/logging/LoggerConfig.java

Setzt #1025 für Utill-Klassen um. Das waren überwiegend fehlende `finals` oder kleinere typos in der Javadoc. 
Daher dieser Sammel-PR. Das erstellen einzelner PRs hätte hier mehr Zeit gekostet als die fixes selbst.

[GAME] small cleanups for small classes

---

game/src/core/utils/components/draw/Painter.java
game/src/core/utils/components/draw/PainterConfig.java
game/src/core/utils/components/draw/TextureMap.java

Setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für Utill-Klassen `Painter`, `PainterConfig`, `TextureMap`

[Game] cleanup `Painter` 

---

game/src/core/level/TileLevel.java

Setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `TileLevel` um.

[GAME] cleanup `TileLevel`

---

game/src/core/level/utils/LevelUtils.java

Setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `LevelUtils` um.

[GAME] cleanup `LevelUtils` 

---

dungeon/test/dsl/interpreter/TestDSLInterpreter.java
game/doc/animation.md
game/src/contrib/entities/MiscFactory.java
game/src/core/Game.java
game/src/core/game/ECSManagment.java
game/src/core/game/GameLoop.java
game/src/core/game/PreRunConfiguration.java
game/src/core/utils/components/draw/Animation.java

Setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `Game`, `ECSManager`, `GameLoop`, `PreRunConfiguration` und `Animation`  um.
Fügt eine separate Dokumentation für die Animation hinzu. 
@Lena241 sorry für den supper PR, ich hab irgendwie meine Branches durcheinandergebracht und hab jetzt auch etwas Angst beim aufsplitten etwas zu verlieren.

[GAME] cleanup `Game` and `Animation` 

---

game/src/core/utils/EntitySystemMapper.java

[GAME] cleanup EntitySystemMapper

---

game/src/contrib/utils/components/skill/DamageProjectile.java
game/src/contrib/utils/components/skill/FireballSkill.java

Setzt #178 für die Klassen `DamageProjectile` und `FireballSkill` um.

[GAME] cleanup class `DamageProjectile` & `FireballSkill`

---

game/src/contrib/entities/MiscFactory.java
game/src/contrib/entities/MonsterFactory.java
game/src/contrib/utils/components/item/ItemGenerator.java
game/test/contrib/entities/ChestTest.java

Setzt #178 für die Klasse `ItemGenerator` um.

[GAME] cleanup class `ItemGenerator`

---

game/src/contrib/utils/components/ai/AIUtils.java
game/src/contrib/utils/components/ai/fight/CollideAI.java
game/src/contrib/utils/components/ai/fight/MeleeAI.java
game/src/contrib/utils/components/ai/fight/RangeAI.java
game/src/contrib/utils/components/ai/idle/PatrolWalk.java
game/src/contrib/utils/components/ai/idle/RadiusWalk.java
game/src/contrib/utils/components/ai/idle/StaticRadiusWalk.java
game/src/contrib/utils/components/ai/transition/ProtectOnApproach.java
game/src/contrib/utils/components/ai/transition/ProtectOnAttack.java
game/src/contrib/utils/components/ai/transition/RangeTransition.java
game/src/contrib/utils/components/ai/transition/SelfDefendTransition.java

Setzt #178 für die Klassen in `contrib.utils.components.ai` um.

[GAME] cleanup `contrib.utils.components.ai`

---

blockly/src/client/Client.java
dungeon/src/starter/Starter.java
dungeon/test/manual/taskgeneration/TaskGenerationTest.java
game/src/contrib/systems/AISystem.java
game/src/contrib/systems/CollisionSystem.java
game/src/contrib/systems/HealthBarSystem.java
game/src/contrib/systems/HealthSystem.java
game/src/contrib/systems/HudSystem.java
game/src/contrib/systems/IdleSoundSystem.java
game/src/contrib/systems/ProjectileSystem.java
game/src/contrib/systems/SpikeSystem.java
game/src/starter/RandomDungeon.java
game/src/starter/RoomBasedDungeon.java

Setzt #178 für die Klassen in `contrib.utils.systems` um.
@AMatutat Sorry, dass das gleich alle Systeme auf einmal sind. Die Änderungen sind aber überschaubar und man wird wahnsinnig wenn man für jede Klasse einen PR aufmacht.

[GAME] cleanup `contrib.utils.systems`

---

blockly/src/client/Client.java
dungeon/src/graph/TaskGraphConverter.java
dungeon/test/task/TaskContentDoorOpenerTest.java
game/src/contrib/level/generator/graphBased/CantPlaceDoorException.java
game/src/contrib/level/generator/graphBased/LevelGraphGenerator.java
game/src/contrib/level/generator/graphBased/RoomBasedLevelGenerator.java
game/src/contrib/level/generator/graphBased/RoomGenerator.java
game/src/contrib/level/generator/graphBased/levelGraph/Direction.java
game/src/contrib/level/generator/graphBased/levelGraph/LevelGraph.java
game/src/contrib/level/generator/graphBased/levelGraph/LevelNode.java
game/src/starter/RoomBasedDungeon.java

Setzt #178 für die Klassen in `contrib.level.generator.graphBased` um.

[GAME] cleanup `contrib.level.generator.graphBased`

---

dungeon/src/dslinterop/dsltypeproperties/EntityExtension.java
dungeon/src/dslinterop/nativescenariobuilder/NativeScenarioBuilder.java
game/src/contrib/entities/MiscFactory.java
game/src/contrib/systems/HealthSystem.java
game/src/contrib/utils/components/interaction/DropItemsInteraction.java
game/src/core/components/DrawComponent.java
game/src/core/systems/DrawSystem.java
game/test/core/components/DrawComponentTest.java

setzt https://github.com/Programmiermethoden/Dungeon/issues/1025 für die Klasse `DrawComponent` um.

[GAME] cleanup `DrawComponent` 

---

dungeon/src/starter/KeyboardConfig.java
dungeon/src/starter/Starter.java
game/src/contrib/configuration/KeyboardConfig.java

Setzt #178 für die Klassen in `contrib.Keyboardconfig` um.

[GAME] cleanup `contrib.KeyboardConfig` 

---

blockly/src/client/Client.java
dungeon/src/starter/Starter.java
game/src/contrib/crafting/Crafting.java
game/src/contrib/crafting/CraftingIngredient.java
game/src/contrib/crafting/CraftingResult.java
game/src/contrib/crafting/CraftingType.java
game/src/contrib/crafting/InvalidRecipeException.java
game/src/contrib/crafting/Recipe.java
game/src/contrib/item/Item.java
game/src/starter/RandomDungeon.java
game/src/starter/RoomBasedDungeon.java

Setzt #178 für die Klassen in `contrib.crafting` um.

[GAME] cleanup `contrib.crafting` 

---

doc/related_work/mapping_learning_and_game_mechanics_for_serious_games_analysis.md

fixes #1103 
Ich konnte das Paper noch nicht in der tiefe durchdringen und hab es eher überflogen, daher ist die zusammenfassung auch recht kurz. 
Ich will es trotzdem festhalten, könnte sich lohnen das nochmal richtig durchzuarbeiten.

[Publication] add related work Mapping learning and game mechanics for serious games analysis

---

dungeon/src/dslinterop/dsltypeadapters/DrawComponentAdapter.java
dungeon/src/dslinterop/nativescenariobuilder/NativeScenarioBuilder.java
dungeon/src/starter/TaskSelector.java
dungeon/test/manual/quizquestion/CallbackTest.java
dungeon/test/manual/taskgeneration/TaskGenerationTest.java
game/src/contrib/entities/EntityFactory.java
game/src/contrib/entities/HeroFactory.java
game/src/contrib/entities/MiscFactory.java
game/src/contrib/entities/MonsterFactory.java
game/src/contrib/utils/components/Debugger.java
game/src/contrib/utils/components/skill/DamageProjectile.java
game/src/contrib/utils/components/skill/FireballSkill.java
game/src/core/components/DrawComponent.java
game/src/core/utils/components/draw/Animation.java
game/test/contrib/systems/HealthSystemTest.java
game/test/core/components/DrawComponentTest.java
game/test/core/systems/VelocitySystemTest.java

[Game] Only using IPath interface in DrawComponent

---

game/src/core/level/Tile.java
game/src/core/level/TileLevel.java
game/src/core/level/elements/tile/DoorTile.java
game/src/core/level/elements/tile/ExitTile.java
game/src/core/level/elements/tile/FloorTile.java
game/src/core/level/elements/tile/HoleTile.java
game/src/core/level/elements/tile/SkipTile.java
game/src/core/level/elements/tile/TileFactory.java
game/src/core/level/elements/tile/WallTile.java
game/src/core/level/utils/TileTextureFactory.java
game/src/core/systems/LevelSystem.java
game/test/core/level/TileLevelAPITest.java
game/test/core/level/TileLevelTest.java
game/test/core/level/TileTest.java
game/test/core/level/TileTextureFactoryTest.java
game/test/core/level/elements/tile/TileFactoryTest.java

Aufräumen von den Tiles für #1143

[Game] Tiles no longer using Strings for texture paths

---

game/src/core/Game.java

`Game#loadConfig` kann nun dynamisch viele `keyboardConfigClass`es einlesen.

[GAME] update `Game#loadConfig`

---

doc/related_work/partner.md
doc/related_work/startplay_poster.md

Fixes #1071
Für eigene Dokumente scheinen mir weder die Poster noch die Linksammlung geeignet zu sein, aber zum Festhalten durchaus interessant.
Gerade die Firmen könnten für zukünftige Projekte ggf. als Partner interessant sein. Offenbar sind sie ja für Gamification offen.
BibKey etc. gibts noch nicht (ich hoffe die schaffen das mit dem Konferenzband noch)

[DOC] add StarPlay contacts

---

dungeon/src/dsl/interpreter/DSLInterpreter.java
dungeon/src/dsl/semanticanalysis/analyzer/FunctionDefinitionBinder.java
dungeon/src/dsl/semanticanalysis/analyzer/SemanticAnalyzer.java
dungeon/src/dsl/semanticanalysis/analyzer/TypeBinder.java
dungeon/test/dsl/helpers/Helpers.java
dungeon/test/dsl/interpreter/TestEnvironment.java
dungeon/test/dsl/semanticanalysis/TestTypeBinder.java

[DSL] Erzeugt Set, List und Map Datentypen in `TypeBinder`

---

doc/wiki/code-conventions.md

@AMatutat Eigentlich sollte ich Dich als Reviewer assignen :/  Schaust Du Dir Deine Arbeitsergebnisse eigentlich nicht an?

doc: fix broken markdown

---

.github/dependabot.yml
build.gradle
dependencies.gradle

Bases on #1322 (should be merged first)
fixes #1349

Gradle Config: Dependabot Expansion

---

.github/workflows/github_ci.yml

CI: run JUnit@Linux always, and @Mac/@Win only if tests changed

---

dungeon/src/starter/Starter.java

closes #1430 
Changes: Error handling in main() method of dungeon starter adjusted.

Dungeon Starter: improve error handling

---

dungeon/src/starter/Starter.java
game/src/core/configuration/Configuration.java

@tgrothe Ich habe mal Deinem #1433 hintergeräumt. So in etwa habe ich mir das eigentlich vorgestellt. Bitte ein kurzes Review, ob das so bei Dir läuft.

Refactoring: clean-up after #1433 (Dungeon-Starter: configGame())

---

dungeon/src/entrypoint/DSLFileLoader.java
dungeon/src/starter/Starter.java
dungeon/test/manual/taskgeneration/TaskGenerationTest.java

@tgrothe Ich habe mal Deinem #1433 hintergeräumt. So in etwa habe ich mir das eigentlich vorgestellt. Bitte ein kurzes Review, ob das so bei Dir läuft.

Refactoring: clean-up after #1433 (Dungeon-Starter: processCLIArguments())

---

dungeon/src/starter/Starter.java

@tgrothe Ich habe mal Deinem #1433 hintergeräumt. So in etwa habe ich mir das eigentlich vorgestellt. Bitte ein kurzes Review, ob das so bei Dir läuft.

 Refactoring: clean-up after #1433 (Dungeon-Starter: selectSingleDngFile())

---

dojo-dungeon/src/dojo/compiler/DojoCompiler.java
dojo-dungeon/src/dojo/rooms/rooms/riddle/Fehler_Syntax.java
dojo-dungeon/todo-assets/Fehler_Syntax/FehlerhafteKlasse.java

modified:   dojo-dungeon/src/dojo/rooms/rooms/riddle/Fehler_Syntax.java
modified:   dojo-dungeon/todo-assets/Fehler_Syntax/FehlerhafteKlasse.java
closes #1501

Dojo: Refactoring FehlerhafteKlasse.java

---

dojo-dungeon/src/dojo/rooms/Room.java
dojo-dungeon/src/dojo/rooms/rooms/riddle/Fragen_Pattern.java
dojo-dungeon/src/starter/DojoStarter.java

Die Pattern sollen in zufälliger Reihenfolge präsentiert werden. Dabei soll es keine Wiederholungen geben, d.h. jede Frage soll maximal einmal präsentiert werden.
Bei falschen Antworten nimmt der Hero Schaden (aktuell 50% der max. Health). Der Wert kann über eine Konstante konfiguriert werden.
Die Anzahl der zum Weiterkommen nötigen korrekten Antworten wird über eine Konstante definiert (aktuell 1).
closes #1518 closes #1512

Dojo: present questions randomly (level 2, pattern task)

---

gradle/wrapper/gradle-wrapper.properties
gradlew

https://docs.gradle.org/8.8/release-notes.html
`./gradlew wrapper --gradle-version 8.8`

Gradle: upgrade to v8.8

---

game/src/core/level/utils/LevelUtils.java

Ich habe `LevelUtils` angepasst, um die Robustheit zu erhöhen, indem ich Null-Checks hinzugefügt habe, um NullPointerExceptions zu vermeiden. Zudem habe ich einige leere Zeilen entfernt und die Methode `isAnyCornerOfTileInRadius` korrigiert.
- `LevelUtils.java`: Null-Checks hinzugefügt, um NullPointerExceptions zu vermeiden.
- Null-Check in `calculatePath` Methode hinzugefügt.
- Leere Zeilen entfernt.
- Methode `isAnyCornerOfTileInRadius` korrigiert.

Core: Improve robustness of LevelUtils and fix LevelUtils#isAnyCornerOfTileInRadius

---

dungeon/src/contrib/entities/HeroFactory.java
game/src/core/Game.java

Dieser PR optimiert die HeroFactory-Klasse durch Code-Refactoring und verbessert die UI-Interaktionen für eine intuitivere Spielerfahrung.
- **HeroFactory.java**:
- Einführung der `registerMovement`-Hilfsmethode zur Reduzierung von Code-Duplikation bei der Bewegungsregistrierung.
- Anpassung der UI-Interaktionen: Inventar und Kisten/Kessel können nun mit derselben Taste geöffnet und geschlossen werden.
- Aktualisierung der `INTERACT_WORLD`-Callback-Logik für verbesserte UI-Handhabung.
- Statt zwei Fields für den `SPEED_HERO, wird jetzt ein Vector2 verwendet.`
- Hinzufügung eines Game-Over-Dialogs beim Tod des Helden.
- **Game.java**:
- Hinzufügung einer `exit()`-Methode zum Beenden der GDX-Anwendung.
Diese Änderungen wurden eingeführt, um die Codequalität zu verbessern und die …

Dungeon: enhance UI interactions (HeroFactory)

---

dungeon/src/contrib/components/PathComponent.java
dungeon/src/contrib/systems/PathSystem.java

Kleines Refactoring zur Verbesserung der Lesbarkeit des neuen `PathSystems` (nach #1586)

Dungeon: improve readability of PathSystem

---

build.gradle

https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-10.18.0

Tooling: bump checkstyle to v10.18.0

---

settings.gradle

remove sub-projects, which are not running and/or not used any more

Gradle: remove defective and obsolete sub-projects

---

blockly/build.gradle
blockly/frontend/src/api/api.ts
blockly/frontend/src/generators/java.ts
blockly/frontend/src/generators/java/arrays.ts
blockly/frontend/src/generators/java/functions.ts
blockly/frontend/src/generators/java/loops.ts
blockly/frontend/src/generators/java/variables.ts
blockly/frontend/src/index.ts
blockly/frontend/src/toolbox.ts
blockly/src/antlr/BlocklyConditionVisitor.java
blockly/src/antlr/blocklyConditionVisitor.java
blockly/src/client/Client.java
blockly/src/server/Server.java
blockly/test/TestServer.java

Dieser PR bringt folgende Verbesserungen: ein neuer Gradle Task buildBlocklyJar für die Erstellung der Blockly Dungeon JAR, API-Error Handling, behobene Frontend-Code-Style Fehler, eine sichere Beendigung des Http Servers und die Einführung eines Standard-Startblocks im Blockly Frontend.
* `blockly/build.gradle`: Neue Gradle Task `buildBlocklyJar` um eine JAR für den Blockly Dungeon zu erstellen.
* `blockly/frontend/src/api/api.ts`: Error Handling bei Post Request an Blockly Client
* Alle Style Check Feher behoben, um auch das Projekt bauen zu können.
* Da einige Types unbekannt sind, wurde an manchen stellen `any` verwendet als Workaround.
* `blockly/src/server/Server.java`, `blockly/src/client/Client.java`: Im Java Code wird jetzt der Http Server sicher beendet. So wird auch der Java …

Blockly: Singleton BlocklyServer, Fixed style check errors, safe server shutdown, default start-block

---

blockly/src/server/Server.java

Die Zielrichtung der Feuerbälle wurde korrigiert. Statt einer ungenauen Verschiebung um `+1` wird nun `Integer.MAX_VALUE` bzw. `Integer.MIN_VALUE` verwendet, um eine genauere Richtung sicherzustellen.  
Die Feuerball-Logik in `Server` wurde refaktoriert, um Code-Duplizierung zu vermeiden. Die wiederholte Implementierung der Angriffsfunktion wurde durch eine zentrale Methode (`shootFireBall`) ersetzt.  
fixes #1690

Blockly: Fix fireball direction

---

blockly/frontend/src/blocks/dungeon.ts
blockly/frontend/src/config.ts
blockly/frontend/src/generators/java.ts
blockly/frontend/src/generators/java/character.ts
blockly/frontend/src/generators/java/condition.ts
blockly/frontend/src/generators/java/directions.ts
blockly/frontend/src/generators/java/skills.ts
blockly/frontend/src/index.ts
blockly/frontend/src/toolbox.ts
blockly/src/antlr/BlocklyConditionVisitor.java
blockly/src/blockly.g4
blockly/src/nodes/BaseNode.java
blockly/src/nodes/Types.java
blockly/src/server/Server.java
blockly/src/utils/Direction.java

Ich habe die Condition Blöcke in Blockly refactored. Die Blöcke haben jetzt einen `Direction` Block, der auch für Aktionen wie `Move` und `Feuerball` verwendet werden kann. Dabei wurden alle Blöcke mit fester Richtung entfernt und durch einen Block mit Richtungs-Parameter ersetzt. Außerdem wurden manche Type-Checks in Blockly angepasst. Ein Bug beim SKIP Button, bei dem eine falsche Instanz der Blöcke verwendet wurde, wurde behoben. Zudem wurde der Support für Parameter im Java Code verbessert und die Blockly Grammar um die Unterstützung von Strings erweitert, wodurch auch Funktionsaufrufe eine höhere Priorität erhalten. Im Java Code wurden Methoden aufgeräumt und auf parametrisierte Methoden umgestellt. Eine neue `Direction.java` Klasse wurde ergänzt, die in der Blockly Block Logik …

Blockly: Refactor Condition Blocks and Add Direction Block

---

dungeon/src/contrib/entities/LeverFactory.java
dungeon/src/contrib/utils/ICommand.java

fixes https://github.com/Dungeon-CampusMinden/Dungeon/pull/1804#discussion_r2002980722

[contrib] cleanup `ICommand`

---

.github/CODEOWNERS

@AMatutat Ich denke, wir sollten die Codeowner doch wieder reaktivieren. So kann ich sicherstellen, dass einer von euch beiden (Du || @Flamtky) ein Review gemacht hat, bevor gemergt werden kann ...

Org: add AMatutat and Flamtky to codeowners

---

game/src/core/components/PositionComponent.java

PositionComponent#position(Tile)so it center the entity on the tile
In Blockly wird der Held dadurch immer zentriert (beim level laden)

[Core] update `PositionComponent#position(Tile)`so it center the entity on the tile

---

game/src/core/level/TileLevel.java

beim pathfinding erstellen fehlte ein null check

Core: add check for null tile

---

blockly/frontend/src/utils/variableList.ts
blockly/src/server/Server.java

fixes #1830 
- upgrade `variablelist.ts` => zeigt jetzt auch Variablen an, die nicht über das UI angelegt wurden
- in `Server.java` => Sende die Feuerball Munition als Variable mit
Die Anzeige wird erst mit dem "Start"-Knopf aktualisiert.

[Blockly] add fireball ammunition to web ui

---

escape-room/doc/sources/shroff2019immersion.md

das paper geht auf viele fragen ein, die sich mir unterwegs so gestellt haben. leider nicht immer mit abschließenden antworten und einer (gemessen an dem, was wir wollen) sehr kurz gegriffene umsetzung.

escape-room: add source 'shroff2019immersion'

---

blockly/src/produsAdvanced/AdvancedDungeon.java
blockly/src/produsAdvanced/abstraction/Fireball.java
blockly/src/produsAdvanced/abstraction/FireballSkill.java
blockly/src/produsAdvanced/abstraction/Hero.java
blockly/src/produsAdvanced/level/AdvancedBerryLevel.java
blockly/src/produsAdvanced/riddles/MyFireball.java

Abstract fireball logic | fix cooldown

---

escape-room/doc/research/design.md
escape-room/doc/research/sources/nicholson2015meaningful.md

They are used from research/design.md

Escape: add missing a tags

---

escape-room/doc/analog_escape_room/evaluation.md
escape-room/doc/analog_escape_room/readme.md
escape-room/doc/research/evaluation.md
escape-room/doc/research/readme.md

Sammlung von Anforderungen, Notizen, Gedanken und Rechercheergebnissen betreffend der Evaluierung des analogen Escape-Rooms

Escape: add document to collect evaluation parameters

---

build.gradle

- enforce also target compatibility
- use uniform version string

tooling: enforce JDK21

---

blockly/src/utils/BlocklyCodeRunner.java
blockly/vs-code-extension/package.json
blockly/vs-code-extension/src/handlers/sendBlocklyFile.ts

Jetzt werden auch bestimme Fehler im User-Code reingeschrieben, statt wie vorher einfach nur `null`.
Ich habe auch neue Imports für Components im Wrapper ergänzt.

Blockly: Better error logging for CodeRunner | more imports

---

advancedDungeon/src/produsAdvanced/level/AdvancedControlLevel1.java
advancedDungeon/src/produsAdvanced/level/AdvancedControlLevel2.java
advancedDungeon/src/produsAdvanced/level/AdvancedControlLevel3.java
advancedDungeon/src/produsAdvanced/level/AdvancedControlLevel4.java
advancedDungeon/src/produsAdvanced/level/AdvancedSortLevel.java

Ich habe in den Leveln 1-4 und 9 die Hilfetexte angepasst und ab dem Punkt an dem der Spieler interagieren kann Schilder eingefügt, die detaillierter werdende Tips geben, wie das Level gelöst werden kann.

Advanced dungeon: update task texts for herocontroll and array sort

---

.checkstyle.xml
blockly/src/server/LanguageServer.java
build.gradle

10.26.0 has support for records
see https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-10.26.0

Bump checkstyle from 10.19.0 to 10.26.0

---

advancedDungeon/src/produsAdvanced/abstraction/Hero.java

fixes #2159 
registriert einen Callback für jeden LibGDX Input.Key im AdvancedDungeon Hero

AdvancedDungeon: Leite alle Keyboardinteraktionen weiter

---

blockly/tooling/install.sh
blockly/tooling/install_doc.md
blockly/tooling/update.sh
blockly/tooling/update_doc.md

Die zwei Skripts die wir für die Raspberry PIs verwendet haben.
* update.sh: Das ist das Skript mit dem wir regelmäßig die PIs geupdatet haben.
* install.sh: Das installiert alle Abhängigkeiten bei einen neuen PI.
closes #2070

Blockly: Update and install script for PIs

---

blockly/tooling/install.sh
blockly/tooling/install_doc.md
blockly/tooling/update.sh
blockly/tooling/update_doc.md

Die zwei Skripts die wir für die Raspberry PIs verwendet haben.
* update.sh: Das ist das Skript mit dem wir regelmäßig die PIs geupdatet haben.
* install.sh: Das installiert alle Abhängigkeiten bei einen neuen PI.
closes #2070

Blockly: Update and install script for PIs (#2176)

---

advancedDungeon/build.gradle
blockly/build.gradle
devDungeon/build.gradle
dungeon/build.gradle
settings.gradle

@AMatutat Ich habe Dir für #2221 die Gradle-Config gefixt.

Clean-up: fix gradle config

---

blockly/src/utils/BlocklyCodeRunner.java
dungeon/src/core/Game.java

Dungeon: hotfix import in Blockly Code + tileAT calling itself

---

escape-room/doc/research/sources/escape_room_design_as_a_game-based_learning_process_for_steam_education.md
escape-room/doc/research/sources/sources.bib

Neben der Inhaltlichen Idee (the creation is the process) haben die viele Beispiele anderer Escape Rooms und Grandlagenpaper erwähnt.
Die hab ich mir nicht angeschaut, aber wenn mal mehr beispiele siucht

paper: Escape room design as a game-based learning process for STEAM

---

advancedDungeon/src/aiAdvanced/starter/ComparePathfindingStarter.java
advancedDungeon/src/aiAdvanced/starter/PathfinderStarter.java
advancedDungeon/src/produsAdvanced/level/AdvancedControlLevel3.java
advancedDungeon/src/produsAdvanced/level/AdvancedControlLevel4.java
devDungeon/src/level/devlevel/TutorialLevel.java
devDungeon/src/utils/EntityUtils.java
dungeon/src/contrib/utils/components/Debugger.java
dungeon/src/contrib/utils/components/ai/fight/RangeAI.java
dungeon/src/core/Game.java
dungeon/src/core/game/GameLoop.java
dungeon/src/core/level/TileLevel.java
dungeon/src/core/level/elements/ILevel.java
dungeon/src/core/level/loader/DungeonLevel.java
dungeon/src/core/level/loader/DungeonSaver.java
dungeon/src/core/systems/CameraSystem.java
dungeon/test/core/level/TileLevelTest.java
dungeon/test/core/systems/CameraSystemTest.java
dungeon/test/core/systems/LevelSystemTest.java

* lässt `TileLevel` das interface `ITickable` implementieren
* Es wird kein random start oder end mehr platziert.
* verwendet jetzt `Optional` für `#exitTile()` und `#startTile()`
* entfernen nicht verwendeter/überflüssiger API-Funktionen
* add quality of life functions to api

Dungeon:  cleanup level api: `TileLevel` now implements `ITickable`; use `Optional` for `#exitTile` and `startTile`;

---

escape-room/doc/research/leitfragen_gamebasedlearning_mit_deer.md

> **Zielsetzung:**  
> Dieses Dokument dient dazu, eine strukturierte Grundlage für die Literaturrecherche zu schaffen  
> und die erarbeiteten Ergebnisse nachhaltig festzuhalten.  
> Erkenntnisse sollen so dokumentiert werden, dass sie später leicht wiederauffindbar und verwertbar sind.
> Ziel ist es, eine verlässliche Wissensbasis aufzubauen, auf die das gesamte Team zugreifen kann.
> **Hinweis zur Bearbeitung:**  
> Jede der folgenden Leitfragen soll wissenschaftlich fundiert und gut belegt beantwortet werden.  
> Achte dabei auf eine angemessene Flughöhe – weder zu oberflächlich noch zu tief im Detail.  
> Verwende nach Möglichkeit einschlägige Literatur und Studien.  
> Alle Quellen sind im BibTeX-Format in der Datei [`sources.bib`](./sources/sources.bib) zu hinterlegen und im Text …

Research: add key question about gbl and deer

---

devDungeon/src/starter/DevDungeon.java
dungeon/src/contrib/utils/components/ai/transition/SelfDefendTransition.java

Die Methode apply() wurde in eine kompakte und funktionale Schreibweise umgewandelt. 
Die neue Version ist übersichtlicher und nutzt direkt die map()-Funktion, um die Bedingung zu prüfen. 
Das Verhalten der Methode bleibt identisch.

Refactoring der Klasse SelfDefendTransition zur besseren Lesbarkeit und Verständlichkeit

---

dungeon/src/contrib/utils/components/health/DamageType.java

Ich habe passende Kommentare hinzugefügt.

Dungeon: refactor `DamageType`

---

dungeon/src/core/level/elements/tile/ExitTile.java

Macht Ausgänge die geschlossen sind auch nicht accessible. 
Analog zu den Türen

Dungeon: make closed exits not accessible

---

escapeRoom/src/tools/Timer.java

fügt ene Util Function hinzu, um einen Countdown zu erstellen.
Ohne UI anzeige.

Escaperoom: add timer to end game (without ui) 

---

dungeon/src/core/components/DrawComponent.java

Ich hab die Javadoc mal angepasst. Das verwirrt mich jedes mal

Dungeon: update javadoc for Tint in DrawComponent

---

dungeon/src/contrib/systems/DebugDrawSystem.java
escapeRoom/src/starter/DemoRoom.java

Fügt ein System hinzu, welches
* Position als Orangen Diamant
* Viewdirection als "Pfeil"
* Texture Size als grüne Box
* Hitbox als rote Box 
sichtbar einzeichnet.
Beim bewegen wackeln die Boxen etwas, das hat was mit der Camera in libGDX zu tun.
Als Debug tool sollte das erstmal so funktionieren.
https://github.com/user-attachments/assets/df9c687e-d783-48f1-9387-6fb0c9eef574

Dungeon: add DebugDrawSystem

---

advancedDungeon/src/produsAdvanced/abstraction/portals/PortalFactory.java

Wie hier erwähnt https://github.com/Dungeon-CampusMinden/Dungeon/pull/2541#discussion_r2391111895 wurden die statischen variablen für die Entities und Direction entfernt und ersetzt.

AdvancedDungeon: removed unnecessary static variable for entities and direction

---

dungeon/src/contrib/hud/UIUtils.java

fixes #2559
Hab in der Funktion korrektes Optional Handling eingebaut. Beim laden eines neuen Levels kann es sein, dass der Held kurzzeitig nicht im Spiel ist und dann ist das DIng explodiert.

Dungeon: fix Optional handling in UITools#show
